### ISSUE TITLE
Crash when loading chunk containing Mimicube with certain armor (1.16.0 to 1.17.2)

### ISSUE THREAD

**Issue by antoine-courant** [Alex-the-666/AlexsMobs#1000]
All was fine while playing the 1.16.0 version of the mod
I recently updated to 1.17.2 version, and when I'm loading a chunk containing a mimicube with an armor rendered (spiky shell turtle helmet, according to the crash report) I got kicked
I know it's whilme loading this specfic chunk because another player was able to join but got kicked as well when going to the chunk in question
Here is the crash log
[crash-2022-03-20_18.33.05-client.txt](https://github.com/Alex-the-666/AlexsMobs/files/8311828/crash-2022-03-20_18.33.05-client.txt)

**Comment by AlexModGuy** [comment]
update forge version
