### ISSUE TITLE
Mob Spawning breaking in 1.16.5

### ISSUE THREAD

**Issue by DoctorMage** [Alex-the-666/AlexsMobs#1041]
Forge Version
36.2.33

Mods invovled
Aquaculture-1.16.5-2.1.22
alexsmobs-1.12.1
environmental-1.16.5-1.1.1
fins-1.6.2.jar
productivebees-1.16.5-0.6.9.25.jar
mysticalworld-1.16.5-0.3.6.27
upgrade_aquatic-1.16.5-3.1.2

(xaeros is just so i dont have to play spot the mob)
Xaeros_Minimap_22.5.0_Forge_1.16.5
XaerosWorldMap_1.20.6_Forge_1.16.5

Passive mob spawning breaks in both normal and peaceful difficulty causing mobs to not respawn 
https://github.com/JDKDigital/productive-bees/issues/258
![image](https://user-images.githubusercontent.com/85318453/165264424-bbbe49d6-c356-4bdd-a348-e9f161ea1862.png)

This issue was originally found in a larger pack narrowed down to 7 mods being the possible culprit but finally being confirmed to be Alex's mobs after testing with it disblaed only mobs are spawning fine
https://youtu.be/c57EeUgVm2M

**Comment by DoctorMage** [comment]
With alex's mobs enabled
https://youtu.be/6c0GVjC8Gcc

[debug.log](https://github.com/Alex-the-666/AlexsMobs/files/8562151/debug.log)
[latest.log](https://github.com/Alex-the-666/AlexsMobs/files/8562160/latest.log)

**Comment by PlummetStudios** [comment]
1.16.5 is no longer supported.
