### ISSUE TITLE
Crafted items are given empty nbt tags

### ISSUE THREAD

**Issue by s7092910** [Alex-the-666/AlexsMobs#1056]
All crafted items seem to be given empty nbt tags which is viewable when looking at the nbt data of the entity when the item is in the player's hand.  This causes a few issues , for example, with the vanilla recipe book not working with the items with the empty nbt tags and the items with empty nbt tags not stacking with items with no nbt tags.

Alex's Mobs Version: 1.18.0
Minecraft Version: 1.18.1 and 1.18.2

**Comment by isaaclepes** [comment]
I posted too quickly..   https://github.com/Alex-the-666/AlexsMobs/issues/1068  is also this issue

**Comment by gchpaco** [comment]
Of note, I do not experience this with 1.17.5, so it's some piece of code that landed since then.

**Comment by isaaclepes** [comment]
Versions:

Forge 40.1.0
MC 1.18.2
alexsmobs-1.18.1

**Comment by isaaclepes** [comment]
This issue was fixed in latest release 1.18.3

**Comment by s7092910** [comment]
Closing this as it has been fixed
