### ISSUE TITLE
Some receipts stop working and damage saves

### ISSUE THREAD

**Issue by uhloin** [Alex-the-666/AlexsMobs#1067]
If upgrade from 1.17.5 to 1.18.1 then some receipts stop working. If rollback to 1.17.5 they still do not work like save is corrupted. Only create new world helps.

Reproduction steps:

Install minecraft 1.18.2,
forge 40.1.0,
OptiFine_1.18.2_HD_U_H7.jar,
alexsmobs-1.18.1.jar
citadel-1.11.2-1.18.2.jar
 
Create new world (creative mode with cheats).

Get craft table, get 64 wheats,

set craft table on ground click it,

click "receipts" button,

click bread icon,

- receipt does not work, craft cells stay empty.

**Comment by isaaclepes** [comment]
This is also caused by https://github.com/Alex-the-666/AlexsMobs/issues/1056

**Comment by AlexModGuy** [comment]
fixed
