### ISSUE TITLE
alexs mobs Release 1.18.2 on 1.18.1 keeps crashing for me

### ISSUE THREAD

**Issue by justawander** [Alex-the-666/AlexsMobs#1079]
ever since i updated to the new version of the mod and try to enter the mod loader the game simply crashes

https://bytebin.lucko.me/MoKpBSX465

**Comment by brisingraerowing** [comment]
1.18.1 mods are NOT compatible with 1.18.2, and vice versa.

**Comment by justawander** [comment]
i know the version was made for 1.18.1 and i'm using 1.18.1 its just that the version name of the actual mod was called it 1.18.2. if that makes any sense

**Comment by Jaderey** [comment]
the release alexsmobs-1.18.2 says its for 1.18.1 and causes the game to crash before it even starts.

the version that is labeled alexsmobs-1.18.3 says its for 1.18.2 

edit: I suspect in my case i may have some mod that conflicts with this one. it has something to do with mixins in my case.
