### ISSUE TITLE
Mimicube causes server crashes

### ISSUE THREAD

**Issue by celsiusqc** [Alex-the-666/AlexsMobs#108]
https://pastebin.com/8NVhysBv

**Comment by Alex-the-666** [comment]
> com.flemmli97.improvedmobs.ai.ItemUseGoal

caused by mod called "improved mobs". please report this to them instead.

**Comment by GuiMora12** [comment]
I've been playing a custom modpack without improved mobs and have had the same crash. With the issue section, as reported by my server owner, being:

" at com.google.common.collect.ImmutableListMultimap.removeAll(ImmutableListMultimap.java:439) ~[guava-31.0.1-jre.jar%2328!/:?] {re:mixin,re:mixin}
    at com.google.common.collect.ImmutableListMultimap.removeAll(ImmutableListMultimap.java:51) ~[guava-31.0.1-jre.jar%2328!/:?] {re:mixin,re:mixin}
    at vazkii.psi.common.item.tool.ItemPsimetalSword.getAttributeModifiers(ItemPsimetalSword.java:78) ~[Psi+1.18.2-98.jar%23123!/:1.18.2-98]    ".
    Sorry if this is subpar formating, I am not that experienced with git's formalities. Anyhow, whenever I attempt to join the server, a crash occurs. I reason the mimicube is attempting to run the code from the sword, and something bad is going on with the slime. I will seek the PSI developers as well.
