### ISSUE TITLE
Mobs not spawning when adding to server

### ISSUE THREAD

**Issue by awbuckst11181999** [Alex-the-666/AlexsMobs#109]
Added this mod to an already running server, and so far I've yet to see a single mob. Vanilla mobs spawn fine, and I can spawn any of the modded mobs with spawn eggs. I checked in single player and they spawn fine.

**Comment by awbuckst11181999** [comment]
I did find some seals in newly generated chunks, but that is all

**Comment by Alex-the-666** [comment]
this is to be expected. Most creature spawns happen in chunk generation.
