### ISSUE TITLE
Frost Stalker/Brutal Bosses Melee AI crash

### ISSUE THREAD

**Issue by Tyrius1** [Alex-the-666/AlexsMobs#1092]
https://pastebin.com/CgbUHf5J
forge - 40.1.20
alexsmobs-1.18.3
citadel-1.11.3-1.18.2

Using the mod Brutal Bosses I made a large Frost Stalker mini boss that I call: Tyrant Stalker!
Brutal Bosses allows for adding some melee attack AI.
Towards the end of fighting it my client crashed giving the above crash report.
I'll just not use that specific mob for a boss for now but would be kool to have my boss stalker, the Tyrant Stalker back if at all possible :)
If not well thanks anyway.
![2022-05-17_00 27 09](https://user-images.githubusercontent.com/29525146/168729898-15c70e16-6f8b-4b0d-bb55-bbec5b090e58.png)
)

**Comment by L0serr** [comment]
Getting the same ticking entity crash when a Frost Stalker attacks anyone. 

https://pastebin.com/pCcjnYmH
