### ISSUE TITLE
issue when putting a boat on rainbow glass

### ISSUE THREAD

**Issue by NIGHTDRAGON1111** [Alex-the-666/AlexsMobs#1093]
when i put a boat on rainbow glass to make a rainbow road course like in mario cart it just crashed

**Comment by NIGHTDRAGON1111** [comment]
[crash-2022-05-16_23.29.38-client.txt](https://github.com/Alex-the-666/AlexsMobs/files/8705800/crash-2022-05-16_23.29.38-client.txt)
there is the crash report

**Comment by AlexModGuy** [comment]
com.mrcrayfish.framework.common.data.SyncedEntityData.hasSyncedDataKey

mrcrafish mod crash
