### ISSUE TITLE
alex mobs has conflicts with ice and fire

### ISSUE THREAD

**Issue by miguelforge** [Alex-the-666/AlexsMobs#11]
amphithere do not spawn instead many hummingbirds appear, the mob alex mobs makes the dragon fire caves less frequent and scarce in generation

**Comment by BugmanBugman** [comment]
I don't think there's a bug between them as I've seen fire caves and amph's pretty frequently

**Comment by Alex-the-666** [comment]
the caves one is definitely not true. Dragon caves are world features, AlexsMobs does not interfere or add any world features.
