### ISSUE TITLE
Leaf cutter ant crippling server performance?

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/AlexsMobs#1107]
The TPS is cut in half by alex mobs leaf cutter ant. Running Forge 40.1.19 and Alex Mobs 1.18.3 and used Spark mod to find that the cause was the alex mobs "leaf cutter ant"

![leafcutterant](https://user-images.githubusercontent.com/82549089/170371490-f7726459-d545-4def-bf5c-ec69514d61ac.PNG)

Edit: ITS A BUG! 🐜

**Comment by Brcyden** [comment]
This happened to me also. In config disable the spawning of the nests then add a repeating command block that is running the command /kill @e[type=alexsmobs:leafcutter_ant] to kill any pre existing ants.

**Comment by CvoidWyvern** [comment]
Having this happen on a 1.18.2 pack, spawns very quickly getting out of control and taking up >65% of tick time.
![image](https://user-images.githubusercontent.com/20373462/222802957-ee1a980b-bdf8-4f3d-b57e-b75088a1df3d.png)
![image](https://user-images.githubusercontent.com/20373462/222802367-b2adfd6c-1896-44f2-9b0b-a80d31882c5c.png)

**Comment by jcurtis06** [comment]
I was losing my mind trying to figure out what was causing extreme lag on my server (every 40 ticks). Found this, killed the *singular* leaf cutter ant in my house (it was a sad moment but desperate times called for desperate measures), and bam, server is instantly running better than ever.
