### ISSUE TITLE
my game crashes when opening alexmobs book 1.18.2

### ISSUE THREAD

**Issue by papillo12** [Alex-the-666/AlexsMobs#1119]
I am currently playing on a server with alexmobs, when I open the book the game crashes but the server doesn't crash, then I open the game again, enter the server and open the book and it doesn't crash anymore. But after a while if I try it again it crashes

[crash-2022-06-10_21.53.57-client.txt](https://github.com/Alex-the-666/AlexsMobs/files/8883209/crash-2022-06-10_21.53.57-client.txt)

**Comment by magsum** [comment]
exact same thing happens to me too!
