### ISSUE TITLE
Alex's mobs creative tab icon continues to cause intermittent crashes.

### ISSUE THREAD

**Issue by Warhand** [Alex-the-666/AlexsMobs#1126]
I've had this issue happen a few times before in older versions, and can't remember if I've reported it before.

Sometimes when I'm in the section of the creative menu that inclues the Alex's mobs tab, I'll get a random crash, and the crash report will point to the tab icon for Alex's mobs as being the issue.

Crashlog: https://pastebin.com/ea954kAz

Minecraft: 1.18.2
Forge: 40.1.25
Alex's mobs: 1.18.3

**Comment by AlexModGuy** [comment]
at com.mrcrayfish.framework.common.data.SyncedEntityData.hasSyncedDataKey

mr crayfish issue
