### ISSUE TITLE
Mobs despawned after world was played without mod loaded

### ISSUE THREAD

**Issue by MarrsAttax** [Alex-the-666/AlexsMobs#1129]
This may not be an issue as much as my own stupid fault.  I accidentally played my world without the mod loaded.  Once I realised I restarted the game with the mod but I had lost the kangaroos I had tamed and also the surrounding area where I was has lost all the mobs from the mod apart from the odd fly.  The mobs still spawn in other areas but I have to travel a few chunks away before encountering them.  Is there anyway of restoring the tamed mobs I lost or at least making new mobs spawn in this area? And no, stupidly I don't have a backup  :(

**Comment by DragonInsight** [comment]
It is your own fault as that happens when you load a world that uses mods without the proper mods installed.

**Comment by DragonInsight** [comment]
you'd have to spawn those mobs back in btw

**Comment by MarrsAttax** [comment]
Thought as much. Oh well - thanks for the reply :)
