### ISSUE TITLE
Suggestion : Adding vanilla mobs to the bestiary

### ISSUE THREAD

**Issue by 2Naato** [Alex-the-666/AlexsMobs#113]
I don't really like the fact that you receive a book when entering a new world. I mean it's obvious that this is a modded item or something, and I think that you get it but it's not good for immersion → it's better when you're not like "ha yes this is an item from X mod". 
So Idk if my explanation makes sense or whatever but it doesn't really matter in the end. 

I got a suggestion to make this a little better : the main problem is that it only contains your mod's mobs, so it's a little strange, considering that this is a "bestiary". Shouldn't EVERY mob be in there??
You could simply fix that by adding vanilla mobs to the bestiary. It would make sense plus it would be quite fun to have a bit of lore/tips about vanilla mobs.

The only hic would be that mobs from other mods would not be in there. 
If it turns out to be that much of a problem, maybe some mod integration could be done then?

(Oh and a config for not getting the bestiary at the start of a game would be cool too, we have JEI anyway..).

Your mod is really a blessing from the gods, thanks, really!!

**Comment by Alex-the-666** [comment]
not going to do this. we have enough language files to keep track of. besides im sure if you've figued out how to use mods/modpacks then you know what a pig or creeper is.
