### ISSUE TITLE
FroststalkerAIMelee server crash once target is dead.

### ISSUE THREAD

**Issue by Flatgub** [Alex-the-666/AlexsMobs#1146]
Minecraft Version: 1.18.2
Forge Version: 40.1.51
AlexMobs Version: 1.18.5

What happened:
Someone on my server was fighting some Froststalkers and then a few seconds after they were downed (we have PlayerRevive) the server crashed. The moment of the crash wasn't exactly when the player was "killed" but seemed to be when one of the froststalkers jumped after the combat was over?

Crashlog:
[crash-2022-06-26_10.13.50-server.txt](https://github.com/Alex-the-666/AlexsMobs/files/8985762/crash-2022-06-26_10.13.50-server.txt)

**Comment by BillHamilton-psh** [comment]
We are having the same issue with Froststalkers
[crash-2022-06-26_10.13.50-server.txt](https://github.com/Alex-the-666/AlexsMobs/files/8987427/crash-2022-06-26_10.13.50-server.txt)
.

**Comment by AlexModGuy** [comment]
fixed
