### ISSUE TITLE
Rhinos are not affected by domestication innovation enchants

### ISSUE THREAD

**Issue by JJahovah** [Alex-the-666/AlexsMobs#1163]
Trusted rhinos can be given a collar tag but they do not receive the enchant powers

https://user-images.githubusercontent.com/83381275/176915489-c9c7d44f-7524-49ce-85a4-cbd5d30dca73.mp4

https://user-images.githubusercontent.com/83381275/176915671-3db03655-de5f-4d81-a833-43d81f46136e.mp4

**Comment by AlexModGuy** [comment]
they arent tameable. they shouldn't even be able to be given a collar tag
