### ISSUE TITLE
No Text In Animal Dictionary

### ISSUE THREAD

**Issue by Karttonn** [Alex-the-666/AlexsMobs#1165]
So When I Open The Animal Dictionary Only Pictures Appear And There Isn't Any Text 
![obraz_2022-07-01_201137405](https://user-images.githubusercontent.com/108547926/176948223-9a73ef03-a3c8-4609-9e68-6514b4fc2983.png)
![image](https://user-images.githubusercontent.com/108547926/176948281-8b913760-1210-4210-82fb-e0c3f7145682.png)

**Comment by SvetlinSandev** [comment]
I experience the same issue

**Comment by DadoIrie** [comment]
by any chance using dark mod everywhere mod? [https://github.com/Buuz135/DarkModeEverywhere/issues/12](https://github.com/Buuz135/DarkModeEverywhere/issues/12)

or any mod which messes around with minecraft's native shaders?

**Comment by SvetlinSandev** [comment]
No

На пн, 25.07.2022 г., 10:47 Damir Krupic ***@***.***> написа:
