### ISSUE TITLE
[SUGGESTION] New Wilder Update mobs available in 1.18.2 when The Wild Backport is installed

### ISSUE THREAD

**Issue by Drigonis** [Alex-the-666/AlexsMobs#1170]
When https://www.curseforge.com/minecraft/mc-mods/the-wild-backport is installed, the new mobs (Potoo, Sugar Glider, Rain Frog, Rhinoceros, and Mudskipper) should spawn. They should probably be already fully-implemented in 1.18.2 despite the Wild Backport being installed or not, but mobs in the new biomes just don't spawn.

Thank you!

**Comment by PlummetStudios** [comment]
This is not a form for suggestions and this feature will not be coming to Alex's Mobs. Alex wants to avoid being locked to a previous version or supporting 2 at once. It's much too difficult
