### ISSUE TITLE
Minecraft closed with exit code: -1 (1.19)

### ISSUE THREAD

**Issue by BeastMaster6989** [Alex-the-666/AlexsMobs#1176]
I have problems running minecraft with this mod. I installed only Alex's Mobs and at startup it gives the developer console and: "**Minecraft closed with exit code: -1**". I don’t know what to do, no extraneous modifications are installed. Has a crash-reports. Crash-report attached.
[crash-2022-07-04_20.01.52-client.txt](https://github.com/Alex-the-666/AlexsMobs/files/9041180/crash-2022-07-04_20.01.52-client.txt)

**Comment by thomasstelli** [comment]
I have the same problem.

**Comment by BeastMaster6989** [comment]
> У меня такая же проблема.

I can't find solution to this problem...(
