### ISSUE TITLE
1.19 update most of my mobs arent spawning :(

### ISSUE THREAD

**Issue by Hydra106** [Alex-the-666/AlexsMobs#1178]
Some of my mods spawn but most of them don't, I'm also using Biomes O plenty, better villages, More villagers, and incendium.

**Comment by Hydra106** [comment]
Also, I'm pretty sure rhinos are spawning in place of Elephants, but I don't know. (Elephants aren't spawning)

**Comment by coolerksf** [comment]
too

**Comment by AlexModGuy** [comment]
delete the config in the alexsmobs folder
