### ISSUE TITLE
1.19 version unable to open with Alex's Mobs

### ISSUE THREAD

**Issue by PunderArmor** [Alex-the-666/AlexsMobs#1182]
Hi. Recently, I tried to play Minecraft with Alex's Mobs, along with other mods, and the game would not move to the red loading screen with the Mojang Studios logo, instead causing the game to not respond on a white screen before closing. I narrowed down the mods to this one causing problems. I am using alexsmobs-1.19.0 and 1.19-forge-41.0.63.

**Comment by MianReplicate** [comment]
I believe you might be doing something wrong or are missing something essential to this issue. I'm using the exact same mod version and forge version and it launches perfectly fine so I don't think this is a problem with the mod.

**Comment by AlexModGuy** [comment]
downgrade forge to 41.0.62 until next update
