### ISSUE TITLE
Alex's mobs doesn't load correctly in Aternos

### ISSUE THREAD

**Issue by VictorAnhui** [Alex-the-666/AlexsMobs#1186]
Alex mobs crashes with forge version 1.19 41.0.64. With version 1.19 41.0.63 it worked fine. You cannot go back to this version in aternos.

![Captura de pantalla 2022-07-08 033653](https://user-images.githubusercontent.com/108952299/178050139-da872849-a066-4826-b4e7-67e23fbd9d5f.png)

**Comment by AlexModGuy** [comment]
downgrade forge until next update
