### ISSUE TITLE
:l

### ISSUE THREAD

**Issue by Hydra106** [Alex-the-666/AlexsMobs#1190]
![image](https://user-images.githubusercontent.com/84299486/178080864-8996c9d9-c441-431d-8797-ab864dcd332f.png)
Not working

**Comment by Hydra106** [comment]
plz help

**Comment by Hydra106** [comment]
anyone know how to fix it

**Comment by DoCharlcate** [comment]
The new Forge update broke a lot of mods so you either have to wait for them to update or revert to a previous edition of Forge but you wont be able to use Alex's Mobs as it requires the new Forge.

**Comment by AlexModGuy** [comment]
^
