### ISSUE TITLE
Crash with Lucky TNT Mod (TooMuchTNT) 1.16.5

### ISSUE THREAD

**Issue by kylepitcock** [Alex-the-666/AlexsMobs#1196]
These two mods on 1.16.5 seem to crash with each other.  It crashes as soon as it hits "Found 65 modfiles to load" in the initialization process.  The game crashes with an exit code 1 with the reason in a screenshot below.  When one of these mods is not installed, the game loads fine.  The game doesn't seem to create a crash file, so I will send the latest.log.  I will also attach full modlist
[latest.log](https://github.com/Alex-the-666/AlexsMobs/files/9085237/latest.log)
![image](https://user-images.githubusercontent.com/40410003/178297560-0c6d0f93-ccf1-4cdc-a374-593071e0dd6c.png)
![image](https://user-images.githubusercontent.com/40410003/178297753-bbcac792-aa7a-4786-838e-b15ddde28b5a.png)

**Comment by AlexModGuy** [comment]
1.16.5 no longer supported
