### ISSUE TITLE
Skelewags feel unbalanced

### ISSUE THREAD

**Issue by IdrisQe** [Alex-the-666/AlexsMobs#1200]
I like the idea of an undead fish but these things are WAY unbalanced- not only spawning in the day seemingly near the surface, but they also spawn in packs of 2 or more from what I can tell, and are able to outspeed a boat moving away from them at full speed, making them impossible to avoid if you happen to run into them, nevermind that a single hit from one seems to deal something like 4 hearts of damage. I feel they could definitely be done better:

1. Make them only spawn at night, and despawn during the day: Yes they're underwater mobs but unlike drowned which are fairly simple to deal with, these things spawn close to the surface and are extremely powerful.
2. Make their speed, or charge attack, or whatever it is they do, have a cooldown, and decrease the damage a bit. I get that boating without armour is a bad idea but there are a lot of cases where you spawn pretty much surrounded by ocean. Trying to cross a body of water and running into even one or two of these is a death sentence given they seem to be able to move faster than a boat even.

I'm unsure how many were chasing me, between 1 and 2 given how many I saw before fleeing, but every second or so they would catch up and hit me again even though I was fleeing on a boat, and even just 3 hits was enough to completely kill me. I could have just been combo'd by a pack of them but if so they should spawn rarer and only in packs of 1.
Given how fast they are, in their current state, even with armour and staying to fight I probably would have stood no chance, and they would have just kept catching up and hitting me trying to flee, so... yeah.

_Edit: So by default they aren't supposed to spawn anywhere but shipwrecks? That's really weird since the ones I saw were close to shore at the surface of the water and I didn't see any shipwreck nearby or under them. I wonder if some other mod I have breaks their spawning... Because it's more fair for them to be guarding those than just spawning randomly. Though I'm not sure how you're supposed to fight them with how fast they are._

**Comment by MarioSMB** [comment]
Just like to add that I've encountered the same issue, it does not appear to be resolved (at least, not in 1.18.2 releases of the mod).
