### ISSUE TITLE
Some Mob's Refuse To Spawn

### ISSUE THREAD

**Issue by themadcowboy** [Alex-the-666/AlexsMobs#1201]
I've been trying to do a survival world for this mod, but for some reason mobs are refusing to spawn naturally. These are new worlds that have not been played on before, nor do i have any other biome mods or anything of the sort. 

The only mobs i have seen are the newer mobs that were recently added. but anything before that just basically doesn't spawn naturally. 

Does anyone know how to fix this issue? i would greatly appreciate it.

**Comment by Hydra106** [comment]
delete the config

then reopen forge it worked for me :)

**Comment by Hydra106** [comment]
![image](https://user-images.githubusercontent.com/84299486/179379351-bff0f682-d645-48db-a936-5cfe0233a166.png)
