### ISSUE TITLE
Spawn problem

### ISSUE THREAD

**Issue by Pabloxeg** [Alex-the-666/AlexsMobs#1202]
I have a 1.19 world with some mods like byg and bop, exploring a lot i only found 2 mobs.
I made an other world but in creative, and a saw only one mob more and i explore over 10 diferent biomes .
Im not sure if it's normal or if it's a problem.
What can i do to solve it?

**Comment by themadcowboy** [comment]
I have been basically having the same problem, for some reason the mobs wont spawn.

**Comment by R3N50** [comment]
I'm having the same issue in a 1.19 world. I've only seen 2 animals so far

**Comment by Hydra106** [comment]
delete the config

then reopen forge it worked for me :)

**Comment by Hydra106** [comment]
![image](https://user-images.githubusercontent.com/84299486/179379353-2422d545-0f3b-49fb-a9f6-492e38aebbe7.png)
