### ISSUE TITLE
Some mobs are unable to spawn naturally

### ISSUE THREAD

**Issue by CoolKarlkat** [Alex-the-666/AlexsMobs#1207]
No matter how much I crank up the spawning in the config, some mobs just do not spawn naturally at all. I have seen this happen with Mantis Shrimp, Blobfish, Soul Vultures, and Rocky Rollers. There are probably a couple others that I am forgetting. Strangely, this issue seems to be solved with the Terralith mod installed. But I don't want to play with that mod. I am using version 1.18.6 on Forge version 40.1.21.

**Comment by Hydra106** [comment]
delete the config

then reopen forge
