### ISSUE TITLE
Add support for vanilla mobs and Quark mobs

### ISSUE THREAD

**Issue by FrannDzs** [Alex-the-666/AlexsMobs#121]
Hello! Good afternoon, I would like you to add compatibility with other vanilla mobs such as rabbits and Quark mobs since when installing Alex Mobs mobs start to disappear, even the Guard Villagers guards disappear: or, maybe I could inject code instead of replacing it Maybe you could use Quark's mob system which is not intrusive, I hope it can remedy these problems, it's a great complement, congratulations, and best regards

**Comment by Yourname942** [comment]
Are you referring to hostile mobs eventually stop spawning in the world? (that is happening to me)

**Comment by FrannDzs** [comment]
Hello, I mean non-hostile mobs, I have not tried hostile mobs yet but according to what you count it is widespread. I can't see the Quark frogs and I can't see vanilla rabbits. That happens :(

**Comment by FrannDzs** [comment]
> Are you referring to hostile mobs eventually stop spawning in the world? (that is happening to me) If not, then sorry to intrude on your issue.

Hello, I mean non-hostile mobs, I have not tried hostile mobs yet but according to what you count it is widespread. I can't see the Quark frogs and I can't see vanilla rabbits. That happens :(

**Comment by BugmanBugman** [comment]
This isn’t compatibility. It’s just well known that the more mob spawns you have, the less the rare mobs will spawn.

i have never heard of a quark mob system
