### ISSUE TITLE
Ticking entity crash

### ISSUE THREAD

**Issue by Gavin456b** [Alex-the-666/AlexsMobs#1213]
Not sure if this is caused by Alex's mobs but the entity causing the crash is a terrapin.
[crash-2022-07-16_14.51.42-server.txt](https://github.com/Alex-the-666/AlexsMobs/files/9126515/crash-2022-07-16_14.51.42-server.txt)

**Comment by AlexModGuy** [comment]
> at vazkii.quark.content.automation.module.FeedingTroughModule.temptWithTroughs

**Comment by Gavin456b** [comment]
Any way to circumvent this issue with Quark or is it something I should report to their issue tracker?

**Comment by erictpappis** [comment]
how to solve this problem? i have the same problem

**Comment by Gavin456b** [comment]
> how to solve this problem? i have the same problem

It was an issue with Quark's feeding trough. Disable it

**Comment by NovaProYT** [comment]
> > ¿Cómo resolver este problema? Tengo el mismo problema
> 
> Fue un problema con el comedero de Quark. Desactívelo

how can i disable it??
