### ISSUE TITLE
Lava like Water With any version of SEUS shaders

### ISSUE THREAD

**Issue by Kyrenncraft** [Alex-the-666/AlexsMobs#1232]
Installing the mod with SEUS shaders on makes the lava transparent, IT seems something related with lavavision that is working without drinking the potion, 

This is happening to me with any version of SEUS Shaders and with alexmobs-1.18.6, if I remove the mod, lava turns totally normal.

Thnak you

**Comment by TheHitman2772** [comment]
I'm also experiencing this, on 1.18.2, lava turns to water. Only with SEUS, any settings, and only with alex's mobs 1.18.6 + citadel 1.11.3. I'm assuming it's citadel as Alex's Mob's files don't seem to have anything to do with lava.

**Comment by rampagerock** [comment]
Is there a possibility of pushing this fix to 1.18.2? Many modpacks still run on that, and use AlexMobs
(Which is where I have this same issue, but fix is only on 1.19)
Thanks for the fix anyhow
