### ISSUE TITLE
[1.18.2] Cachalot whale AI causing tic lag

### ISSUE THREAD

**Issue by MarioSMB** [Alex-the-666/AlexsMobs#1233]
Running a Spark profile for lagging tics on my server, I've found that the function `net.minecraft.world.level.pathfinder.SwimNodeEvaluator.getBlockPathType()` from the cachalot whale AI is taking up a majority of processing time.  
We have a house near the ocean and there are frequently up to 4 whales nearby, here's the profiler log: https://spark.lucko.me/wn9EIfr8IZ

**Comment by zenril** [comment]
How many ticks behind is your server most of the time?
Mine tends to be 40 - 70 ticks behind, I wonder if its this.


Edit: ahh I see your profiler says ticks >= 150
Might have to setup something like this myself, the mod breakdown is cool.
