### ISSUE TITLE
idk what to do im geting this message mod alexsmobs 1.19.5 jar needs langauge provider javafml 42 or above to load

### ISSUE THREAD

**Issue by jackowacko14** [Alex-the-666/AlexsMobs#1243]
help how do i fix this

**Comment by kuukrii** [comment]
most likely using a version of the mod thats ABOVE the version of your game- ie, 1.19 mod running on a 1.18 client

**Comment by alixydnochu** [comment]
i have the same problem and i checked evertyhing and its the same version 1.19
