### ISSUE TITLE
Can't re-access a world

### ISSUE THREAD

**Issue by annam12345** [Alex-the-666/AlexsMobs#1244]
I made a post yesterday asking for help with my game crashing but I thought I had figured it out. I decided to just start a new world and using world edit I copied my previous builds into the new world. It was annoying but I was happy I could continue building my zoo. It was working great until I had to shut down the game. It saved and everything looked fine but when I tired to go back into the world, it crashed. It seems like the mod (it could be citadel but I know its definitely one of these mods) is corrupting the world or stopping the world from loading. I'm clearly not smart enough to fix this on my own so I definitely need help.

This is the crash report [https://pastebin.com/S8sM8Bj2](url)

**Comment by AlexModGuy** [comment]
disable skipWarnings in citadel config
