### ISSUE TITLE
Crash Report Mimicube tick

### ISSUE THREAD

**Issue by titorito11** [Alex-the-666/AlexsMobs#1260]
Having issues with sever crashing due to mimicube. Assuming the mimic can't mimic modded weapons. If you can send me directions on how to recover my sever that would be greatly appreciated.
[crash-2022-08-04_21.09.26-server.txt](https://github.com/Alex-the-666/AlexsMobs/files/9265201/crash-2022-08-04_21.09.26-server.txt)

**Comment by AlexModGuy** [comment]
bug is from psimetal
