### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by Niik1802** [Alex-the-666/AlexsMobs#1266]
Hi Alex. I encountered this problem when trying to start a server, it crashes because of:

Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.SimpleContainer.m_7983_()" because "this.catfishInventory" is null

Minecraft 1.18.2
mohist-1.18.2-88-server.jar
Forge: 40.1.68

I leave the crash report here

[crash-2022-08-06_01.54.53-server.txt](https://github.com/Alex-the-666/AlexsMobs/files/9279746/crash-2022-08-06_01.54.53-server.txt)

**Comment by mraxg** [comment]
The same thing happens to me and I don't know how to solve it
