### ISSUE TITLE
Transparent Lava Issue

### ISSUE THREAD

**Issue by JuanTaco666** [Alex-the-666/AlexsMobs#1269]
![Desktop Screenshot 2022 08 08 - 23 16 48 61](https://user-images.githubusercontent.com/39626287/183679363-5d571adf-2574-4f88-b7fc-2042c178f638.png)
![Desktop Screenshot 2022 08 08 - 23 16 59 39](https://user-images.githubusercontent.com/39626287/183679407-bcef8add-40ae-4df8-bce8-2bed1546dc42.png)

I have rubidium and oculus installed on Forge 1.18.2, (not optifine) and the lava looks like this when using certain shaders, specifically Seus PTGI and Seus Renewed, all other shaders I tried seem to work. I have enabled the option in Alex's mobs config that is supposed to fix this issue, but it has no effect. Could this be looked into?

**Comment by Mad-Kitsune** [comment]
Commenting to confirm that I have the same issue, Minecraft Forge 1.18.2 with Rubidium and Oculus with Seus Renewed Shaders, have also tried the config option that is meant to help with this issue

**Comment by AlexModGuy** [comment]
dupe
