### ISSUE TITLE
Mobs will not appear in 1.19.1

### ISSUE THREAD

**Issue by TheFakeADI** [Alex-the-666/AlexsMobs#1280]
I will create a new world and none of the alexs mobs mobs will appear except for the ones which were added in the 1.19 update. I tried looking for the Devil's hole pupfish, but when I got to the chunk, they weren't even there. I don't know what's going on but no matter what I try I can't get mobs to spawn without using commands or a spawn egg. Basically nothing except the Rhino, Potoo, Sugar Glider and Rain Frog is spawning naturally in their biomes. Not even the mudskipper which I know was added in the 1.19 update.

**Comment by AlexModGuy** [comment]
delete your config file
