### ISSUE TITLE
Minecraft keeps crashing when I try to create a world

### ISSUE THREAD

**Issue by UnN00b233** [Alex-the-666/AlexsMobs#1283]
[crash-2022-01-04_11.48.55-fml.txt](https://github.com/Alex-the-666/AlexsMobs/files/9366477/crash-2022-01-04_11.48.55-fml.txt)

**Comment by UnN00b233** [comment]
Please help

**Comment by mraxg** [comment]
It seems that you have not installed the citadel dependency, try to install it and see if it works
