### ISSUE TITLE
Only rhinos spawning in savannas (Alex's mobs)

### ISSUE THREAD

**Issue by PlaqueDoctor** [Alex-the-666/AlexsMobs#1288]
Only Rhinoceroses are spawning in savannas, no emus no kangaroos no gazelles and no manes wolves.

**Comment by solal3005** [comment]
> Only Rhinoceroses are spawning in savannas, no emus no kangaroos no gazelles and no manes wolves.

Yes almost no mobs spawn in 1.19 and 1.19.2 , exept rhinos, hummingbirds and cachalot whale

**Comment by AlexModGuy** [comment]
delete old configs
