### ISSUE TITLE
Alex's Mobs makes all generation mods crash

### ISSUE THREAD

**Issue by Matthysse** [Alex-the-666/AlexsMobs#1292]
Hello!

Here is a weird problem I have with Alex's Mobs (not Citadel, tested with it), on MC 1.19.2, forge 43.1.2, adding the Alex's Mobs mod to the game makes all the mods that add generation stuff crash (when creating a new world), here is an example:

This time it crashes with BOP: https://pastebin.com/ZdED3Je0
This time with supplementaries: https://pastebin.com/jDFMrzB8
This time with  Twilight Forest: https://pastebin.com/pbRQwWhm

Removing the mod resolves the problem.

**Comment by NcSc11** [comment]
Hello, I have the same problem, do you have any solution?
