### ISSUE TITLE
Crashes when re-opening a world

### ISSUE THREAD

**Issue by PiGuy314159** [Alex-the-666/AlexsMobs#1312]
When trying to open a world that has been already created, the games crashes. I am on Minecraft Java Edition 1.19.2, Forge 43.1.1, Alex's Mobs 1.19.5, and Citadel 1.12.7-1.19 with no other mods. I have tested it many times. Nothing stops the crash, not even world backups. The game is virtually unplayable with this issue. The crash report is attached below. (Note: the screenshots repeat some areas to ensure everything is documented. Apparent repetitions of the crash report are due to that; they are not actually repeated.)
<img width="1440" alt="Screen Shot 2022-09-02 at 12 21 49 PM" src="https://user-images.githubusercontent.com/112724130/188215558-d0fc6bac-55b6-4102-9d60-a4184c33bf8d.png">
<img width="1440" alt="Screen Shot 2022-09-02 at 12 22 13 PM" src="https://user-images.githubusercontent.com/112724130/188215563-d67b5e63-934c-4f32-bfac-d38ccbade661.png">
<img width="1440" alt="Screen Shot 2022-09-02 at 12 22 16 PM" src="https://user-images.githubusercontent.com/112724130/188215570-db2b5ee0-8738-41c4-9fea-d29addcfbf09.png">
<img width="1440" alt="Screen Shot 2022-09-02 at 12 22 25 PM" src="https://user-images.githubusercontent.com/112724130/188215576-a176a91f-cd8e-4188-bf70-1ddde2583f6d.png">
<img width="1440" alt="Screen Shot 2022-09-02 at 12 22 43 PM" src="https://user-images.githubusercontent.com/112724130/188215584-4763b84e-f675-40b9-ac85-bdb516c0517f.png">
<img width="1440" alt="Screen Shot 2022-09-02 at 12 22 53 PM" src="https://user-images.githubusercontent.com/112724130/188215585-8a551acb-d649-4e5d-ab8d-870513f6ad71.png">

**Comment by AlexModGuy** [comment]
disable skipWarnings in citadel config
