### ISSUE TITLE
Mobs from AlexMobs keep crashing my server

### ISSUE THREAD

**Issue by Zelioth** [Alex-the-666/AlexsMobs#1317]
[crash-2022-09-04_21.16.09-server.txt](https://github.com/AlexModGuy/AlexsMobs/files/9485536/crash-2022-09-04_21.16.09-server.txt)

as far as i can tell its mobs from alex mobs causing it but i could be wrong
Minecraft 1.19.5
Forge 43.1.5
Latest versions of mod

**Comment by AlexModGuy** [comment]
> com.github.dragoni7.dreamland.core.event.DreamlandEventHandler.updateTarredEffect

Something called dreamland is causing the crash
