### ISSUE TITLE
Alexs Mobs not spawning after adding mod to pre existing world.

### ISSUE THREAD

**Issue by snepsnorp** [Alex-the-666/AlexsMobs#1339]
After adding this mod to an already established world, I have found that there is only a few of the newer animals from the most recent update spawning. When I use this mod on other worlds, all animals spawn fine. Why is this?

**Comment by AlexModGuy** [comment]
animals only spawn on chunk generation; or rarely when chunks have been fully depopulated of animals. There are a few respawnable animal mods out there that may help you out.
