### ISSUE TITLE
Crash upon opening. using curseforge launcher.

### ISSUE THREAD

**Issue by Fingernailsss** [Alex-the-666/AlexsMobs#1368]
![Screenshot 2022-10-01 193504](https://user-images.githubusercontent.com/107367170/193431966-c73441e7-384e-4579-a177-93dcfa8c2087.png)

forge 41.1.0

alex's mobs 1.20.1

**Comment by AlexModGuy** [comment]
using the wrong version of forge

**Comment by Fingernailsss** [comment]
41.1.0 is the highest possible ver.

**Comment by Fingernailsss** [comment]
that is the maximum
