### ISSUE TITLE
Hummingbird Rendering Crash

### ISSUE THREAD

**Issue by FevilGitHub** [Alex-the-666/AlexsMobs#1374]
Hey! i reported this to the Better MC Github but they stated for me to go to this one, so imma copy paste what i said there.

"Hey i was randomly playing on my world when my game suddenly crashed, but didnt display the usual minecraft launcher you usually use before booting up Better MC after the crash. A log was created upon further examination and from what i could tell on there, it seemed that a Hummingbird had failed to render and caused the entire world to crash. This could potentially be a problem later down the line. Upon further examination this is caused by literally any hummingbird. This is going to be an issue going forward for those who enjoy the effects of hummingbirds like me :c"

Someone stated that this was bc the mob is apparently trying to load in a Curios item.

Crash Report - https://pastebin.com/kx0cYazF
Initial Report (Closed) - https://github.com/LunaPixelStudios/Better-MC/issues/778

**Comment by AlexModGuy** [comment]
twighlight forest bug
