### ISSUE TITLE
drop bears spawning in overworld

### ISSUE THREAD

**Issue by HelloChronicles** [Alex-the-666/AlexsMobs#1375]
Hello, I recently tried making a mob farm in the overworld, but when I was finished with it and went up the hundred or so blocks into the sky to go afk, I noticed red things falling from the sky and didn't learn what it was until after going afk for a bit and coming back down, which is when I noticed drop bears around the farm. I tested it a few more times and they keep appearing in the sky and falling to the ground and are also spawning inside the structure, hijacking the spawn rates since they attach to the ceilings of each spawn floor and dont get pushed into the campfires by the water dispensers.

I tried turning the spawns for the drop bears off in the configs, but only the nether wastes and crystalline chasm were listed as the biomes, obviously, since they aren't supposed to be spawning in the over world at all. I still turned the spawns off and it unsurprisingly didn't work. Another thing I remember was that they seemed to spawn whenever I traveled to new places and it was taking a while for new chunks to load in, again, this is in the overworld. I had the same problem with drop bears with my gold farm, but since the config for turning off their spawns in the nether wastes existed, I was able to fix it, but I have no idea what to do about them spawning in the overworld.

I'm totally open to somehow deleting the mob from the files altogether, if that's the only option and if that's doable, but I don't know how I'd be able to do that. Thanks ahead of time for any help on the issue.

**Comment by HelloChronicles** [comment]
Okay, just a quick update, I'm not completely sure if the drop bears are spawning inside the spawning structure. I just heard their growls and when I look around and under the structure, I don't see any of them but when I broke the walls and looked inside I still didnt see any, though I still heard their growls. It could be that it was just too dark to see them, but they are definitely still falling from the sky whenever I go up to the afk platform.

**Comment by HelloChronicles** [comment]
another update: there are now drop bears in the end

**Comment by RuseTiger** [comment]
Can you copy the biome tags from other mobs that are supposed to spawn in those regions (I would assume the drop bear somehow stole the bat tags) and then set them to not spawn in those biomes? Also when you changed the nether tags did it fully stop them from spawning in the nether or did it cause them to spawn everywhere at all times?

**Comment by HelloChronicles** [comment]
it looks like turning their spawns on again fixed the problem, but what should I be doing when I need their spawns off in the nether wastes for my gold farm? the gold farm has to be in the nether wastes and it doesnt work if the drop bears are hijacking the spawn rates. this wasn't a problem on the previous 1.18 server I had, where I could turn off their spawns and they wouldn't be spawning in places they shouldn't be, so I don't know what changed
