### ISSUE TITLE
1.19 - 1.19.2 Made for older version of minecraft

### ISSUE THREAD

**Issue by Hvottt** [Alex-the-666/AlexsMobs#1402]
Whenever I make a world, in the modpacks it says the mod is incompatible because it was made for an older version of minecraft. When I get into the game, the advancement for opening the journal is glitchy, and the only mobs I have noticed that spawn is the bison and the rhino. I seriously have no idea what is happening, I have tried getting older versions of the mod, older versions of forge, but nothing will work. It just keeps saying that it is made for an older version of minecraft. It also warns me about using experimental settings.

I am using the latest version of forge, and the latest version of both citadel and alex's mobs. I also have optifine.

**Comment by davidromrell** [comment]
Same issue
