### ISSUE TITLE
Alexes Mobs not spawning in my server

### ISSUE THREAD

**Issue by NoobyK** [Alex-the-666/AlexsMobs#1408]
I have made a server using Minehut. I have downloaded the 1.19 versions for both Alexes mobs and citadel on my server, and no Alexes mobs are spawning, however, all the Alexes mobs' items are there, and the new spawn eggs are there (which aren't functional) Any fixes?

**Comment by NoobyK** [comment]
If i try to summon a alexes mob mob using /summon, it says unkown entity.

**Comment by Rzeky21** [comment]
i have the same Problem
