### ISSUE TITLE
Mimicube doesn't spawn on player-placed blocks

### ISSUE THREAD

**Issue by bambambeans** [Alex-the-666/AlexsMobs#141]

**Comment by bambambeans** [comment]
The mimicube is only spawning on the tiny 1x1 purpur blocks in the end city and not on my massive purpur platform just above the end city

**Comment by BrisingrAerowing** [comment]
Your platform may be just out of range of the end cities' bounding box. IIRC, each part of the city has its own bounding box, so removing a section and building a platform (or multiple) in its place may work.
