### ISSUE TITLE
90 % of mobs don't spawn in 1.19.2

### ISSUE THREAD

**Issue by lynariel** [Alex-the-666/AlexsMobs#1414]
Since few patches I noticed some mobs don't spawn. After hours to explore worlds in creative mode, I saw only few like whales, skelewags, giant squids and comb jelly in ocean biome. On the lands I met just gelada monkeys, bisons, flutters and the new mobs of the 1.21.0. In the nether I could see just stradders, souls vultures and a lot of crimson mosquitoes !

I tested the mod in several configurations : 
- With all my mods, like terralith, create..... and recommanded Forge version
- With only Alex's mobs, Citadel,Optifine and recommanded Forge version
- just Alex's mobs, Citadel and recommanded Forge version
- with the last version of Forge

in all those cases I have this issue.

**Comment by SodiumZH** [comment]
Have you deleted the old config files of AM? I encountered this issue when updated 1.18.2 to 1.19.2, and after deleting the old config files, the new ones were automatically generated and everything went right.

**Comment by SodiumZH** [comment]
Actually it was mentioned at the update log on CurseForge...

**Comment by lynariel** [comment]
Oh ! It works ! Thanks !

**Comment by Brodend1** [comment]
> Have you deleted the old config files of AM? I encountered this issue when updated 1.18.2 to 1.19.2, and after deleting the old config files, the new ones were automatically generated and everything went right.

Where can I find these config files?

**Comment by SodiumZH** [comment]
> > Have you deleted the old config files of AM? I encountered this issue when updated 1.18.2 to 1.19.2, and after deleting the old config files, the new ones were automatically generated and everything went right.
> 
> Where can I find these config files?

/.minecraft/config/alexsmobs.toml
