### ISSUE TITLE
Gay Juice (Rainbow Jelly) doesn't affect mobs from other mods + the easter eggs don't work (1.19.2)

### ISSUE THREAD

**Issue by Shroomy281** [Alex-the-666/AlexsMobs#1419]
Fairly clear, the rainbow jelly can be tested against most other mobs from other mods (I tried ecologics, the biome-thematic creeper joosh mod), a nd then the renaming to "trans" or "weezer" didn't change the overlay.

**Comment by ScoutTheSaneless** [comment]
can confirm this issue
