### ISSUE TITLE
Mob Suggestion: Unsettler

### ISSUE THREAD

**Issue by kihgy** [Alex-the-666/AlexsMobs#142]
The Unsettler is a passive creepy fantasy mob, it spawns underground at low levels with a low spawn rate. It have the appearance similar to a player, its skin is black. It have 1 hp, but cannot be killed, but vanish instead, everytime it is damaged, it disappear. Unsettler wander slowly where it spawned, when it detect it is being stared at, it will also vanish, but without applying 10 secs of Blindness onto the looker, the two vanish and debuff actions take place at the same time. When it vanishes, it will also leave the player a gift, which can vary from a dead bush, dirt up to a diamond. The unsettler doesnt make any sound at all.

**Comment by Alex-the-666** [comment]
this is for bugs keep suggestions to discord
