### ISSUE TITLE
Game Crash during Item Rendering

### ISSUE THREAD

**Issue by MeeMik0ik0** [Alex-the-666/AlexsMobs#1425]
Recently updated Alex's Mobs to the Forest Friends for Aternos update, game closes and gives the following message

```
The game crashed whilst rendering item 
Error: java lang.NullPointerException: Registry Object nkt present: alexsmobs:stink_ray

Exit Code: -1
```

**Comment by MeeMik0ik0** [comment]
[crash-2022-11-08_20.58.18-client.txt](https://github.com/AlexModGuy/AlexsMobs/files/9961417/crash-2022-11-08_20.58.18-client.txt)
Crash Log here

**Comment by AlexModGuy** [comment]
client was outdated
