### ISSUE TITLE
Flies keep dying when on the moon with Ad Astra

### ISSUE THREAD

**Issue by Antop90fr1** [Alex-the-666/AlexsMobs#1442]
It's on the title. I'm using the latest version of ad astra in 1.19.2 with forge.
The flies drop a large amount of maggots when on the moon (I haven't tested on other planets) generate a large amount of smoke when dying.
![image](https://user-images.githubusercontent.com/118689992/202923141-dd8496f4-cb0a-4848-9e4a-0e51c2f6f907.png)
![image](https://user-images.githubusercontent.com/118689992/202923155-be1ece6b-b201-4c38-b5dc-ef0c458bf8a1.png)
![image](https://user-images.githubusercontent.com/118689992/202923159-6908fb8b-ff2a-48c8-95a6-2de50a423896.png)

**Comment by s19439-AW** [comment]
I have the same problem with Beyond Earth! ( similiar mod  or even exactly like Ad Astra )
I tried use fly_spawns.json to disable fly spawn at moon 

```
{
  "biomes": [
    [
      {
        "type": "BIOME_TAG",
        "negate": true,
        "value": "minecraft:is_end"
      },
      {
        "type": "BIOME_TAG",
        "negate": true,
        "value": "minecraft:is_nether"
      },
      {
        "type": "BIOME_TAG",
        "negate": true,
        "value": "minecraft:is_ocean"
      },
      {
        "type": "REGISTRY_NAME",
        "negate": true,
        "value": "beyond_earth:moon_desert"     <------    
      },
```

But no matter which combination with negate, biome tag etc i used - fly keep spawning!
Pls fix that!

**Comment by cubicbyte** [comment]
@RejectFrontendEmbraceBackend I did the same as you, and flies really stopped spawning on the moon. It looks like you are changing the wrong config
