### ISSUE TITLE
[1.19.2] Flies spawn on Ad Astra's Moon

### ISSUE THREAD

**Issue by rafaelkai** [Alex-the-666/AlexsMobs#1445]
The mod author stated that it is an Alex's Mobs problem.
https://github.com/terrarium-earth/Ad-Astra/issues/50

**Comment by s19439-AW** [comment]
I have the same problem with Beyond Earth! ( similiar mod  or even exactly like Ad Astra )
I tried use fly_spawns.json to disable fly spawn at moon 

```
{
  "biomes": [
    [
      {
        "type": "BIOME_TAG",
        "negate": true,
        "value": "minecraft:is_end"
      },
      {
        "type": "BIOME_TAG",
        "negate": true,
        "value": "minecraft:is_nether"
      },
      {
        "type": "BIOME_TAG",
        "negate": true,
        "value": "minecraft:is_ocean"
      },
      {
        "type": "REGISTRY_NAME",
        "negate": true,
        "value": "beyond_earth:moon_desert"     <------    
      },
```

But no matter which combination with negate, biome tag etc i used - fly keep spawning!
Pls fix that!

**Comment by SooshiGuy** [comment]
I think this is caused by Flies being an ambient mob.

**Comment by noahcroghan** [comment]
It seems using "BIOME_TAG" "ad_astra:has_structure/lunarian_village_biomes" or "ad_astra:has_structure/moon_dungeon_biomes" in the fly_spawns.json config fixes this!
