### ISSUE TITLE
Mob Spawns

### ISSUE THREAD

**Issue by TyrionTargarian** [Alex-the-666/AlexsMobs#1460]
Ive a few other animal mods (naturalist Aquaculture 2 goodall yungs red panda) and even without them the mobs hardly ever spawn even after like 20 mins flying in creative only saw some bison and about 50 blue jays any way to turn up spawns without manually doing each mob thanks (On aternos BTW)

**Comment by AlexModGuy** [comment]
delete your spawn configs
