### ISSUE TITLE
[1.19.2] [Server Performance] Leafcutter Ant Queen causes huge lag spikes when attempting to locate nearest free nest block

### ISSUE THREAD

**Issue by LoftyLoftyLoftyLoftyLofty** [Alex-the-666/AlexsMobs#1472]
Leafcutter Ant Queen causes huge dips in server performance when relocated far away from a nest block.
During testing we had one queen navigate over 1000 blocks in a straight line, causing constant server hiccups all the way home.

**Comment by LoftyLoftyLoftyLoftyLofty** [comment]
Regular leafcutter ants have similar performance hits if relocated.

**Comment by MoonstruckSpirit** [comment]
This also occurs on 1.19.3
