### ISSUE TITLE
Performance problem and corrupted saves

### ISSUE THREAD

**Issue by uhloin** [Alex-the-666/AlexsMobs#1475]
Minecraft 1.19.2
forge-1.19.2-43.2.0-installer.jar
citadel-2.1.1-1.19.jar
alexsmobs-1.21.1.jar

I did not checked for 19.3 but probably bug is older than 1.21.1

Steps to reproduce
Install clean version of 1.19.2 or clear mods/resourcepacks/shaderpacks/config folders.
Install Forge 1.19.2-43.2.0
Copy Alexmobs and Citadel jars to mod folder.
Launch game.
Create a new world in Hardcode mode.
Quit to title screen with save.
Enter to the same world again. There warning message may be shown but problem is not the message.
Quit to title screen with save.
Enter to the same world again.  This time there should not be warnings.
Quit to title screen with save.

Check level.dat file in saved world with any tool which can show NBT-file content (for example NBTExplorer).
Under "surface_rule" branch you can see repeating nesting nodes (see attachment).
The nesting of these nodes increases every save.
The deeper recursion the more degradation of chunk generation speed.
After nesting level achieves 512 the world stops loading and may be lost forever if user is not familiar with tools like NBTExplorer.

I checked and reproduce this bug with only Forge, Alex's mobs and Citadel. But originally I lost my very old (512 saves) world with bigger mod pack (73 mods). This pack includes mods like Biomes of Plenty and Biomes You'll go which probably do something with "surface_rule" branch. In this case the tree under "surface_rule" branch looks different but result is similar. First branch grows deeper and deeper with every save and after some time world stops loading.

**Comment by uhloin** [comment]
Screenshot
![recursion](https://user-images.githubusercontent.com/96169906/208303376-c9a91fe0-29c7-4813-8c40-a271091912c6.png)

**Comment by aAndrew3030** [comment]
I am having this same problem, seems to be a issue between Citadel and Terrablender
https://github.com/Glitchfiend/TerraBlender/issues/107

**Comment by uhloin** [comment]
> I am having this same problem, seems to be a issue between Citadel and Terrablender [Glitchfiend/TerraBlender#107](https://github.com/Glitchfiend/TerraBlender/issues/107)

I reproduced it without terrablender, only with alex's mobs and citadel. So terrablender' data is just involved to bug.

I forced to periodically fix my world save or else terrain generation becomes very slow. 

1. I created brand new world with name like "NewNew"
2. Open saves in NBT Explorer, expand NewNew/level.dat/Data/WorldGenSettings/dimensions.
3. Click "dimensions", use menu Edit/Copy
4. Expand OldWorld/level.dat/Data/WorldGenSettings
5. Click "dimensions", use menu Edit/Delete
6. Click "WorldGenSettings", use menu "Edit/Paste
7. Save file

**Comment by aAndrew3030** [comment]
Yes, I have to manually fix the world after several saves. I am thinking a temp workaround (while we wait for a fix) might be to pre-gen chunks and fix the nesting as needed. I really don't want to delete my Alex mob zoo!

**Comment by KostromDan** [comment]
@aAndrew3030 @uhloin Any automatic solution after so much time?

**Comment by uhloin** [comment]
@KostromDan I still use NBTExplorer

**Comment by KostromDan** [comment]
Test 1:
mods:
	TerraBlender, Citadel
protocol:
	create world and reopen in 5 times, look with NBTExplorer.exe at the nesting of surface_rule.
result:
	no bug

Test 2:
mods:
	TerraBlender, Citadel, BOP
protocol:
	same as 1 test
result:
	BUG

Test 3:
mods:
	TerraBlender, BOP
protocol:
	same as 1 test
result:
	no bug

Test 4:
mods:
	TerraBlender, BOP
protocol:
	Create world with TerraBlender, Citadel, BOP (without reopening). Close minecraft. Disable Citadel. Run Minecraft. Reopen this world 5 times.
result:
	BUG (Nesting continues to increase despite the absence of Citadel.)

Test 5:
mods:
	TerraBlender
protocol:
	Create world with TerraBlender, Citadel, BOP (without reopening). Close minecraft. Disable Citadel, BOP. Run Minecraft. Reopen this world 5 times.
result:
	BUG (Nesting continues to increase despite the absence of Citadel, BOP)

Verdict: Citadel does something with level.dat, as a result of which TerraBlender starts to work incorrectly and each save increases the nesting of suface_rules.
Also see our discussion in discord with TerraBlender dev. From this msg:
https://discord.com/channels/138056667865546752/927537933718802482/1112006439704207470
He's verdict:
I do understand. Citadel ruins level.dat, then TerraBlender perpetuates the issue
Anything I could theoretically do on my end won't actually fix any underlying problem
The state will still be wrong

**Comment by KostromDan** [comment]
Tested on 1.19.4 problem is actual.
I know that 1.19.2 is not supported. But as the creator of the modpack with 1.1 million downloads, I will be very grateful for the release at least with 1 of this fix.

**Comment by AlexModGuy** [comment]
Issue should not be present in new worlds using Citadel 2.3.4/2.1.4. For old worlds, NBTExplorer will be needed to reset the level WorldGenSettings. After that is done it should no longer appear.

**Comment by AlexModGuy** [comment]
For continuing saves with this bug:

"https://www.youtube.com/watch?v=Dp5hcxxPx28

  1.  Backup world! It is very important. If you make a mistake with even one step or click, you will irrevocably ruin the world.

  2.  Create brand new world with name like "NewNew" after updating Citadel to 2.1.4+ (1.19.2) or 2.3.4+ (1.19.4). In no case do not use the Re-Create feature built into minecraft. The problem will remain! If you have changed the parameters of the world, restore them from your memory and create a world with exactly these parameters.

  3.  Open saves in NBT Explorer, expand NewNew/level.dat/Data/WorldGenSettings/dimensions.

   4. Click "dimensions", use menu Edit/Copy

  5. Expand OldWorld/level.dat/Data/WorldGenSettings

  6.  Click "dimensions", use menu Edit/Delete

   7. Click "WorldGenSettings", use menu "Edit/Paste

   8.  Save file

   9. Close NBT Explorer

   10. Teleport to the border of the generated and non-generated area and check that it converges. This is very important! If you make a mistake somewhere, it will ruin your world!"

**Comment by uhloin** [comment]
I still have the issue with citadel-2.1.4-1.19
I will reset it again and report a bit later.

**Comment by uhloin** [comment]
No, It's not fixed. After creation of new world level.dat tree was as on the screenshot 1 (will attach) and after 2 saves I got the screenshot 2. Pay attention to branch surface_rule
![sreenshot1](https://github.com/AlexModGuy/AlexsMobs/assets/96169906/5b41a9d0-edaf-48d5-bda2-9f01bccf50d3)
![screenshot2](https://github.com/AlexModGuy/AlexsMobs/assets/96169906/77d763fb-e668-4b6a-860c-816cb4acdcf1)

**Comment by KostromDan** [comment]
> No, It's not fixed. After creation of new world level.dat tree was as on the screenshot 1 (will attach) and after 2 saves I got the screenshot 2. Pay attention to branch surface_rule ![sreenshot1](https://user-images.githubusercontent.com/96169906/241885389-5b41a9d0-edaf-48d5-bda2-9f01bccf50d3.png) ![screenshot2](https://user-images.githubusercontent.com/96169906/241885380-77d763fb-e668-4b6a-860c-816cb4acdcf1.png)

Try to reproduce it with only terrablender, any worldgen mod, which is dependent on it, citadel. If you manage to repeat it, it is very strange since I failed. Otherwise, you are looking for a different mode by brute force, which causes this. Write to me if you can find this mod.

**Comment by uhloin** [comment]
After update to latest version of TerraBlender it's fixed, thank you
