### ISSUE TITLE
Only a select few mobs spawn.

### ISSUE THREAD

**Issue by Brodend1** [Alex-the-666/AlexsMobs#1484]
In the past few versions, only the new mobs since Release 1.15.0 (Caves and Cliffs Update) will spawn consistently, with others in the mix such as grizzly bears, cachalot whales, and hummingbirds. I tested on 1.18.2 versions and can confirm something had changed between those updates that messed with mob spawning. I have redownloaded forge and looked at the differences between versions. Please fix this bug. It makes the mod completely pointless, and it must be a rare bug since I only see a few people bringing it up.

**Comment by SooshiGuy** [comment]
Try resetting the config and see if that works.
