### ISSUE TITLE
Cant use it

### ISSUE THREAD

**Issue by robertjozef** [Alex-the-666/AlexsMobs#151]
Hi,
I'm trying to make a server on aternos with this mod, citadel, and 2 other extra mods.
When launching my server i get error messages in history. Heres an example: [30Jan2021 22:51:29.736] [modloading-worker-1/ERROR] [net.minecraft.util.Util/]: No data fixer registered for elephant 
How do i fix this? I have played this mod along with those 2 other mods and citadel on another server and it worked perfectly fine there.
Thanks in advance,
robertjozef

**Comment by Alex-the-666** [comment]
thats just a warning that no datafixers(used only when minecraft updates versions) are there for elephant. This is expected since 1. elephant only exists in 1.16+ and 2. elephants are a modded mob and therefore cannot have a datafixer.
