### ISSUE TITLE
Why Do Not Have A Fabric

### ISSUE THREAD

**Issue by MuzanAwnKingerGyuu** [Alex-the-666/AlexsMobs#1512]
Do you intend to make a fabric version?
to be more precise, to have a future Alex's Mobs ( Fabric ), Need your API ( Citadel ) Updated for Fabric too?

**Comment by SooshiGuy** [comment]
The dev of the mod said he will not port this mod to fabric.

**Comment by PlummetStudios** [comment]
No. It will never happen. It is way too much effort for the less popular modloader.
