### ISSUE TITLE
(1.19.2) Crash on hit specific mobs of Alex's Mobs

### ISSUE THREAD

**Issue by Jaeyong1114** [Alex-the-666/AlexsMobs#1556]
When i hit some mobs of Alex's Mobs like Cachalot or Giant Squid
[242월2023 05:02:27.843] [Netty Server IO #3/WARN] [Implementer/ASYNC_CATCHER]: Async chunk entity get
[242월2023 05:02:27.843] [Netty Server IO #3/WARN] [Implementer/ASYNC_CATCHER]: Async chunk entity get
[242월2023 05:02:27.888] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Jaeyong97 lost connection: Internal Exception: java.lang.IllegalStateException: EntityDamageEvent cannot be triggered asynchronously from another thread.
[242월2023 05:02:27.888] [Server thread/INFO] [voicechat/]: Disconnecting client Jaeyong97

I have noticed that this error is caused by using Arclight buckets.
So I asked the bucket creator
he said 
"This should be reported to alex mob developer with these information:
The packet is handled on netty thread.MessageHurtMultipart"
[latest (1).log](https://github.com/AlexModGuy/AlexsMobs/files/10819980/latest.1.log)

**Comment by RoryBlanco** [comment]
I had the same issue. Though I only had it happen on Beached Giant Squids and Blue Giant Squids.

**Comment by RoryBlanco** [comment]
It also only seems to crash when you hit the top portion of the squid.

**Comment by vgrynch** [comment]
I also have the same issue, happens every time the message "MessageHurtMultipart" is sent and an a few other cases. Any tips to workaround this? (Except the disabling relevant mobs).

Happens with:
Cachalot whale
Giant squid
When starting the hooded falcon to explore

**Comment by vgrynch** [comment]
If you are using ArcLight, I have patched it there for 1.19.2

**Comment by vgrynch** [comment]
Here is the advice from the experienced dev (IzzelAliz, developed of ArcLight) on this issue, please, can you incorporate this fix? (Please, do it also for Bald Eagle flying issues.)

> just add a ctx.get().enqueue that wraps all the code below
![image](https://github.com/AlexModGuy/AlexsMobs/assets/46818018/21e0762e-39d7-4e2f-a551-d3c92c2d46c1)

**Comment by ColdTearsYY** [comment]
same question on 1.20.1 omg

**Comment by zoe-may** [comment]
The issue persists in Arclight 1.20.1 and Alex’s Mobs 1.22.8.
