### ISSUE TITLE
Custom Modpack based on BMC2 crash when loading up world due to ticking entity mimicube

### ISSUE THREAD

**Issue by TheOmnicGG** [Alex-the-666/AlexsMobs#1583]
I have spent quite a while in my game and there have been no issues so far, however, I recently received a crash as well as the crash stating that a ticking entity was the cause. I checked and it was indeed a mimicube.

Here is the crash log: 
[crash-2023-04-05_22.19.37-server.txt](https://github.com/AlexModGuy/AlexsMobs/files/11163304/crash-2023-04-05_22.19.37-server.txt)

I will try other things but hopefully this can be resolved well.

**Comment by AlexModGuy** [comment]
> sweenus.simplyswords.effect.WildfireEffect
caused by simply swords mod
