### ISSUE TITLE
[1.16.5] Ticking Entity Crash while exploring

### ISSUE THREAD

**Issue by mr-poyo** [Alex-the-666/AlexsMobs#162]
Forge Jar: 36.0.13
alexsmobs-1.5.0.jar
ScalingHealth-1.16.4-4.0.3+3.jar

There seems to be some ticking entity crash triggering while I have both scaling health + Alex mobs active. It happened while exploring. When disabling either alexsmobs/scaling health, the crash went away.

Line 8 of the crash report references alexsmobs
Line 24 of the crash report references scalinghealth

https://pastebin.com/uNcsGaCv

Hope this helps!

**Comment by LordGuppy** [comment]
Same issue using scaling health as well.

Here is my crash report
https://pastebin.com/Y9yUBM8S

**Comment by IRonicBruh** [comment]
+1

**Comment by Yourname942** [comment]
Same

**Comment by Alex-the-666** [comment]
fixed

**Comment by recklessrider** [comment]
This is not fixed FYI

**Comment by recklessrider** [comment]
Crash log: https://filebin.net/tlu5m2q1clgri3ft/crash-2021-02-06_16.55.25-server.txt?t=qwqpocg6

**Comment by mr-poyo** [comment]
Your log shows version 1.5.0. Don't think the update has been published yet. Might take some time to appear on curseforge @recklessrider
