### ISSUE TITLE
Seagul with Lunchbox Mod

### ISSUE THREAD

**Issue by Florian2133** [Alex-the-666/AlexsMobs#1622]
The Lunchboxes in the "Lunchbox  Mod" counts as an food item so seagulls steal them and the lunchbox including all the food inside gets destroyes.

Does anyone have a solution since the lunchbox is not cheap and its anoying that all the fodd gets destroyed because of the shitty seagulls.

**Comment by NovaLynxie** [comment]
There is a stealing blacklist in the config now.
Refer to issue #631 for more information.
Though for now you may have to disable that if it keeps happening.
