### ISSUE TITLE
Holding Artifacts Umbrella while looking at mimicube repeatadly crashes game

### ISSUE THREAD

**Issue by DyllPickle-pal** [Alex-the-666/AlexsMobs#163]
Looking at a mimicube while holding an umbrella from the artifacts mod (specifically in the offhand). had to remove the item via NBT editor to resume gameplay.

**Comment by Alex-the-666** [comment]
this is an issue that will **have** to be fixed by Artifacts devs. Stop reporting it to us! Report it to them. they should not cast any holder to Player without checking first!
