### ISSUE TITLE
[BUG] Ghostly pickaxe item duplication glitch

### ISSUE THREAD

**Issue by nahyun71** [Alex-the-666/AlexsMobs#1630]
![2023-05-25_20 43 53](https://github.com/AlexModGuy/AlexsMobs/assets/134608919/4aea0bf8-1597-4b1a-adaa-b29026da7e8d)
So I filled inventory like this, ghostly pickaxe, one set of blocks to duplicate (diamond blocks) and other items (bricks)
![2023-05-25_20 43 33](https://github.com/AlexModGuy/AlexsMobs/assets/134608919/afbd3b06-6a93-4643-a49c-afd6efe99b65)
get extra diamond blocks and place it. the inventory should remain full. then mine at least two diamond blocks with ghostly pickaxe.
![2023-05-25_20 44 06](https://github.com/AlexModGuy/AlexsMobs/assets/134608919/d348defd-6636-4478-ab2d-f8f4c5a1252c)
when you place a couple of diamond blocks, you can see it duplicates itself. the diamond blocks just keep filling themselves up so they never run out.
this duplication glitch works with other blocks that can be stacked up like iron blocks, and planks

also my english is pretty bad cuz it's not my native language

**Comment by zzzaitegui** [comment]
I've also been able to replicate this bug with any block, shulkers too (so you can dupe anything). It works on stackable blocks normally and if you use the "Digging claws" from the Artifacts mod that give you faster mining speed (which I'm assuming is what makes it work for non-stackable blocks) it works on any block. This was Alex mobs version 1.21.1, on forge 1.19.2-43.2.6 (artifatcs was version 5.0.2)

**Comment by ochotonida** [comment]
Fixed in Artifacts version 5.0.4. To prevent similar issues with other mods, you should probably give your HarvestCheck event handler a lower priority.

**Comment by kitovoi111** [comment]
No fixed in Alex's Mobs
