### ISSUE TITLE
[Bug] Crash caused by capturing Whale and Giant Squid in Industrial Forgoing Mob Imprisonment ball 

### ISSUE THREAD

**Issue by DemonSeedxp** [Alex-the-666/AlexsMobs#1635]
Just as the title says, capturing the whale and giant squid causes a hard crash back to title screen, invoking an Internal exception:java.lang.NullPointerException:Cannotinvoke"net.minecraft.world.entity.Entity.m_20185_(J"because"p_20271"isnull error

Running Forge  43.2.11 Minecraft 1.19.2 Alex's Mobs 1.21.1

![zLAK78doeI](https://github.com/AlexModGuy/AlexsMobs/assets/11554194/2b412ea5-ba14-418a-9142-d096ca9141a5)

**Comment by AlexModGuy** [comment]
send a full log
