### ISSUE TITLE
Getting error for Entity Type: alexsmobs:cachalot_whale 

### ISSUE THREAD

**Issue by Wulfninja90** [Alex-the-666/AlexsMobs#1644]
When i downloaded the Etho's Modded season 2 modpack and run the program during the loading time of game i crashed and following is the crash report. please help. 
[crash-2023-06-12_23.04.45-client.txt](https://github.com/AlexModGuy/AlexsMobs/files/11726540/crash-2023-06-12_23.04.45-client.txt)

**Comment by AlexModGuy** [comment]
dupe #1797
