### ISSUE TITLE
spawning warped mosco crashes the server

### ISSUE THREAD

**Issue by ReflectiveFlame** [Alex-the-666/AlexsMobs#1654]
whenever I spawn a warped mosco it crashed my server

**Comment by ReflectiveFlame** [comment]
it only happens when it does one of its attacks

**Comment by GramRex18** [comment]
This is also happening to me my world that I have worked so very hard on is now not able to be logged onto all because I tried fighting a warped mosco I do not know what to do please help me fix this issue

**Comment by HiGuysItsMeSussyBaka** [comment]
Same, it's the latest version of Alex's Mobs with the latest version of Citadel for version 1.20. No other mods. Here's the game log:
[New Paste 1 (1).txt](https://github.com/AlexModGuy/AlexsMobs/files/11803400/New.Paste.1.1.txt)

**Comment by AlexModGuy** [comment]
fixed
