### ISSUE TITLE
[1.20] [alexsmobs-1.22.4] Mounted mobs can't move

### ISSUE THREAD

**Issue by ferentas** [Alex-the-666/AlexsMobs#1666]
Rideable mobs like the elephant, bear, laviathan are not moving when tamed and mounted. They can turn in the direction player is looking but wont move in any direction. Won't move on their own either. They only turn in the direction player is looking when WASD keys are used. When WASD keys arent used, the player can look around 360 degrees and the mob will not change direction.

Mobs will also float in water when the player mounts them on water and uses WASD keys to move. Otherwise, they will sink till the water is at the player's waist level.

**Comment by Z4CKUND0** [comment]
I have the same issue did you solve it? Cant ride elephants bears comododragons any mob which you can ride other than horses and camels

**Comment by Z4CKUND0** [comment]
i mean you can ride them but they dont move
