### ISSUE TITLE
Ridable mobs doesnt move when its tamed

### ISSUE THREAD

**Issue by Z4CKUND0** [Alex-the-666/AlexsMobs#1669]
Ridable mobs doesnt move when its tamed.They dont move whatever you do.When you get down you can see the particles from their foot bot they dont move it ruins the mod

**Comment by ohelvira** [comment]
the same happens for me but only in 1.20.1 other versions like 1.19.2 or 1.16.5 worked fine before. i thought it might be because of an incompatible mod but now im not sure since other ppl are having this issue too.
