### ISSUE TITLE
[1.20.1] Forge update issue - Error in console - Failed to read chunk [117, -110] java.util.concurrent.CompletionException: java.lang.IllegalAccessError: class com.github.alexthe666.alexsmobs.entity.EntityRhinoceros tried to access private field net.minecraft.world.entity.Entity.f_19793_ (com.github.alexthe666.alexsmobs.entity.EntityRhinoceros is in module alexsmobs@1.22.4 of loader 'TRANSFORMER' @1480fe81; net.minecraft.world.entity.Entity is in module minecraft@1.20.1 of loader 'TRANSFORMER' @1480fe81)

### ISSUE THREAD

**Issue by ProsperCraft** [Alex-the-666/AlexsMobs#1672]
Stacktrace - 

https://gist.githubusercontent.com/ProsperCraft/bda5843affee1c4ac75f457cd96ff23f/raw/f425b28c843383aef05ef8f2e51f19f2cb086018/gistfile1.txt

Full log-

https://gist.githubusercontent.com/ProsperCraft/0597d8b26bdc2e6ed282b074cc2d1035/raw/781dd184bcda1aad45e268356c2f9f55c3a40e81/gistfile1.txt

alexsmobs-1.22.4
forge/1.20.1-47.0.34
Modpack- TownCraft for 1.20.1

**Comment by ProsperCraft** [comment]
Server crash report-
https://gist.githubusercontent.com/ProsperCraft/ef1226dbec0af3fbf6c9408d70d85482/raw/1d3d99ca3e34c9456ddd3fd7d2836dc5687cf793/gistfile1.txt

This seems to  have been caused from the Forge update from .19 to .34  Downgrading it back to .19 seems to have stopped the crashes and stacktraces in console.

**Comment by ProsperCraft** [comment]
Client crash - 

https://bytebin.lucko.me/mN37VguzkR

**Comment by OBS3SS1ON** [comment]
x2 
The game crashed whilst exception ticking world
Error: java.lang.IllegalAccessError: class com.github.alexthe666.alexsmobs.entity.EntityCentipedeHead tried to access private field net.minecraft.world.entity.Entity.f_19793_ (com.github.alexthe666.alexsmobs.entity.EntityCentipedeHead is in module alexsmobs@1.22.4 of loader 'TRANSFORMER' @2dd8a273; net.minecraft.world.entity.Entity is in module minecraft@1.20.1 of loader 'TRANSFORMER' @2dd8a273)

**Comment by OBS3SS1ON** [comment]
1.20.1-forge-47.0.34

**Comment by ProsperCraft** [comment]
@OBS3SS1ON The fix is to downgrade back to .19 it totally fixed it for us, I am scared though once the mods start requiring newer Forge.  Hopefully it gets fixed.
