### ISSUE TITLE
1.20.1 Entities are crashing servers and mobs wont move when ridden

### ISSUE THREAD

**Issue by softsasas** [Alex-the-666/AlexsMobs#1676]
I play coop with my friends via Aternos, and the server started crashing recently. I looked at crash reports, and it said that some entities were bugging the game. Also, when i ride my domesticated mobs, they won't move. Hope u fix it soon, this is my favorite mod <3

**Comment by softsasas** [comment]
sorry for the bad english, its not my first language :(

**Comment by JulllienD** [comment]
I got the same issue, the mod was working fine with Forge 1.20.1 - 47.0.19 but now it switched to Forge 47.0.34, and the Aternos server starts, but disconnect players when they're joining. Then the server doesn't work and we have to stop it. When the server starts, there is the error that says it couldn't load chunks, then when we join the entities are making the server crash.
