### ISSUE TITLE
1.20 Crash/Freeze

### ISSUE THREAD

**Issue by Inonedn** [Alex-the-666/AlexsMobs#1677]
[crash-2023-06-29_13.13.27-server.txt](https://github.com/AlexModGuy/AlexsMobs/files/11908614/crash-2023-06-29_13.13.27-server.txt)
[latest.log](https://github.com/AlexModGuy/AlexsMobs/files/11908622/latest.log)

**Comment by Inonedn** [comment]
[crash-2023-06-30_02.17.53-server.txt](https://github.com/AlexModGuy/AlexsMobs/files/11912106/crash-2023-06-30_02.17.53-server.txt)

**Comment by AlexModGuy** [comment]
fixed
