### ISSUE TITLE
[1.19.2] Game Freezes with Alex Mobs + Structure Gen

### ISSUE THREAD

**Issue by SHXRKIEgg** [Alex-the-666/AlexsMobs#1679]
As described in the IDAS [issue page ](https://legacy.curseforge.com/minecraft/mc-mods/idas/issues/87) Alex mobs seem to freezing when trying to spawn a elephant or wandering trader elephant. 

Here is the log and in it you can see it mentions the spawning of the elephant.
[latest (2).log](https://github.com/AlexModGuy/AlexsMobs/files/11913559/latest.2.log)

    at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.Mob.m_6914_(Mob.java:806)
    at TRANSFORMER/alexsmobs@1.21.1/com.github.alexthe666.alexsmobs.entity.EntityElephant.canSpawnWithTraderHere(EntityElephant.java:996)
    at TRANSFORMER/alexsmobs@1.21.1/com.github.alexthe666.alexsmobs.event.ServerEvents.onEntityJoinWorld(ServerEvents.java:494)
    at TRANSFORMER/alexsmobs@1.21.1/com.github.alexthe666.alexsmobs.event.__ServerEvents_onEntityJoinWorld_SpecialSpawn.invoke(.dynamic)

This also occurs with just the required mods from IDAS + Alex Mobs and its IDAS Datapack.

I don't see an option in the config to disable wandering traders with elephants?
With that I have not tested myself with just Alex mobs and it spawning with a wandering trader elephants and that could be the real issue.
If there is a way to disable it lmk and hope you would just do a small update fixing this?

**Comment by XionioXMaster** [comment]
same

**Comment by Greatone123** [comment]
Same here too, I've been trying to pregen a world, I get to one spot just locks up, and eventually times out. I found this post from the IDAS post.

I've removed, changed several things. However after finding this, I removed Alex's Mobs, and it finished without issue. So just throwing my hat in the ring.

**Comment by SHXRKIEgg** [comment]
I can confirm this can also be caused without IDAS. It seems whenever a structure generation and elephant collides it freezes. IDAS was on of them and then I was able to recreate another with another mod structure generating. Disabling Elephants and even using a mod like bad mobs to disable it completely also fails.

**Comment by brisingraerowing** [comment]
I just did some changes to my fork that *should* fix this issue. I also made the config values actually appear in the config file. Going to test it in a moment.

EDIT: It works! The seed I was getting this on no longer hangs!

**Comment by SHXRKIEgg** [comment]
> I just did some changes to my fork that _should_ fix this issue. I also made the config values actually appear in the config file. Going to test it in a moment.
> 
> EDIT: It works! The seed I was getting this on no longer hangs!

After more testing I found out underground miners from Ancient Mines also crashes sometimes. Want me to get that seed?

**Comment by brisingraerowing** [comment]
I deleted the world as it was mostly swamp and desert related biomes, and I wasn't liking it at all. Also, I've never had a Ghost Miner crash, and I've explored a number of Ancient Mines.

**Comment by Ahri-UwU** [comment]
I'm experiencing this problem but in 1.18.2 instead.

**Comment by MacatMovie** [comment]
How did valhesia 5 1.19.2 modpack manage to go around this crash?
They're using Alex's mobs version 1.20.2, is that one safe to use?

**Comment by jkkiller101** [comment]
Came here after encountering this issue on 1.19.2 with IDAS and killing the server... I noticed SHXRKIIE you said you had a fix? How does one disable elephants or fix it? and once again tried the bad mobs to see if it would work but no luck as previously said.

**Comment by JLCGaming** [comment]
> Came here after encountering this issue on 1.19.2 with IDAS and killing the server... I noticed SHXRKIIE you said you had a fix? How does one disable elephants or fix it? and once again tried the bad mobs to see if it would work but no luck as previously said.

I believe IDAS released a fix on their end, at least that's what the change log said a while back.

**Comment by jkkiller101** [comment]
I noticed that it says it fixed the issue in the most recent update of 1.7.6+ and yet no change as I'm already running that version. appreciate it though!
