### ISSUE TITLE
Most Armor Textures and Models Either Glitched or Aren't Visible At all

### ISSUE THREAD

**Issue by EpicTonyBoi** [Alex-the-666/AlexsMobs#1681]
i first noticed this issue with the sombrero and how it wouldn't show and then later as i was looking at the texture files noticed every texture was there and that all of the mappings or models werent there

**Comment by AlexModGuy** [comment]
Update forge

**Comment by EpicTonyBoi** [comment]
i am on the latest version 💀

**Comment by EpicTonyBoi** [comment]
if it is 1.20.1 and not 1.20 your should put that on your mod page... but the latest version of forge 1.20 is 46.0.14 and i have been using that version
