### ISSUE TITLE
Rocky Roller Keeps Crashing My Game

### ISSUE THREAD

**Issue by xeno0o** [Alex-the-666/AlexsMobs#1711]
I was testing out spawning all the alex mobs out of curiosity what they looked like and when it came to the rocky roller, it immediately freezes and then crashes my game. And I have tried many times and it only happens when it came to the rocky roller. Every other mobs do not crash my game. 

My friend tried in their own server and for them, they couldn't even spawn the rocky roller.

<img width="1197" alt="Screenshot 2023-07-14 at 1 30 46 AM" src="https://github.com/AlexModGuy/AlexsMobs/assets/139493679/8f264c76-d2e1-4a9a-b8db-045bf1061839">

**Comment by AlexModGuy** [comment]
dupe #1690
