### ISSUE TITLE
Laviathan crashing game upon trying to load new world

### ISSUE THREAD

**Issue by Veranidae** [Alex-the-666/AlexsMobs#1716]
When trying to load a world for the first time, the game crashes with "Exception in server tick loop"

[crash-2023-07-15_06.26.26-server.txt](https://github.com/AlexModGuy/AlexsMobs/files/12061159/crash-2023-07-15_06.26.26-server.txt)

**Comment by GlynLeine** [comment]
[crash-2023-07-15_19.43.43-server.txt](https://github.com/AlexModGuy/AlexsMobs/files/12062388/crash-2023-07-15_19.43.43-server.txt)

It's a null pointer exception in the Leviathan update:
`com.github.alexthe666.alexsmobs.entity.EntityLaviathanPart.m_6972_(EntityLaviathanPart.java:74) ~[alexsmobs-1.22.5.jar%23205!/:1.22.5] {re:classloading}`
`this.size` is null

**Comment by MeloDemonic** [comment]
Don't know exactly how much this differs from the current two crashes but here is another...
[crash-2023-07-16_15.29.11-server.txt](https://github.com/AlexModGuy/AlexsMobs/files/12064903/crash-2023-07-16_15.29.11-server.txt)

**Comment by Veranidae** [comment]
seems to work okay with an older forge version, crashes on the newest (47.1.39) and the recommended (47.1.0) but appears to work with 47.1.1
