### ISSUE TITLE
Does not work with Ultra Amplified Dimension

### ISSUE THREAD

**Issue by Hedgehog0091** [Alex-the-666/AlexsMobs#173]
Versions:
Minecraft 1.16.5
Forge 36.0.15
Alex's Mobs 1.5.1
Citadel 1.6.0
Ultra Amplified Dimension 9.0.3
(latest of everything at the time of writing)

When creating a world with Alex's Mobs, Citadel and Ultra Amplified Dimension [(link to mod)](https://www.curseforge.com/minecraft/mc-mods/ultra-amplified-mod) the world does not load due to an 'error in one of the current datapacks'.
This does not happen if only UAD and Citadel are installed, so it must be a conflict between Alex's Mobs and UAD.
![screenshot_of_error](https://user-images.githubusercontent.com/11356733/107299535-a779d800-6a45-11eb-9e94-145aa3dc5c1e.png)
Clicking 'Safe Mode' does not seem to do anything.

**Comment by Alex-the-666** [comment]
update citadel
