### ISSUE TITLE
The game crashes

### ISSUE THREAD

**Issue by ElBuhooo04** [Alex-the-666/AlexsMobs#1738]
The game crashes when Alex mobs is opened in version 1.20.1, more specifically when the JEI mod (Just Enough items) is installed, when you see the display of an item in the window when you open the inventory, that is the moment the game crashes, I suppose it is because of some mob that is previewed.

**Comment by krnzhnr** [comment]
I have the same problem. Of course, I don’t really understand what is written in the logs, but it seems to me that the transmutation table is involved here. I hope this problem will be fixed.
[crash-2023-07-24_16.42.59-client.txt](https://github.com/AlexModGuy/AlexsMobs/files/12146523/crash-2023-07-24_16.42.59-client.txt)

**Comment by Escanor336** [comment]
estou com o mesmo problema, onde eu consigo usar esse .txt?

**Comment by OysterStew** [comment]
Also crashes REI
