### ISSUE TITLE
Game crashes after few minutes in the world

### ISSUE THREAD

**Issue by StickySquid2727** [Alex-the-666/AlexsMobs#1742]
it says because of Rocky Roller

**Comment by StickySquid2727** [comment]
[crash-2023-07-26_16.05.23-server.txt](https://github.com/AlexModGuy/AlexsMobs/files/12174170/crash-2023-07-26_16.05.23-server.txt)
this the crash report

**Comment by AlexModGuy** [comment]
update citadel
