### ISSUE TITLE
*Temporary Issue* Transmutation Table rendering issue with Optifine pre 6

### ISSUE THREAD

**Issue by IndubitablyO** [Alex-the-666/AlexsMobs#1747]
As the title suggests, this is more an issue with optifine rather than alex mobs. 

The issue itself lies when browsing items in JEI, as you scroll through the pages, every item is rendered correctly, the game then crashes on the last page (for me) when the transmutation table is.

As mentioned, every other item from the mod renders in the JEI menu just fine, but not the transmutation table for some reason.

I can attach a crash report if this helps, please let me know.

**Comment by JacksonsShadow** [comment]
-- Item being rendered --
Details:
	Item Type: transmutation_table
	Item Damage: 0
	Item NBT: null
	Item Foil: false

**Comment by IndubitablyO** [comment]
Any updates on a fix?

**Comment by AlexModGuy** [comment]
dupe #1796
