### ISSUE TITLE
Centipede

### ISSUE THREAD

**Issue by Keolass** [Alex-the-666/AlexsMobs#1748]
I have a strong phobia of multi-legged insects, how can I turn off this huge centipede?

**Comment by B1adereaper** [comment]
You can disable it spawning in the config via the 'cave_centipede_spawns' file or via 'alexmobs.toml' and changing the spawn weight to 1000

**Comment by Keolass** [comment]
> 

![image](https://github.com/AlexModGuy/AlexsMobs/assets/62995410/c8aa28a0-37cd-4936-a785-324ce99ce1ec)

**Comment by Keolass** [comment]
> You can disable it spawning in the config via the 'cave_centipede_spawns' file or via 'alexmobs.toml' and changing the spawn weight to 1000

![image](https://github.com/AlexModGuy/AlexsMobs/assets/62995410/78ab7a58-c350-4ee0-b331-77aa81622d7f)

**Comment by Keolass** [comment]
> You can disable it spawning in the config via the 'cave_centipede_spawns' file or via 'alexmobs.toml' and changing the spawn weight to 1000

{
  "biomes": [
    [
      {
        "type": "BIOME_TAG",
        "negate": false,
        "value": "minecraft:is_overworld"
      },
      {
        "type": "BIOME_TAG",
        "negate": true,
        "value": "minecraft:is_ocean"
      },
      {
        "type": "BIOME_TAG",
        "negate": true,
        "value": "forge:is_mushroom"
      },
      {
        "type": "REGISTRY_NAME",
        "negate": true,
        "value": "minecraft:deep_dark"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "terralith:cave/andesite_caves"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "terralith:cave/desert_caves"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "terralith:cave/diorite_caves"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "terralith:cave/granite_caves"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "terralith:cave/ice_caves"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "terralith:cave/infested_caves"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "terralith:cave/thermal_caves"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "terralith:cave/crystal_caves"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "terralith:cave/frostfire_caves"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "terralith:cave/mantle_caves"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "terralith:cave/deep_caves"
      }
    ],
    [
      {
        "type": "REGISTRY_NAME",
        "negate": false,
        "value": "terralith:cave/tuff_caves"
      }
    ]
  ]
}
