### ISSUE TITLE
(1.20.1)Cachalots and dictionaries not working 

### ISSUE THREAD

**Issue by Veisia** [Alex-the-666/AlexsMobs#1752]
I have a problem in my game where cachalots whales simply do not exist in 1.20.1. They do not spawn even with an egg or summoning. This also cause another crucial problem in the dictionary. When I open the second page, the dictionary just make the game crash. Because it should have a cachalot render model in the dictionary and the absence of it just makes the entire game crash. I know that currently the development team is just working on Alex’s Caves but if they could maybe update Alex Mobs soon to fix these errors and others it would be really helpful.

**Comment by AlexModGuy** [comment]
dupe #1797
