### ISSUE TITLE
transmutation table Rendering item

### ISSUE THREAD

**Issue by GhiltonAbyss** [Alex-the-666/AlexsMobs#1757]
[](url)
[crash-2023-08-03_23.24.39-client.txt](https://github.com/AlexModGuy/AlexsMobs/files/12257039/crash-2023-08-03_23.24.39-client.txt)

**Comment by KrakenDezJokes** [comment]
I too am having the exact same issue. Ive compared the crash above to my own, It is the exact same crash

**Comment by AlexModGuy** [comment]
dupe #1796
