### ISSUE TITLE
[MC 1.19.4] [alexsmobs-1.22.3] EntityRockyRoller StackOverflow

### ISSUE THREAD

**Issue by DarthShader** [Alex-the-666/AlexsMobs#1760]
Rocky Rollers adjacent to each other (like if they are spawned in a confined area) recursively damage each other until servers/games will crash. This issue is listed separate from a few other Rocky Roller crashes because I am unsure if they are the exact same issue.

https://github.com/AlexModGuy/AlexsMobs/blob/c14c47e54bb785bb4fd026f6a90ad831df7882e3/src/main/java/com/github/alexthe666/alexsmobs/entity/EntityRockyRoller.java#L318

**Comment by AlexModGuy** [comment]
fixed
