### ISSUE TITLE
Alex mobs crash after opening the second page of the animal book

### ISSUE THREAD

**Issue by EmeraldTiger4** [Alex-the-666/AlexsMobs#1761]
![Posnetek zaslona 2023-08-07 133852](https://github.com/AlexModGuy/AlexsMobs/assets/141637021/2160f0b1-a13e-4e4f-960c-cb1456918b72)

If there is anything else i need to send tell me

**Comment by EmeraldTiger4** [comment]
yes it also crashes when its the only mod in the folder

**Comment by TNSGJones** [comment]
I had similar experiences, however when I removed Optifine it didn't crash anylonger. Crashlog when Optifine was installed and the second page of the book was opened.

[crash-2023-08-08_23.57.43-client.txt](https://github.com/AlexModGuy/AlexsMobs/files/12296384/crash-2023-08-08_23.57.43-client.txt)
