### ISSUE TITLE
World crash until I delete de mod

### ISSUE THREAD

**Issue by masd98** [Alex-the-666/AlexsMobs#1763]
(Sorry for my english) This is the error that appear everytime that crash my game.

The game crashed whilst ticking entity
Error: java.lang.IllegalAccessError: class com.github.alexthe666.citadel.server.entity.collision.ICustomCollisions tried to access private field net.minecraft.world.entity.Entity.f_19793_ (com.github.alexthe666.citadel.server.entity.collision.ICustomCollisions is in module citadel@2.4.1 of loader 'TRANSFORMER' @e7b265e; net.minecraft.world.entity.Entity is in module minecraft@1.20.1 of loader 'TRANSFORMER' @e7b265e

I was only able to play again by deleting the mod

**Comment by AlexModGuy** [comment]
update citadel
