### ISSUE TITLE
Ticking entity - CRASH TIGER - Entity Type: alexsmobs:tiger (com.github.alexthe666.alexsmobs.entity.EntityTiger)

### ISSUE THREAD

**Issue by isrado855** [Alex-the-666/AlexsMobs#1774]
[crash-2023-08-17_22.09.14-server.txt](https://github.com/AlexModGuy/AlexsMobs/files/12374465/crash-2023-08-17_22.09.14-server.txt)

Whenever the mob will be generated, it crashes the world and I can't go back, neither opening or closing.

**Comment by AlexModGuy** [comment]
update citadel
