### ISSUE TITLE
1.20.1 Crocodile armor

### ISSUE THREAD

**Issue by Zerachan** [Alex-the-666/AlexsMobs#1775]
My crocodile armor does not stack with the centipede leggings or with other pieces of equipment, is it only me? >.<

**Comment by borssuk** [comment]
same thing happening to me still

for some reasons it seems that when having it on , only 1 armor points from leggings gets counted
![Zrzut ekranu 2024-01-20 194541](https://github.com/AlexModGuy/AlexsMobs/assets/54995976/8ff6cd7b-e96f-4c5b-a99c-0cd7b6cffd7d)
![Zrzut ekranu 2024-01-20 194531](https://github.com/AlexModGuy/AlexsMobs/assets/54995976/88d8fa8f-9a94-46b1-aeae-983901f2bd68)

**Comment by borssuk** [comment]
also , the smae thing happens with antlers and boots
![Zrzut ekranu 2024-01-21 211850](https://github.com/AlexModGuy/AlexsMobs/assets/54995976/df4d04a6-f71f-4e37-96b6-e1d2195aa3be)
![Zrzut ekranu 2024-01-21 211841](https://github.com/AlexModGuy/AlexsMobs/assets/54995976/465e17ee-70cc-4bc8-9395-f0cc590f60b4)
