### ISSUE TITLE
Game crashes when turning to Page 2 of the Animal Dictionary

### ISSUE THREAD

**Issue by GucciLibrarian** [Alex-the-666/AlexsMobs#1777]
In Alex's Mobs version 1.22.5 and Forge 47.1.28 (and possibly other version combinations) the game will crash whenever the player tries to turn to page 2 in the animal dictionary. The crash report yields the following text:

The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Cannot invoke 
"net.minecraft.world.entity.EntityDimensions.m_20388_(float)"
because "this.size" is null

**EDIT** - This issue is resolved with newer versions of Forge. If encountering this issue, try using an updater version.

**Comment by Crepuscul0** [comment]
I'm having the same issue.

**Comment by Nwbyyy** [comment]
Same issue on Forge 47.1.10

**Comment by ilya-nikolaev** [comment]
This happens because of rendering CombJelly.
Perhaps this is due to the use of Optifine

Reference: #1707

**Comment by AlexModGuy** [comment]
dupe #1796
