### ISSUE TITLE
Crashing because of second page of book and one creature

### ISSUE THREAD

**Issue by yagryt** [Alex-the-666/AlexsMobs#1780]
"Прозиратели" (idk what name of it in eng) and second page of the book causing crashes

**Comment by VastleCania** [comment]
If you're running Optifine, try disabling that mod. There seems to be some sort of incompatibility.

If it is optifine, then I think this is the main issue: https://github.com/AlexModGuy/AlexsMobs/issues/1766

**Comment by AlexModGuy** [comment]
dupe #1796
