### ISSUE TITLE
[1.20.1] Rocky Roller causing crashes, unable to load save after crashes occur

### ISSUE THREAD

**Issue by CosmicGlowsticks** [Alex-the-666/AlexsMobs#1786]
Title pretty much sums it up.
I am using the most recent version of the mod and the recommended version of forge (1.20.1-forge-47.1.0)

[crash-2023-09-01_20.30.52-server.txt](https://github.com/AlexModGuy/AlexsMobs/files/12503086/crash-2023-09-01_20.30.52-server.txt)
[crash-2023-09-01_20.34.15-server.txt](https://github.com/AlexModGuy/AlexsMobs/files/12503087/crash-2023-09-01_20.34.15-server.txt)
I left both crash reports here.

**Comment by AlexModGuy** [comment]
update citadel
