### ISSUE TITLE
Alex Ur Mod Have Bug Or Something  (1.20.1 Forge)

### ISSUE THREAD

**Issue by MugooS** [Alex-the-666/AlexsMobs#1788]
Hey Alex i was using ur mod and just enough items mod. When i skip pages on just enough items or skip items on creative mode My game crashes when it comes to one of your mob eggs. When i delete ur mod i can use all jei pages. Please find bug mob and solve. Have a good day.

**Comment by emiloski94** [comment]
I have the same, I had to remove them or skip one page in my case

**Comment by Natt-y** [comment]
Hi, same issue here. Maybe the bug mob is Murmur, because when i tried to search its egg in JEI it crashed the game.

**Comment by AlexModGuy** [comment]
dupe #1796
