### ISSUE TITLE
Book crashes game when switching to 2nd page

### ISSUE THREAD

**Issue by Kileru11** [Alex-the-666/AlexsMobs#1789]
So whenever i play and open the mob book , when i go to 2nd page the games freezes for 2 sec and then turns off

**Comment by emiloski94** [comment]
i have exactly the same

**Comment by Vhaeyne** [comment]
Getting the same issue on my friend's laptop, but not my PC. We copied everything back and forth multiple times to make sure the settings were the same. One PC Crashes on page two, the other does not. Been pulling our hair out trying to find out what exactly is going wrong.

**Comment by AlexModGuy** [comment]
dupe #1796
