### ISSUE TITLE
[1.19.2] Vine Lasso Crash

### ISSUE THREAD

**Issue by DoctorMage** [Alex-the-666/AlexsMobs#1791]
Forge:43.2.23
Minecraft: 1.19.2

Using a lasso on a minecolonies mob will cause a ticking entity crash

Simplest solution add a mob blacklist to lasso

Mods Involved

structurize-1.19.2-1.0.630-RELEASE.jar
multipiston-1.19.2-1.2.21-ALPHA.jar
minecolonies-1.19.2-1.1.138-RELEASE.jar
domum_ornamentum-1.19-1.0.107-RELEASE-universal.jar
citadel-2.1.4-1.19.jar
blockui-1.19-0.0.69-ALPHA.jar
alexsmobs-1.21.1.jar

Logs

Debug Log
https://gist.github.com/DoctorMage/fc8551e54039a9fe35270f0acc968959

Crash Report
https://gist.github.com/DoctorMage/1ca4f6f278fb60b73c8b3623a626009b

**Comment by AlexModGuy** [comment]
minecolonies bug

**Comment by uecasm** [comment]
This is not a MineColonies bug.  Don't go calling AI path navigation on client side; see `PathfinderMob#tickLeash` for reference (called server side only).

**Comment by someaddons** [comment]
@AlexModGuy its clearly a bug of this mod, your event which is literally called server events is doing stuff on client side it should not :D
`	at com.github.alexthe666.alexsmobs.event.__ServerEvents_onLivingUpdateEvent_LivingTickEvent.invoke(.dynamic) ~[alexsmobs-1.21.1.jar%23158!/:1.21.1]
`
