### ISSUE TITLE
2 Crashes. JEI & Book.

### ISSUE THREAD

**Issue by Zeyeo** [Alex-the-666/AlexsMobs#1793]
Hello. I am experiencing issues with the latest update of the mod.
when using the animal book and flipping the pages game very suddenly crashes leaving screen blue with a small black square and then closing down.

2nd when scrolling through the pages in JEI getting to a certain page within Alex's mobs makes game freeze and then crash down
(suspecting this is one of the mob eggs causing the instant crash.)

No log for both the crashes just Exit Code: -1

Minecraft version 1.20.1
Mod Version: alexsmobs-1.22.5.
Forge - 47.1.43

**Comment by AlexModGuy** [comment]
dupe #1796
