### ISSUE TITLE
Crash When Using Book

### ISSUE THREAD

**Issue by MoriQuendi23** [Alex-the-666/AlexsMobs#1802]
Hi opening the book to the second page crashes the game.

[crash-2023-09-14_18.00.25-client.txt](https://github.com/AlexModGuy/AlexsMobs/files/12611566/crash-2023-09-14_18.00.25-client.txt)

**Comment by TheJacksonOfGreen** [comment]
I also have this problem. Providing another crashlog just in case anyone sees any similarities. 

[crash-2023-09-15_21.24.00-client.txt](https://github.com/AlexModGuy/AlexsMobs/files/12634606/crash-2023-09-15_21.24.00-client.txt)

**Comment by OysterStew** [comment]
Same here

**Comment by VastleCania** [comment]
This seems to be the same as many of the closed bugs - I think it's still an incompatibility with Optifine. I tested with the newest version and had the same issue, so the bug is not resolved yet.

**Comment by TheJacksonOfGreen** [comment]
> I think it's still an incompatibility with Optifine. 

My pack uses Rubidium over Optifine (because Create). Respectfully, I don't think it's that simple.

**Comment by BlazeDeku** [comment]
I have this problem as well, except I don't use Rubidium or Optifine, but a several Forge mods.

I did notice that this only happens when using the vanilla Minecraft launcher. When I use the CurseForge client launcher, I don't have any crashes when reading the rest of the bestiary ingame.

Maybe it's how Curseforge sets up the mod files? Probably worth looking into.

**Comment by TheJacksonOfGreen** [comment]
Swapped from Rubidium to Embeddium. Still have this issue. 
[crash-2023-10-06_12.50.57-client.txt](https://github.com/AlexModGuy/AlexsMobs/files/12833496/crash-2023-10-06_12.50.57-client.txt)

**Comment by NemesisWolf92** [comment]
También se me cierra el juego cuando trato de cambiar a la segunda pagina del libro, ¿lo van a parchear?

**Comment by AlexModGuy** [comment]
dupe #1900
