### ISSUE TITLE
Alex's mobs 1.22.6 Crashes the game with Oculus

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/AlexsMobs#1811]
I discovered that version 1.22.6 Crashes the game with Oculus,I discovered this the help of the sever of AtLauncher, after a couple minutes playing the game decide to just crash and if I try to join the world again it crashes after one second.
 [crash-2023-09-22_18.32.38-client.txt](https://github.com/AlexModGuy/AlexsMobs/files/12705212/crash-2023-09-22_18.32.38-client.txt)
![Screenshot_39](https://github.com/AlexModGuy/AlexsMobs/assets/144281112/2719af4a-2486-45cb-a44b-ec8ccb5bcf5b)

**Comment by AlexModGuy** [comment]
> Caused by: io.github.steelwoolmc.shadow.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectGetFacing(FFF)Lnet/minecraft/core/Direction; in fabric-renderer-api-v1.mixins.json:client.OverlayVertexConsumerMixin from mod (unknown) failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabric-renderer-api-v1-refmap.json

are you running the mod on fabric? it's meant for forge.
