### ISSUE TITLE
Kicked/Crash from using Transmutation Table

### ISSUE THREAD

**Issue by Inonedn** [Alex-the-666/AlexsMobs#1818]
![image](https://github.com/AlexModGuy/AlexsMobs/assets/36087299/62d8d270-2caf-43c4-a032-2d2d12041e91)

**Comment by Inonedn** [comment]
[crash-2023-09-28_16.19.36-server.txt](https://github.com/AlexModGuy/AlexsMobs/files/12753645/crash-2023-09-28_16.19.36-server.txt)

**Comment by Inonedn** [comment]
[latest (4).log](https://github.com/AlexModGuy/AlexsMobs/files/12766374/latest.4.log)

**Comment by AlexModGuy** [comment]
dupe #1862
