### ISSUE TITLE
Transmutation Server Crash

### ISSUE THREAD

**Issue by RiyDoesNothing** [Alex-the-666/AlexsMobs#1821]
The transmutation table crashes the entire server after a random amount of uses. The only way to stop it from crashing is to exit the table's GUI after every transmutation.

Crash Log: https://mclo.gs/JFzaEoV OR [Crash Report.txt](https://github.com/AlexModGuy/AlexsMobs/files/12794036/Crash.Report.txt)
The server we're using is Exaroton

EDIT: I also have the most recent version of alex's mobs and citadel

**Comment by AlexModGuy** [comment]
dupe #1862
