### ISSUE TITLE
Game crash and unable to load back in

### ISSUE THREAD

**Issue by bmemike** [Alex-the-666/AlexsMobs#183]
Was in my first end city and just killed a pair of shulkers (not sure if this matters) and the game crashed.

With the following error. When I loaded back in, it partially renders the world but hangs and crashes with the same error.

Was running Enigmatica 6 v0.3.11 when this happened w/ AlexsMobs v1.4.1. I upgraded it manually to v1.5.1 and ran into other errors. 

I also upgraded Enigmatica 6 to v0.3.13 and loaded the save file and it crashes with the same error. The rendered image is slightly different (a little more loads), but I still don't have the ability to move or interact with the game. 

![crash](https://user-images.githubusercontent.com/29279375/107463328-d9656a00-6b2b-11eb-9cf1-c0b424332c72.png)
![freeze_screen](https://user-images.githubusercontent.com/29279375/107463331-dbc7c400-6b2b-11eb-8eb0-b7de5d4e8024.png)
[crash-2021-02-10_03.51.35-client.txt](https://github.com/Alex-the-666/AlexsMobs/files/5955778/crash-2021-02-10_03.51.35-client.txt)

**Comment by Alex-the-666** [comment]
dupe #163

**Comment by bmemike** [comment]
Sorry for the dupe.

Thanks for pointing me to the right problem. Updated Artifacts to the latest version which fixes this bug. 

Hopefully Enigmatica updates their pack soon to eliminate the noise.
