### ISSUE TITLE
(1.20.1)Some mobs don't spawn

### ISSUE THREAD

**Issue by AnomalHydra** [Alex-the-666/AlexsMobs#1837]
I wanted to play alex's caves after some time i decieded to add the latest version of alex's mobs and i didn't see any crows or racoons,
i didn't mind it but there was also no fishes no flys.One day when i went into the nether and i saw straddlers and crimson musqitoes so only some animals don't spawn.So i deleted every mod i had(wihout alex's mobs or citadel)and still doesn't work

**Comment by melapela235** [comment]
you can fix?

**Comment by AlexModGuy** [comment]
delete configs
