### ISSUE TITLE
Comb Jelly crashes game

### ISSUE THREAD

**Issue by zefkie** [Alex-the-666/AlexsMobs#1840]
I was in a iceberg biome when my game stopped and crashed with a weird graphical distortion and gave a -1 error code on the launcher stating: "The game crashed whilst rendering entity in world. Error: java.lang.IllegalArgumentException: Duplicate delegates" The crash report told me it struggled to render a "Comb Jelly" I created a new creative world and tried to spawn a Comb Jelly in that world and it crashed with the same graphical error.
[crash-2023-10-21_16.55.29-client.txt](https://github.com/AlexModGuy/AlexsMobs/files/13061973/crash-2023-10-21_16.55.29-client.txt)

**Comment by AlexModGuy** [comment]
dupe #1900

**Comment by ker73rus** [comment]
> dupe #1900

This is trouble with Optifine, it cant renderer combjelly

**Comment by ker73rus** [comment]
Just unistal Optifine, its helped

> I was in a iceberg biome when my game stopped and crashed with a weird graphical distortion and gave a -1 error code on the launcher stating: "The game crashed whilst rendering entity in world. Error: java.lang.IllegalArgumentException: Duplicate delegates" The crash report told me it struggled to render a "Comb Jelly" I created a new creative world and tried to spawn a Comb Jelly in that world and it crashed with the same graphical error. [crash-2023-10-21_16.55.29-client.txt](https://github.com/AlexModGuy/AlexsMobs/files/13061973/crash-2023-10-21_16.55.29-client.txt)
