### ISSUE TITLE
Leafcutter ant path finding

### ISSUE THREAD

**Issue by Ladocterus** [Alex-the-666/AlexsMobs#1841]
Alex's mobs 1.22.6
leaf cutter ant workers and queens do not path find back to their nest, just wander around.

**Comment by GreenForzeGaming** [comment]
this
i actully think the ants are cute but they just wander around and the hill never grows

**Comment by GreenForzeGaming** [comment]
![image](https://github.com/AlexModGuy/AlexsMobs/assets/62345403/82e85a74-d974-4972-bdaa-282727b5dc40)
i guess they try to go up? then they just stand still.
