### ISSUE TITLE
Game crashing 1.20.1 exit code 1

### ISSUE THREAD

**Issue by solivanxd** [Alex-the-666/AlexsMobs#1843]
I have tried many other mods and they all work in my modpack, but only the alexmobs mod does not work, the exit code is 1.

Is there any solution?

**Comment by symoner66** [comment]
This code might mean that you're missing a required mod. Did you get Citadel? There is a link at the top of AlexsMobs page.

**Comment by X0bananas0X** [comment]
Having the same issue with this specific mod, also made sure i had citadel installed. could it be a corrupted config file? is so then how to fix?

**Comment by Seadragon91** [comment]
Well wanted to test the mod and got the same error and found out why , but don't know if It's the same problem.

Looks like curseforge ( I think) is doing something wrong with adding citadel:
![image](https://github.com/AlexModGuy/AlexsMobs/assets/14818618/734b2341-27d2-4e3a-af1d-850e83c10c2f)
![image](https://github.com/AlexModGuy/AlexsMobs/assets/14818618/4cee8af8-521f-4a96-8eb7-b816f18bc0e4)

As you see it's the same file size and the same md5 hash, somehow the mod citadel is the same mod file like alex mobs's...

Workaround:
Download citadel from here for version 1.20.1 and overwrite the citadel file in the mods folder:
https://www.curseforge.com/minecraft/mc-mods/citadel/files?page=1&pageSize=20

To get to the mods folder: Right-click the profile -> "Open Folder -> mods.

I searched around, but found no option to clear a cache in curseforge or where curseforge is caching downloaded mods.
Maybe a reinstall could fix that problem, but I don't want to do it...

**Comment by cosierwolf** [comment]
ya I'm getting this problem too with this mod when i try to open a new pack that I'm working on.

**Comment by Seadragon91** [comment]
Looks like the problem I had is gone, can't reproduce it anymore.
