### ISSUE TITLE
[Crash] Opening world

### ISSUE THREAD

**Issue by Matthysse** [Alex-the-666/AlexsMobs#185]
Hello!
Here is a crash I have when opening my world with your mod mentioned:
https://pastebin.com/d93XFitM

**Comment by TheSnowyChickens** [comment]
Hello,
same issue here.

-> 
[crash-2021-02-10_18.42.07-client.txt](https://github.com/Alex-the-666/AlexsMobs/files/5960240/crash-2021-02-10_18.42.07-client.txt)

**Comment by Matthysse** [comment]
Weird... seems to be a one-time thing, I restarted the game with the 1.5.1 version and every thing updated, and it now works...
