### ISSUE TITLE
Weird Advancement screen and crashes with Animal Book and new Animals

### ISSUE THREAD

**Issue by Norizaki96** [Alex-the-666/AlexsMobs#1855]
Since I discovered the first Advancements of the Mod, my Screen looks now like this. I can't see the other fields and have to click a lot to change the site. Whenever I move the mouse, the animals change (two pictures as example here) and I can't see Information about the advancement itself.

However, there are many crashes too. I.e. when I fly around with Elytra and want to discover stuff, I crashes a lot when new animals (mostly in the water) are loading. Also, when I want to spawn them with /summon or use spawneggs, I mostely crash at the first time. 100% crash is when I want to open second page on the animal book. Are there any fixes known? I searched every mod up and put in a new version. 
![2023-11-01_15 18 48](https://github.com/AlexModGuy/AlexsMobs/assets/149594752/9a1fc98d-6182-4ee9-ba1a-d5635638f843)
![2023-11-01_15 43 11](https://github.com/AlexModGuy/AlexsMobs/assets/149594752/9a6407ec-eb23-4b58-b9a3-f5268bc8c868)

**Comment by artiemoth** [comment]
I'm getting the same glitch, I've tried reinstalling the mod but doesn't seem to change
