### ISSUE TITLE
Extremely frequent game crashes 

### ISSUE THREAD

**Issue by Jonastheginger** [Alex-the-666/AlexsMobs#1859]
Anytime I flip to the 2nd page of the Animal Dictionary, the game crashes. This also happens whenever I scroll down the Alex’s Mobs tab in the creative menu. I’ve also experienced a crash whenever I spawn the comb jelly. I’m sure this is the case with other mobs, I just haven’t been able to find out which.

**Comment by AlexModGuy** [comment]
dupe #1900
