### ISSUE TITLE
Game crash by cachalot whale, giant squid and crow 1.20.1

### ISSUE THREAD

**Issue by Rozz97** [Alex-the-666/AlexsMobs#1874]
alexsmobs-1.22.6
[crash-2023-11-17_00.47.34-client.txt](https://github.com/AlexModGuy/AlexsMobs/files/13388278/crash-2023-11-17_00.47.34-client.txt)
[crash-2023-11-16_23.56.27-client.txt](https://github.com/AlexModGuy/AlexsMobs/files/13388279/crash-2023-11-16_23.56.27-client.txt)
[crash-2023-11-17_01.45.26-client.txt](https://github.com/AlexModGuy/AlexsMobs/files/13388833/crash-2023-11-17_01.45.26-client.txt)

**Comment by AlexModGuy** [comment]
> 	at net.mehvahdjukaar.dummmmmmy.common.ModEvents.onEntityHeal(ModEvents.java:100) ~[dummmmmmy-1.20-1.8.9.jar%23337!/:?] {re:mixin,re:classloading}

crash is from dummmmmmy mod
