### ISSUE TITLE
What does "lavawaxed" do?

### ISSUE THREAD

**Issue by Acat1234** [Alex-the-666/AlexsMobs#1878]
I tryed throwing the enchanted item in lava and it burned the book doesnt tell what it does so what does it do?

**Comment by HaiSamuel** [comment]
1) Github is not to post that type of question, bloats real bugs, a quick google search can answer that question for you.
2) If you have Enchantment Descriptions mod you can know what it does in-game (Makes the user have fire resistance when riding the straddleboard)

**Comment by Explode007** [comment]
You don't ask that question on the Github page, there is a discord, a wiki and google search.

Since you are going to read this anyways, it makes the player have fire resistance when riding the straddleboard

**Comment by Acat1234** [comment]
oh
