### ISSUE TITLE
Compatability Crash with Iron's Spellbooks in the ModelAMElytra class

### ISSUE THREAD

**Issue by WardenDrew** [Alex-the-666/AlexsMobs#1882]
When an `irons_spellbooks:necromancer` is spawned in, there is a game crash due to an unchecked entity reference in the ModelAMElytra class's `withAnimations(LivingEntity entity)` method. 

https://github.com/AlexModGuy/AlexsMobs/blob/c466c07ad10e7f906293b39f0d56e39b75099e51/src/main/java/com/github/alexthe666/alexsmobs/client/model/layered/ModelAMElytra.java#L33

I'm not sure why for this specific entity from Iron's spellbooks is causing this parameter to be null, but at a minimum null guarding this method should mitigate the crash.

Crash Log: https://gist.github.com/WardenDrew/a52573fc95e04c14bcd8ca244360a201

Alex's Mobs Version: `1.22.6`
Forge Version: `1.20.1-47.2.0`
Iron's Spellbooks Version: `1.20.1-2.0.2`

**Comment by WardenDrew** [comment]
Related closed issue from Iron's Spellbooks: https://github.com/iron431/Irons-Spells-n-Spellbooks/issues/219

**Comment by n0itLT** [comment]
It is still having problem.
