### ISSUE TITLE
Game crash occurred when the new map was hung up

### ISSUE THREAD

**Issue by Prolxs** [Alex-the-666/AlexsMobs#1883]
When hanging up in the new game map, a crash suddenly occurs, and the game launcher prompts that the reason is from Alexsmobs. After the crash, restarting the game to enter the map will still cause the crash.
[latest.log](https://github.com/AlexModGuy/AlexsMobs/files/13433372/latest.log)

**Comment by Prolxs** [comment]
Just now, I noticed that after giving the raccoon food, it behaves strangely. It swims to the middle of the pool and circles around

**Comment by AlexModGuy** [comment]
> net.coderbot.iris.pipeline
not my mod
