### ISSUE TITLE
Lumberjackosaurus achievement barely obtainable.

### ISSUE THREAD

**Issue by Jackose** [Alex-the-666/AlexsMobs#1892]
I've been utilizing a relicheirus I've named "Val" to cut down trees by feeding him primordial soup. I just discovered there is an achievement for this a couple minutes ago. This wouldn't be a problem except I've used Val to cut down over 40 pewens and only just now got the achievement. What ???. (Also don't worry I replanted them).

Game version: 1.20.1

Other mods: Alex's Mobs, Farmer's Delight.

**Comment by AlexModGuy** [comment]
not issue with this mod
