### ISSUE TITLE
Game still crashes when flipping the book to the next page when using optifine

### ISSUE THREAD

**Issue by sorrtt-byte** [Alex-the-666/AlexsMobs#1897]
it said that it was fixed but it isn't and when using optifine (I6_pre6) and with the newest version of alex's mobs, when you open the book and flip to the next page the game crashes

**Comment by thefewu** [comment]
Yeah, I have the same problem, but if I switch to a different version of optifine, Minecraft worlds don't open, so I can't use the book.

**Comment by AlexModGuy** [comment]
dupe #1900
