### ISSUE TITLE
Crash with Physics Mod v164

### ISSUE THREAD

**Issue by Kill6r** [Alex-the-666/AlexsMobs#1904]
I get this error after a few seconds of enabling the ocean in the settings (it only happens in multiplayer mode) 
[crash-2023-12-18_02.20.46-client.txt](https://github.com/AlexModGuy/AlexsMobs/files/13700784/crash-2023-12-18_02.20.46-client.txt)

The mod to make a port between fabric and forge has nothing to do with it, the error has been there since before I put this mod
List Mods: 
![image](https://github.com/AlexModGuy/AlexsMobs/assets/99845669/84a408e9-230e-4749-a149-ba159753c147)

**Comment by Kill6r** [comment]
Suspected Mods: 
	Alex's Mobs (alexsmobs), Version: 1.22.6
		Issue tracker URL: https://github.com/Alex-the-666/AlexsMobs/issues
		at TRANSFORMER/alexsmobs@1.22.6/com.github.alexthe666.alexsmobs.entity.EntityFlyingFish.m_8119_(EntityFlyingFish.java:128)

**Comment by AlexModGuy** [comment]
> 	at net.diebuddies.physics.ocean.OceanWorld.createWaterSplash(OceanWorld.java:780) 

not my crash
