### ISSUE TITLE
Potoo pathfinding causing high tick rate

### ISSUE THREAD

**Issue by Midnex** [Alex-the-666/AlexsMobs#1907]
I had Potoo in a small room with mostly carpet from Fantasy Furniture mod, and while in the room Potoo caused roughly 9.4% of all entity ticks. You can find more here, clicking on mods
https://spark.lucko.me/0zhN2dkTNl then Alexsmobs.
Ultimately picking the entity up with an Ender Leash instantly stopped the lag in the game.

Not sure what else you need.

**Comment by llanerost** [comment]
Ty!
