### ISSUE TITLE
My server is crashing

### ISSUE THREAD

**Issue by NovaProYT** [Alex-the-666/AlexsMobs#1913]
[crash-2023-12-24_23.28.42-server.txt](https://github.com/AlexModGuy/AlexsMobs/files/13763048/crash-2023-12-24_23.28.42-server.txt)

**Comment by PandaX-0** [comment]
Hey, What is your mod list?

**Comment by AlexModGuy** [comment]
dupe https://github.com/AlexModGuy/AlexsMobs/issues/1369
