### ISSUE TITLE
Crows Missing Language for Subtitle 

### ISSUE THREAD

**Issue by SamL2020** [Alex-the-666/AlexsMobs#192]
Example: 
![Example](https://user-images.githubusercontent.com/66446458/107833657-f97e6e80-6d61-11eb-97d8-467fae828fcb.png)

**Comment by Vaelzan** [comment]
That was fixed in Alex's Mobs 1.5.1, you should update the mod to the latest version (and certainly have it updated before submitting issue reports).

**Comment by SamL2020** [comment]
Ah I'm sorry about that.
