### ISSUE TITLE
[1.16.5] Possible server performance issue with elephants

### ISSUE THREAD

**Issue by MarioSMB** [Alex-the-666/AlexsMobs#193]
The elephant code to search for caravans appears to taking a lot of the thread runtime, according to Spark: https://spark.lucko.me/#fdRkD1JA4e

I have reason to believe the 15 elephants near our base were causing the server to be overloaded.

**Comment by codec-d** [comment]
Still a problem

com.github.alexthe666.alexsmobs.entity.EntityElephant.tick()1.52%
net.minecraft.entity.MobEntity.tick()1.52%
net.minecraft.entity.LivingEntity.tick()1.52%
com.github.alexthe666.alexsmobs.entity.EntityElephant.livingTick()1.27%
net.minecraft.entity.passive.AnimalEntity.livingTick()1.27%
net.minecraft.entity.AgeableEntity.livingTick()1.27%
net.minecraft.entity.MobEntity.livingTick()1.27%
net.minecraft.entity.LivingEntity.livingTick()1.27%
net.minecraft.entity.MobEntity.updateEntityActionState()1.07%
net.minecraft.entity.ai.goal.GoalSelector.tick()1.07%
java.util.stream.ReferencePipeline.forEach()1.07%
java.util.stream.AbstractPipeline.evaluate()1.07%
java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential()1.07%
java.util.stream.ForEachOps$ForEachOp.evaluateSequential()1.07%
java.util.stream.AbstractPipeline.wrapAndCopyInto()1.07%
java.util.stream.AbstractPipeline.copyInto()1.07%
java.util.Spliterators$IteratorSpliterator.forEachRemaining()1.07%
java.util.Iterator.forEachRemaining()1.07%
java.util.stream.ReferencePipeline$2$1.accept()1.07%
java.util.stream.ForEachOps$ForEachOp$OfRef.accept()0.95%
net.minecraft.entity.ai.goal.GoalSelector$$Lambda$49333/0x000000084709c440.accept()0.95%
net.minecraft.entity.ai.goal.PrioritizedGoal.tick()0.95%
com.github.alexthe666.alexsmobs.entity.ai.ElephantAIFollowCaravan.tick()0.57%
com.github.alexthe666.alexsmobs.entity.ai.ElephantAIForageLeaves.tick()0.39%
