### ISSUE TITLE
Rocky Roller Ticking Entity [1.20.1]

### ISSUE THREAD

**Issue by SpookyWoogin** [Alex-the-666/AlexsMobs#1932]
[crash-2024-01-14_19.39.29-server.txt](https://github.com/AlexModGuy/AlexsMobs/files/13934626/crash-2024-01-14_19.39.29-server.txt)

Newest Version of Alex's Mobs and Citadel installed, crash occurred shortly after a player on said server found a Rocky Roller

**Comment by AlexModGuy** [comment]
fixed
