### ISSUE TITLE
Server crash when using Transmutation table

### ISSUE THREAD

**Issue by TheCrystalPig** [Alex-the-666/AlexsMobs#1951]
[crash-2024-02-08_18.35.21-server.txt](https://github.com/AlexModGuy/AlexsMobs/files/14213349/crash-2024-02-08_18.35.21-server.txt)

Occasionally when someone on the server transforms items in the transmutation table, it will crash the server with this crash report remaining consistent each time

Edit: I did some digging and it seems like this crash occured in the past, was supposedly fixed in the latest version but it is still occuring

**Comment by Blugori** [comment]
WHAT I WAS DOING :
In creative mode, I was testing the transmutation table.

WHAT HAPPENED :
While transforming item with the transmutation table or with an second one near the first, game crashed and I got this error message :

The game crashed whilst accessing legacyrandomsource from multiple threads
Error: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads

It happened on forge 47.2.20 for 1.20.1. and Alexs mobs is 1.22.7, Citadel is 2.5.3. There are no other mods.

I hope it can be fixed, the work on this mod is awesome.

Crash log : 
[crash-2022-09-20_10.17.57-client.txt](https://github.com/AlexModGuy/AlexsMobs/files/14358358/crash-2022-09-20_10.17.57-client.txt)

Latest log :
[latest.log](https://github.com/AlexModGuy/AlexsMobs/files/14358363/latest.log)

debug log :
[debug.log](https://github.com/AlexModGuy/AlexsMobs/files/14358366/debug.log)

**Comment by MrAyfan** [comment]
Hello :)
Same problem multiple times. Completely random
[crash-2024-03-03_21.56.22-server.txt](https://github.com/AlexModGuy/AlexsMobs/files/14474635/crash-2024-03-03_21.56.22-server.txt)

[crash-2024-03-03_21.23.11-server.txt](https://github.com/AlexModGuy/AlexsMobs/files/14474638/crash-2024-03-03_21.23.11-server.txt)

[crash-2024-03-03_13.52.43-server.txt](https://github.com/AlexModGuy/AlexsMobs/files/14474640/crash-2024-03-03_13.52.43-server.txt)

forge 47.2.20, Alexs mobs 1.22.7 and Citadel is 2.5.3
