### ISSUE TITLE
cant rejoin my own server

### ISSUE THREAD

**Issue by Korrosake** [Alex-the-666/AlexsMobs#199]
The game crashed whilst rendering entity in world
Error: java.lang.ClassCastException: com.github.alexthe666.alexsmobs.client.model.ModelMimicube cannot be cast to net.minecraft.client.renderer.entity.model.BipedModel
Exit Code: -1

this thing attacked me and now i cant do anything anymore. as soon as i join my server my game crashes and it takes another 10 minutes to start.

**Comment by Alex-the-666** [comment]
dupe #108
