### ISSUE TITLE
Underminer related ticking entity crash

### ISSUE THREAD

**Issue by Happy-Meek** [Alex-the-666/AlexsMobs#2009]
Game crashed and the last message in the log had something to do with the underminer in a mineshaft. Can't access world anymore because game keeps crashing.

[latest.log](https://github.com/AlexModGuy/AlexsMobs/files/14644529/latest.log)

**Comment by MagnamIndie** [comment]
I too recently had this issue pop on one of my worlds and, unfortunately, I could not recover said world.

**Comment by AlexModGuy** [comment]
fixed
