### ISSUE TITLE
JER not showing information correctly with version 1.5.1

### ISSUE THREAD

**Issue by JaytheUnwise123** [Alex-the-666/AlexsMobs#201]
When version 1.5.1 of this mod is in use with Just Enough Resources ( https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer ), there is a noticeable amount of information missing. The thing that stood out at first was the fact that it refuses to show past a certain number of pages of info in the mob drops section: 
![image](https://user-images.githubusercontent.com/77471541/108277968-200c2300-712f-11eb-9823-8af2bf8ce429.png)
Looks like an incompatibility, and it only does this with 1.5.1, works fine with 1.5.0.

**Comment by Alex-the-666** [comment]
Report this to JER not us
