### ISSUE TITLE
Alex's Mobs (alexsmobs) encountered an error during the sided_setup event phase

### ISSUE THREAD

**Issue by Sixdd6** [Alex-the-666/AlexsMobs#202]
Alex's Mobs (alexsmobs) encountered an error during the sided_setup event phase.

Java: 11.0.9
Minecraft; 1.16.5
Forge: 36.0.42
Alex Mobs: 1.5.1

Log files:
[crash-2021-02-17_21.36.22-fml.txt](https://github.com/Alex-the-666/AlexsMobs/files/6000081/crash-2021-02-17_21.36.22-fml.txt)
[latest.log](https://github.com/Alex-the-666/AlexsMobs/files/6000084/latest.log)

**Comment by Alex-the-666** [comment]
dupe #137
