### ISSUE TITLE
Crash on Game Start

### ISSUE THREAD

**Issue by Amale16** [Alex-the-666/AlexsMobs#204]
Exception Message: java.lang.ArrayIndexOutOfBoundsException: 512

[crash-2021-02-18_13.44.51-fml.txt](https://github.com/Alex-the-666/AlexsMobs/files/6005096/crash-2021-02-18_13.44.51-fml.txt)

**Comment by Alex-the-666** [comment]
dupe #137

**Comment by comp500** [comment]
This doesn't look like the same crash... either way, this seems to be a Forge issue where `DispenserBlock.registerBehavior` doesn't account for parallel loading (it isn't threadsafe).
