### ISSUE TITLE
Please! Add additional configuration options for entities.

### ISSUE THREAD

**Issue by mimic2300** [Alex-the-666/AlexsMobs#205]
Hi, please add a configuration option for all individual entities (animals). At least the number of lives. attack, speed and number of spawns.

Example:
I want Grizzly to be more aggressive and harder, or spawn more. And currently what I was looking at is not possible. Or I didn't find how.

Thanks!

**Comment by Alex-the-666** [comment]
sadly not because that would bloat the already bloated config file
