### ISSUE TITLE
Add blacklist for who/what Catfishes can eat.

### ISSUE THREAD

**Issue by Mickeon** [Alex-the-666/AlexsMobs#2051]
We discovered the Catfishes can eat Cobblemon's Pokemon which has rather erratic behavior. I do not want to disable Catfishes for this reason alone. I am suggesting to implement a blacklist for entities Catfishes _cannot_ eat regardless of size.

**Comment by Seamonster778778778788** [comment]
to add: catching these cobblemon also corrupts your player data, requiring deletion from the server or meticulous editing to prevent crashing from opening the PC in game. the randomization effect breaks rendering/loading of the pokes
