### ISSUE TITLE
Question - how to disable spawning?

### ISSUE THREAD

**Issue by LughtMon** [Alex-the-666/AlexsMobs#2059]
Hello, I want to disable spawning of certain mobs, I have found folder in config containing json source files of all mobs, but I kinda don't understand what I should set to false and what to true or if simply deleting the code in it would do the magic. Can you help me?
![Screenshot_1](https://github.com/AlexModGuy/AlexsMobs/assets/159626781/9ccc7b0d-d9f5-4792-ab11-618a38d0ea2f)

**Comment by Razelda1362** [comment]
i would also like to know how to stop the spawn of one spicific mob
i have a phobia of the bugs that are found underground and wish to get rid of them from the game but am not sure how to do so

**Comment by LughtMon** [comment]
> i would also like to know how to stop the spawn of one spicific mob i have a phobia of the bugs that are found underground and wish to get rid of them from the game but am not sure how to do so

I have found yesterday, that alexmobs has a folder in "config", but also it's .toml file where you can disable any mob you want. You can find the list on the wiki. 
![image](https://github.com/AlexModGuy/AlexsMobs/assets/159626781/a07d2567-6862-4e73-a8b2-8d13cdd934e7)

**Comment by CircusSeal** [comment]
> > i would also like to know how to stop the spawn of one spicific mob i have a phobia of the bugs that are found underground and wish to get rid of them from the game but am not sure how to do so
> 
> I have found yesterday, that alexmobs has a folder in "config", but also it's .toml file where you can disable any mob you want. You can find the list on the wiki. ![image](https://private-user-images.githubusercontent.com/159626781/336150608-a07d2567-6862-4e73-a8b2-8d13cdd934e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NjExODYsIm5iZiI6MTcyMjk2MDg4NiwicGF0aCI6Ii8xNTk2MjY3ODEvMzM2MTUwNjA4LWEwN2QyNTY3LTY4NjItNGU3My1hOGIyLThkMTNjZGQ5MzRlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxNjE0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTQ2YjFjMDYwM2U2MDU2MmIwYWZiYmU4NzQxMWFmN2Y3NjAwYmYzOGVjMTljY2E0YzNkOWNmODdiZDA3ODM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Hcfmocw6dVG0YYoHm9w0UtP8FR-S0q_25Ya4jTSKmrY)

The .toml file causes the game to crash upon loading whenever I edit it. I tried to change the stealing-related rules to false, and the game would crash when I launch (Prismlauncher, Minecraft 1.18 and 1.20.1). I tried to turn off spawns entirely, but I can't figure out how to do that either.

**Comment by LughtMon** [comment]
> > > i would also like to know how to stop the spawn of one spicific mob i have a phobia of the bugs that are found underground and wish to get rid of them from the game but am not sure how to do so
> > 
> > 
> > I have found yesterday, that alexmobs has a folder in "config", but also it's .toml file where you can disable any mob you want. You can find the list on the wiki. ![image](https://private-user-images.githubusercontent.com/159626781/336150608-a07d2567-6862-4e73-a8b2-8d13cdd934e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NjExODYsIm5iZiI6MTcyMjk2MDg4NiwicGF0aCI6Ii8xNTk2MjY3ODEvMzM2MTUwNjA4LWEwN2QyNTY3LTY4NjItNGU3My1hOGIyLThkMTNjZGQ5MzRlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxNjE0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTQ2YjFjMDYwM2U2MDU2MmIwYWZiYmU4NzQxMWFmN2Y3NjAwYmYzOGVjMTljY2E0YzNkOWNmODdiZDA3ODM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Hcfmocw6dVG0YYoHm9w0UtP8FR-S0q_25Ya4jTSKmrY)
> 
> The .toml file causes the game to crash upon loading whenever I edit it. I tried to change the stealing-related rules to false, and the game would crash when I launch (Prismlauncher, Minecraft 1.18 and 1.20.1). I tried to turn off spawns entirely, but I can't figure out how to do that either.



> > > i would also like to know how to stop the spawn of one spicific mob i have a phobia of the bugs that are found underground and wish to get rid of them from the game but am not sure how to do so
> > 
> > 
> > I have found yesterday, that alexmobs has a folder in "config", but also it's .toml file where you can disable any mob you want. You can find the list on the wiki. ![image](https://private-user-images.githubusercontent.com/159626781/336150608-a07d2567-6862-4e73-a8b2-8d13cdd934e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NjExODYsIm5iZiI6MTcyMjk2MDg4NiwicGF0aCI6Ii8xNTk2MjY3ODEvMzM2MTUwNjA4LWEwN2QyNTY3LTY4NjItNGU3My1hOGIyLThkMTNjZGQ5MzRlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxNjE0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTQ2YjFjMDYwM2U2MDU2MmIwYWZiYmU4NzQxMWFmN2Y3NjAwYmYzOGVjMTljY2E0YzNkOWNmODdiZDA3ODM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Hcfmocw6dVG0YYoHm9w0UtP8FR-S0q_25Ya4jTSKmrY)
> 
> The .toml file causes the game to crash upon loading whenever I edit it. I tried to change the stealing-related rules to false, and the game would crash when I launch (Prismlauncher, Minecraft 1.18 and 1.20.1). I tried to turn off spawns entirely, but I can't figure out how to do that either.

Hmm, download mod "Spark" and check logs if you can find the issue there. It can clash with other mods whenever you edit it. Or simply bug related to your system, that is possible too.
