### ISSUE TITLE
Can't load when datapack mod biomes/dimensions are present?

### ISSUE THREAD

**Issue by stepsword** [Alex-the-666/AlexsMobs#206]
I think this issue has been brought up [before](https://github.com/Alex-the-666/AlexsMobs/issues/173), but I figured I'd contribute a log to make it easier. I'm the mahou dev - mahou adds a barebones biome/dimension via datapack but the world can't be loaded when both mods are present. I imagine Rats might(?) have a similar issue cause of the biome it adds but I haven't tested.

https://pastebin.com/JQZWWfdW

**Comment by Alex-the-666** [comment]
update citadel mod
