### ISSUE TITLE
1.21 port

### ISSUE THREAD

**Issue by gohkenytp** [Alex-the-666/AlexsMobs#2071]
Isn't there an 1.21 port for Alex's Mobs yet? Cause some people have just started porting them to 1.21

**Comment by devingDev** [comment]
People have ported alex's mobs or their own mods?
I'm also looking to add this on my 1.21 neoforge server.

**Comment by MrAidenPearce** [comment]
probably other mods which are updated for 1.21 for eg zmedival music and cuisine delight, etc

**Comment by tir38** [comment]
@AlexModGuy you marked this complete last month but I don't see any 1.21  versions up on curseforge? Is this done?

https://www.curseforge.com/minecraft/mc-mods/alexs-mobs/files/all?page=1&pageSize=20

**Comment by Quizer9O8** [comment]
> > [@AlexModGuy](https://github.com/AlexModGuy) you marked this complete last month but I don't see any 1.21 versions up on curseforge? Is this done?
> > https://www.curseforge.com/minecraft/mc-mods/alexs-mobs/files/all?page=1&pageSize=20
> 
> I think they left Java development for the bedrock marketplace. As simple as greed.

This is quite a bold statement. Do you have any prove to verify this?

**Comment by nathanapples** [comment]
No updates on this?
