### ISSUE TITLE
Sugar Glider Crash 

### ISSUE THREAD

**Issue by CyberRat7** [Alex-the-666/AlexsMobs#2089]
The game completley crashes whenever a Sugar Glider finishes foraging through leaves for loot, This is on the most recent version of Alexs Mobs and Citadel.

[crash-2024-07-15_22.06.27-server.txt](https://github.com/user-attachments/files/16239760/crash-2024-07-15_22.06.27-server.txt)

@AlexModGuy

**Comment by joanshattershergame** [comment]
Was having a similar issue, pretty sure it's caused by a weird incompatibility between Alex's Mobs and the decoration mod Twigs. Literally no clue why, just that the game crashes when they're both installed and doesn't when they're installed individually.
