### ISSUE TITLE
help me please (minecraft world crashes)

### ISSUE THREAD

**Issue by deijusa** [Alex-the-666/AlexsMobs#2093]
The game crashed whilst ticking entity
Error: java.lang.IllegalAccessError: class com.github.alexthe666.citadel.server.entity.collision.ICustomCollisions tried to access private field net.minecraft.world.entity.Entity.f_19793_ (com.github.alexthe666.citadel.server.entity.collision.ICustomCollisions is in module citadel@2.4.1 of loader 'TRANSFORMER' @47666b39; net.minecraft.world.entity.Entity is in module minecraft@1.20.1 of loader 'TRANSFORMER' @47666b39)

**Comment by AlexModGuy** [comment]
update forge and citadel
