### ISSUE TITLE
after checking every mod to find why my game has been crashing, alex's mobs turns out to be the reason.

### ISSUE THREAD

**Issue by yohanabanana** [Alex-the-666/AlexsMobs#2094]
i use version 1.20 on forge, downloaded the mod and it kept crashing everytime i try to open the game. this is the error message: The game crashed whilst initializing game
Error: java.lang.IncompatibleClassChangeError: class net.coderbot.iris.gui.option.ShadowDistanceOption cannot inherit from final class net.minecraft.client.OptionInstance

**Comment by AlexModGuy** [comment]
> coderbot.iris

report to iris devs
