### ISSUE TITLE
[CRASH] Crashes when entering Nether.

### ISSUE THREAD

**Issue by TheCodingZombie** [Alex-the-666/AlexsMobs#2099]
[crash-2022-07-16_14.51.42-server.txt](https://github.com/user-attachments/files/16420028/crash-2022-07-16_14.51.42-server.txt)

Hello! I have recently come across this issue while playing on a modpack I created. Seemingly, the Bone Snake entity causes crashes while "ticking". The log states the Alex's Mobs and Gempire are the main source of the issue, so perhaps some compatibility issues are found there.

This issue is consistent whenever I load up the Nether. When loading into the world, I get greeted with a black screen, then "Server Closed", and finally, the game closes and crashes, giving me this log. 

For the time being, I have loaded into a separate modpack with all the old mods, just without Alex's Mobs. No issues seem to have arised.

**Comment by AlexModGuy** [comment]
> 	at vazkii.quark.content.automation.module.FeedingTroughModule.temptWithTroughs(FeedingTroughModule.java:97) ~[Quark-3.2-358.jar%23265!/:3.2-358] {re:mixin,re:classloading}
	at net.minecraft.world.entity.ai.goal.TemptGoal.handler$dgf000$findTroughs(TemptGoal.java:529) ~[client-1.18.2-20220404.173914-srg.jar%23331!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:TemptGoalMixin,pl:mixin:A}


quark bug report to them
