### ISSUE TITLE
[Suggestion] Mosquito repellent

### ISSUE THREAD

**Issue by MarioSMB** [Alex-the-666/AlexsMobs#210]
It would be nice to have a counter to the crimson mosquitoes, to avoid having them randomly latch onto you while traversing the Nether... perhaps this could be done in the form of an insect repellent which provides temporary immunity to being bitten by crimson mosquitoes.

As a side note, it may help to reduce their health to allow more easily countering them by killing them before they can reach you.

**Comment by Alex-the-666** [comment]
Already exists, Bug Pheromones potion
