### ISSUE TITLE
Farseer Crashes 1.20.1 forge server whenever it spawns

### ISSUE THREAD

**Issue by EyaeM** [Alex-the-666/AlexsMobs#2105]
i have spent 40 mins now reading the logs to see why my server crashes whenever I join to see farseer erroring out the server and basically chunk banning me but worse since the whole server crashes LOG : https://mclo.gs/ya6G8gS

**Comment by LittleDeD** [comment]
Same issue.
Here is the crash log: https://pastebin.com/WBpUe8pv

**Comment by LittleDeD** [comment]
Another thing to note is that this happens only on the server side!
Running a singleplayer world does not crash the map.
The error is about loading a model for the farseer. Maybe the mod tries to do it server side where it shouldn't?

**Comment by EyaeM** [comment]
> Another thing to note is that this happens only on the server side! Running a singleplayer world does not crash the map. The error is about loading a model for the farseer. Maybe the mod tries to do it server side where it shouldn't?

Yeah that's probably it why is the server trying to load the model when it doesn't have a rendering engine to fix this I just place a command block at spawn which instakills them whenever they spawn

**Comment by LittleDeD** [comment]
I have InControl and I made a rule to deny any spawn or join of the mob in the world from any source (player, world, summon).
But this should not be the solution for this problem and I think we will not have a solution anytime soon...

**Comment by EyaeM** [comment]
> I have InControl and I made a rule to deny any spawn or join of the mob in the world from any source (player, world, summon). But this should not be the solution for this problem and I think we will not have a solution anytime soon...

whats incontrol

**Comment by LittleDeD** [comment]
InControl! mod is made by McJty and it has a complex system of defining rules about spawning. It has a wiki and some examples (it's quite hard to understand how to write those rules; it took me some days to understand some basic mob cap rules =)) ).
I've made the rule to deny any spawn of that mob and it's being removed before it actually spawns, so the model won't load.
