### ISSUE TITLE
[1.6.0] Hatched crocodiles are never tamed

### ISSUE THREAD

**Issue by Carro1001** [Alex-the-666/AlexsMobs#214]
Crocodiles are never tamed when hatched, and don't seem to be able to be tamed with anything either, tried hatching them near me, placing the eggs myself, leaving a crocodile to lay the eggs, none of these work, the baby is always a wild one and attacks the player on sight after growing up.

**Comment by Hunt3r552** [comment]
I have a similar issue, my crocs won't act friendly after being hatched on 1.16.5

**Comment by Alex-the-666** [comment]
fixed
