### ISSUE TITLE
No Roadrunners Found in Badlands

### ISSUE THREAD

**Issue by Robongio** [Alex-the-666/AlexsMobs#217]
As much as I adore this mod so far, which definitely lives it up to Mo' Creatures' legacy, I still think there is a problem needs to be addressed:
![FalseADFacts](https://user-images.githubusercontent.com/18617748/108920055-4d2b6a80-7634-11eb-9e2d-e0cdcf4b8fd6.jpg)
Yep! Pretty self-explanatory right here.

**Comment by Alex-the-666** [comment]
will be fixed in 1.7.0
