### ISSUE TITLE
Config option to be able to use mimicream to get mending

### ISSUE THREAD

**Issue by Darth-Pikachu** [Alex-the-666/AlexsMobs#218]
We noticed in game that when duplicating our tools that it wouldn't duplicate mending. I checked the source to make sure this wasn't a bug to find out that the mimicream recipe type is hard coded to not duplicate mending.

Is there any reason why mending can't be an option? (Especially in modpacks where getting to the end might already a challenge.)

**Comment by Alex-the-666** [comment]
Intentional game design

**Comment by Darth-Pikachu** [comment]
So you wouldn't allow packdevs to use mimicream as the only way to get renewable mending?
