### ISSUE TITLE
Mimicube Crashes Server (Valhelsia 3 3.1.8a)

### ISSUE THREAD

**Issue by Noxfield** [Alex-the-666/AlexsMobs#227]
Tried deleting end and another mimicube spawned and caused it to crash again

[crash-2021-02-27_23.15.00-server.txt](https://github.com/Alex-the-666/AlexsMobs/files/6056313/crash-2021-02-27_23.15.00-server.txt)

**Comment by Alex-the-666** [comment]
Should be fixed in the next release of Psi
