### ISSUE TITLE
(suggestion) I would like you to add a angler fish

### ISSUE THREAD

**Issue by Abishark** [Alex-the-666/AlexsMobs#230]
Since the blobfish, a pasific deep-sea fish, were added, I'd like a hostile one to be added as well, and there is nothing better than an anglerfish. My idea is that it somehow attracts you with its lure and then grab you with its huge mouth, until death. Since he ate you, he will also eat your items, so you will not be able to retrieve them. That was my idea that I wanted to share :D

This came to my head when I saw a model of an anglerfish in minecraft, and when I saw it I thought: hey ... it looks a lot like alex's mod.  And that is why, here I leave you the model, just in case: https://sketchfab.com/3d-models/minecraft-angler-fish-5046e55b17fd46a8b65663c35710ee44

**Comment by Alex-the-666** [comment]
no suggestions here.
