### ISSUE TITLE
[1.16.5] Burning Moose and Lobster drop raw meat

### ISSUE THREAD

**Issue by Kisutora** [Alex-the-666/AlexsMobs#231]
**Forge:** release 1.16.5-forge-36.0.43
**Alexs Mobs:** [1.6.0](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs/files/3213812)

Moose and Lobster drop raw meat when on fire, should be cooked.

**Comment by Alex-the-666** [comment]
Fixed in 1.7.0.
