### ISSUE TITLE
Confi function not available

### ISSUE THREAD

**Issue by Hsinyao99** [Alex-the-666/AlexsMobs#239]
Just found this awesome mod, but can’t see the configuration after getting into the Minecraft main screen mod tab. I saw that the mod was highly configurable, I wonder is there other ways to configure it? Have the latest forge and citadel installed. Btw, the mod works fine and mobs are spawning.

**Comment by Carro1001** [comment]
You can't edit mod configs in the game itself in 1.14+, you must go to .minecraft/config/alexsmobs-common.toml and open it in notepad or notepad++ to edit the stuff

**Comment by Alex-the-666** [comment]
^
