### ISSUE TITLE
Log spam from CentipedeHead

### ISSUE THREAD

**Issue by Rutes** [Alex-the-666/AlexsMobs#25]
I'm getting about 50-60 entries per second of the below in my latest.log

`[09Dec2020 18:36:55.027] [Render thread/INFO] [STDOUT/]: [com.github.alexthe666.alexsmobs.entity.EntityCentipedeHead:func_70071_h_:163]: 60.0 / 60.0`

Forge version 35.1.7
alexsmobs-1.0.1

**Comment by CynicalShrew** [comment]
Same here.

**Comment by feandrad** [comment]
Yep
