### ISSUE TITLE
Tameable mobs take half damage from non-player mobs

### ISSUE THREAD

**Issue by Sp00kyTom** [Alex-the-666/AlexsMobs#253]
Raccoons, komodo dragons, grizzly bears, ect. take 50% damage from mob attacks, even in the wild. This bug doesn't apply to non-tameable mobs.

**Comment by Carro1001** [comment]
there are also weird inconsistencies: 

Silverbacks take damage normally

To the relation to the rebalance, i don't think it's that, since non-tameable entities take just damage normally, even the ones who were rebalanced like the gazelle

**Comment by Alex-the-666** [comment]
this was done because vanilla wolves do this
