### ISSUE TITLE
[Bug] Wandering Trader Elephant spawning when Elephant spawns are disabled

### ISSUE THREAD

**Issue by Kisutora** [Alex-the-666/AlexsMobs#256]
**Forge:** release 1.16.5-forge-36.0.46
**Alex's Mobs:** [1.7.1](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs/files/3230693)

I have set elephantSpawnWeight to 0, however Wandering Trader Elephants still spawn.
Could we have a separate option for disabling Wandering Trader Elephants?
![image](https://user-images.githubusercontent.com/22685232/110552052-4bd36500-813f-11eb-9ceb-c5487e3421fe.png)

**Comment by Alex-the-666** [comment]
there is a seperate config for this.
