### ISSUE TITLE
Mobs aren't spawning in previously explored areas

### ISSUE THREAD

**Issue by romaneisbar** [Alex-the-666/AlexsMobs#264]
I recently added this mod into my server however mobs aren't spawning at all. I have tried to reload the chunks and even leave the area and come back but those previously loaded chunks aren't spawning anything.

**Comment by McCullochYO** [comment]
I'm having the exact same problem, only newly generated chunks spawn these mobs.

**Comment by Alex-the-666** [comment]
intended. vanilla only spawns animals rarely after world gen, and mostly on chunk gen. i am not going to change how the game spawns mobs.
