### ISSUE TITLE
New Mobs not spawning in already generated biomes 

### ISSUE THREAD

**Issue by SkullDiamond** [Alex-the-666/AlexsMobs#291]
hello, I need help whit my moded server, I had the alexs-mod since the 1.5.1 version of the mod and when I update it the new version 1.8.0 mobs dont spawn in the biomes that where already generated I have to travel 1000s of blocks. Is that normal ? any way I could fix that?

**Comment by Maalakita** [comment]
Hi, did you get how to fix it? I have the same problem
