### ISSUE TITLE
[FEATURE REQUEST] Disable Minecraft Mobs

### ISSUE THREAD

**Issue by kreezxil** [Alex-the-666/AlexsMobs#292]
Now that your mod provides so much variety, I think it would be awesome if we could disable the default Minecraft mobs.

You could have an easy setting like

B:disable all minecraft mobs=true (default false)
B:disable passive minecraft mobs=false (default false)
B:disable hostile minecraft mobs=true (default true)

And then you could have them either listed individually or have an array of blacklist, where if they are present in the black list they do not spawn. The blacklist would naturally apply if they were not disabled the easy way above. I see a new World of ... something in my future. :)

**Comment by SalehGrey** [comment]
> Now that your mod provides so much variety, I think it would be awesome if we could disable the default Minecraft mobs.
> 
> You could have an easy setting like
> 
> B:disable all minecraft mobs=true (default false)
> B:disable passive minecraft mobs=false (default false)
> B:disable hostile minecraft mobs=true (default true)
> 
> And then you could have them either listed individually or have an array of blacklist, where if they are present in the black list they do not spawn. The blacklist would naturally apply if they were not disabled the easy way above. I see a new World of ... something in my future. :)

I also think disabling certain features/items would be nice, similar to Quark.

**Comment by kreezxil** [comment]
@SalehGrey what features/items provided by Alex's Mobs do you think override something that exists in Minecraft vanilla? I'm curious to know. I only perceived a surface feature.

**Comment by MarioSMB** [comment]
For the record, you are able to disable specific mobs with the In Control mod: https://www.curseforge.com/minecraft/mc-mods/in-control  
The way I see it is, this mod is attempting to expand upon the vanilla gameplay in unique ways, so options to disable vanilla features would be a little out of scope. That is just my opinion though, it is up to the developers how they want to handle this.

**Comment by Alex-the-666** [comment]
^

**Comment by kreezxil** [comment]
thanks mario, that mod isn't always immediately ported preceding any of
alex's mods.
