### ISSUE TITLE
[Request] Add scaling to different entities for ItemTabIcon

### ISSUE THREAD

**Issue by noolaan** [Alex-the-666/AlexsMobs#309]
I understand that tab icons are *only* used for advancements and the creative inventory tab, but this feature is extremely useful for modpack makers. I can use these tab icons inside of FTB Quests and display entities perfectly, with one caveat. The scaling of entities don't fit inside of the icon very well.

If I try displaying the Wither or the Ender Dragon, it is gigantic. I know it has no use for your mod, but maybe as a hidden feature or as a separate core mod this functionality would be amazing. This is what it currently looks like inside of FTB Quests:
![image](https://user-images.githubusercontent.com/32991023/112405290-3c235700-8ccf-11eb-8599-1c32d519051c.png)

**Comment by Alex-the-666** [comment]
should be in 1.9.0 as the "DisplayMobScale" float in the item tag.

**Comment by noolaan** [comment]
Amazing! Thank you so much.
