### ISSUE TITLE
Lava is... Water?

### ISSUE THREAD

**Issue by MarioCraftLP** [Alex-the-666/AlexsMobs#31]
Hi,
I'm making a mod pack with 100+ Mods and AlexsMobs is one of them. But when I start with the mod, Lava looks like water. Idk. The game isn't crashing or doesn't give me an error message. It's not a game breaking bug, but I don't like it.
(My English is very bad so...)
<img width="380" alt="Screenshot 2020-12-11 205757" src="https://user-images.githubusercontent.com/75859777/101949236-92263000-3bf3-11eb-96b6-c71a62849476.png">

**Comment by Carro1001** [comment]
Does that happen only with that shader? have you tried other shaders?

**Comment by MarioCraftLP** [comment]
Ok, it's the shader. But what does the mod change about the lava that the shader no longer works? (I am using the SEUS Renewed 1.0.1 shader)

**Comment by KillNagaThul** [comment]
a fix is coming soon

**Comment by Alex-the-666** [comment]
^

**Comment by DavidZabaleta** [comment]
I'm using the version 1.18.6 of the mod and the problem with the lava still going on using the shaders SEUS

**Comment by Carro1001** [comment]
have you tried enabling the compatibility setting in the alexsmobs config? that might solve the issue

**Comment by DavidZabaleta** [comment]
I enable this one but it didn't work

![image](https://user-images.githubusercontent.com/31398801/195521175-cfba4527-30ac-406f-8f7b-7f23019fb230.png)

**Comment by ThoBekMic** [comment]
I'm also having this exact issue. It's specifically with Enigmatica 8. I added only OptiFine and SEUS Renewed shaders. I also enabled the shadersCompat setting but to no avail.
