### ISSUE TITLE
Multi-part mobs are buggy in the new stable version of forge. [1.16.5-36.1.0]

### ISSUE THREAD

**Issue by Mikeliro** [Alex-the-666/AlexsMobs#312]
[crash-2021-03-25_13.31.53-server.txt](https://github.com/Alex-the-666/AlexsMobs/files/6207134/crash-2021-03-25_13.31.53-server.txt)

**Comment by Alex-the-666** [comment]
issue seems to be with the advanced compass mod. dlovin.advancedcompass.events.EntityEvents.onEntityEnter
