### ISSUE TITLE
[1.16.5] Seemingly random crash 

### ISSUE THREAD

**Issue by NillerMedDild** [Alex-the-666/AlexsMobs#314]
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/1814

Seemingly random crash with Alex's Mobs in the stacktrace. It may be useful information that we have disabled cockroach spawning completely, by setting weight to 0 and the `cockroach_spawns.json` to `{"biomes": []}`

> 
> 
> **Modpack version**
> [0.4.5] singleplayer, with yung's better caves kept in and COFH-Core updated to 1.2.1 to address the looting enchantment issue.
> 
> **Describe the bug**
> A random CTD. What I was doing when it happened (which may be unrelated): I had just opened the gui of a Thermal Expansion Fluid Cell that was mostly full of milk, and my mouse was over a cake that I had in my inventory. Are these related to the crash? I doubt it!
> 
> I thought cockroaches weren't supposed to spawn in the overworld?
> 
> **Logs**
> [crash-2021-03-25_14.28.32-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/6207967/crash-2021-03-25_14.28.32-server.txt)

### Versions
- alexsmobs-1.8.0
- Forge-1.16.5-36.1.0

**Comment by Alex-the-666** [comment]
Seems like the issue is with whatever mod adds a fluid tagged as "redstone". This crash would've happened if the entity was a cockroach, vanilla zombie, etc. just anything that could load the chunk

**Comment by NillerMedDild** [comment]
Cool, thanks for explaining!
