### ISSUE TITLE
Kangaroos don't stay "staying"

### ISSUE THREAD

**Issue by BarionLP** [Alex-the-666/AlexsMobs#318]
My Kangaroos don't stay in staying mode after I reloaded the chunks

**Comment by tweakbsd** [comment]
I have 2 possible fixes for this issue.
 
In EntityKangaroo.java add a DataManager variable for the "forcedSit" member variable will do the trick. Or simply add the following line in 
void readAdditional(); method:

after this line:
`
this.setSitting(compound.getBoolean("KangarooSitting"));
`

add that line:
`
this.forcedSit = this.isSitting(); 
`

Sorry for not doing a PR but I don't have this repository cloned / forked at the moment.
