### ISSUE TITLE
Is this the right place for suggestions?

### ISSUE THREAD

**Issue by ShamblerDK** [Alex-the-666/AlexsMobs#320]
I see that you have mosquitos in the mod. Well, the name mosquito implies the existence of a much larger mosquito called "El Mosco". Could you add that as some kind of boss? Maybe kill enough regular mosquitos for rare drop items, which can be used to summon El Mosco :P

**Comment by NEFFLEAFF** [comment]
![image](https://user-images.githubusercontent.com/69360168/113068372-6b2c4380-917b-11eb-99fa-0734dc1763cc.png)

**Comment by Carro1001** [comment]
![image](https://user-images.githubusercontent.com/47877096/113068389-97a08980-9194-11eb-9f42-8aebf7adeb14.png)

**Comment by NEFFLEAFF** [comment]
do you have a even larger image

**Comment by Carro1001** [comment]
no

**Comment by NEFFLEAFF** [comment]
sad

**Comment by ShamblerDK** [comment]
That's PERFECT! It looks so damn scary xD

**Comment by Carro1001** [comment]
its in the mod yknow

**Comment by ShamblerDK** [comment]
Oh, I didn't know. I'll close the issue.
