### ISSUE TITLE
Monkey and gorilla not spawning

### ISSUE THREAD

**Issue by Cinder474** [Alex-the-666/AlexsMobs#323]
I have my house in the jungle and when I went looking for monkeys and gorilla I couldn't find any I looked around for a long time still didn't see any. I made a different world with a jungle biome to see if the mod works and I found monkeys there but still can't find any in my other world. Is there a reason why I can't find any or its not working?

**Comment by Alex-the-666** [comment]
they spawn. create a world of just jungle biome and see em everywhere
