### ISSUE TITLE
Enhancement : Penguins

### ISSUE THREAD

**Issue by SalmonSmacker** [Alex-the-666/AlexsMobs#336]
They would spawn on Snowy Biomes and frozen ocean biomes, mostly on the flatter parts of the ice. They are prey to polar bears, but they prey on fish, which they would kill then grab the fish item. When they have a fish item in their mouth, they would eat it. They would spawn in groups and walk in groups but if a member of the colony is hit all of the penguins will flee into the water or on ice. Extra feature:sliding around on ice

**Comment by Alex-the-666** [comment]
this is not the place for suggestions
