### ISSUE TITLE
straddler and stradpoles crash

### ISSUE THREAD

**Issue by superdude808** [Alex-the-666/AlexsMobs#348]
so stradlers crash the game because of some interaction with stradpoles being both an item and a living entity at the same time 

here's the crash log https://pastebin.com/93RsLifJ

**Comment by IvorAmlug** [comment]
Have the same crash on my server...

**Comment by RealBitslayn** [comment]
I have this issue as well

**Comment by thenoble1** [comment]
+1

**Comment by bigbull646** [comment]
Same here, they keep on randomly crashing my game.

**Comment by MokahTGS** [comment]
Our server crash: https://pastebin.com/meFq7MSH

**Comment by MarioSMB** [comment]
Another crash, looks like mine was from arrows hitting them: https://paste.ubuntu.com/p/CgGWYz5R3D/
