### ISSUE TITLE
Config not working

### ISSUE THREAD

**Issue by NixityNull** [Alex-the-666/AlexsMobs#35]
The biome config does not seem to effect which biome the mobs spawn in

**Comment by Carro1001** [comment]
Can confirm, the biome config does not affect the biomes for mobs to spawn at the moment, just removed crimson mosquito spawns from the crimson forest and they still spawned there instead of the nether biome i set, same with endergrades

**Comment by NixityNull** [comment]
It's still not working for me. Should delete and reedit the config file?
