### ISSUE TITLE
Failed to load mod correctly

### ISSUE THREAD

**Issue by DRAGNIZ** [Alex-the-666/AlexsMobs#355]
[crash-2021-04-17_02.29.51-fml.txt](https://github.com/Alex-the-666/AlexsMobs/files/6327261/crash-2021-04-17_02.29.51-fml.txt)

**Comment by Carro1001** [comment]
You might wanna update forge and try again, you're using a real old forge version for 1.16.5

**Comment by DRAGNIZ** [comment]
Ok got it. Thanks!
