### ISSUE TITLE
Texture bug with grizzly bear flag

### ISSUE THREAD

**Issue by HightWolt** [Alex-the-666/AlexsMobs#359]
![2021-04-18_09 34 09](https://user-images.githubusercontent.com/63906232/115136836-000fb780-a02b-11eb-8d07-a7c77dd22757.jpg)
version 1.16.5
last mod version
The language in the game is Russian
UPD: my mod list
![mod list](https://user-images.githubusercontent.com/63906232/115137910-77484a00-a031-11eb-9711-1466c62f9cf9.PNG)

**Comment by tikiMC** [comment]
do you have refined storage installed?
 I'm experiencing the same issue and it seems to be refined storage causing the issue for god knows why.

**Comment by HightWolt** [comment]
> do you have refined storage installed?
> I'm experiencing the same issue and it seems to be refined storage causing the issue for god knows why.

Not.
I have AE2

**Comment by tikiMC** [comment]
hmmmmmm try taking ae2 maybe both ae2 and refined cause this issue.

**Comment by HightWolt** [comment]
No, AE 2 is not to blame

> hmmmmmm try taking ae2 maybe both ae2 and refined cause this issue.

**Comment by mcaskilSeed** [comment]
hi russian guy

**Comment by Alex-the-666** [comment]
mowzies mobs bug
