### ISSUE TITLE
I dont't like fantasy mobs

### ISSUE THREAD

**Issue by mcaskilSeed** [Alex-the-666/AlexsMobs#369]
hey dev of Alex's mob, can you adding the alexs mob version without fantasy mob to curseforge, thanks

**Comment by QuerrixTU** [comment]
Lol Minecraft adding a lot of fantasy mobs what the problem xD

**Comment by mcaskilSeed** [comment]
> Lol Minecraft adding a lot of fantasy mobs what the problem xD

i don't like Alex's mob fantasy mob

**Comment by Carro1001** [comment]
You can literally just disable them by setting their spawn weight to 0 in the config, and this isn't a place for suggestions.

**Comment by mcaskilSeed** [comment]
> You can literally just disable them by setting their spawn weight to 0 in the config, and this isn't a place for suggestions.

how to disabled it? there was no config
