### ISSUE TITLE
game crashes and says i have "exception in server tick loop.

### ISSUE THREAD

**Issue by xZaino** [Alex-the-666/AlexsMobs#371]
running this singleplayer and not running it on a server. using 10 gb of ram allocated. little overkill but its fine i have some to spare. here is crash report. removing the mod seems to help and have no problems after that but i do like this mod and want to keep it. using the latest citadel and alexs mobs. 
[crash-2021-04-25_21.09.21-server.txt](https://github.com/Alex-the-666/AlexsMobs/files/6374715/crash-2021-04-25_21.09.21-server.txt)

**Comment by Alex-the-666** [comment]
> pam.pamhc2crops.entities.ai.MoreTemptation.<init>

Is a pams harvest craft bug, not alex's mobs.
