### ISSUE TITLE
Drop bear spawning on blocks they shouldn't

### ISSUE THREAD

**Issue by Lumiwrath** [Alex-the-666/AlexsMobs#380]
They spawn on glass and half slabs in nether

**Comment by Lumiwrath** [comment]
Problem was found during creation of zombie pigmen farm and is currently immensely affecting zombie pigmen spawns

**Comment by Alex-the-666** [comment]
Drop bears will spawn on any ground block normal mobs can. They just leap up to the ceiling after spawning.
