### ISSUE TITLE
Mod is completely unplayable or incompatible with other mods. I tried installing it but it keeps kicking me out of the game for reasons I don't know. 

### ISSUE THREAD

**Issue by TerranE5** [Alex-the-666/AlexsMobs#39]

**Comment by TerranE5** [comment]
So I'll make it clear. I downloaded this mod cause it seemed like a cool addition in my world. But once I added it in my mods, It shows this black screen with a note saying "incompatible" sign in it (I can't remember the exact description). Is the mod not compatible with other mods? Can you fix it?

**Comment by Carro1001** [comment]
Could you give the debug.log file that appears after that happens?

**Comment by TerranE5** [comment]
Nvm, it was a mistake on my part. Turns out I just forgot to update citadel
to 1.5.3. The mod is working properly now. Sorry fr the late reply, I don't
usually receive emails like this. Thanks for the reminder.
