### ISSUE TITLE
Can't Control an Eagle Wearing a Falconry Hood with Mahou Tsukai Installed

### ISSUE THREAD

**Issue by JohnG112358** [Alex-the-666/AlexsMobs#392]
I can't control an eagle with a falconry hood on.  I'm able to put the falconry hood on the eagle and pick it up with the falconry glove, but when I try to launch it it just kinda falls to the ground in the flying animation.  I do get taken to third person perspective, but I am still controlling my character, not the eagle.  It works just fine when I take off the falconry hood and launch the eagle at another mob.

There was no information in the crash logs or the logs.  I am playing a large custom modpack, so it might be an incompatibility with another mod.  Forge version was 36.1.16, Alex's mobs 1.10.0.

**Comment by JohnG112358** [comment]
Edit: After some testing, I can confirm the problem mod is Mahou Tsukai.  I was able to control the eagle just fine with it uninstalled, but one I installed it I experienced the issue described above.  I was using the latest version of the mod, 1.30.4

**Comment by stepsword** [comment]
Yea this is my fault - 1.30.5 of mahou should fix this. sorry bout that! :)
