### ISSUE TITLE
Roadrunners, rattlesnakes and tarantula hawks absent from deserts

### ISSUE THREAD

**Issue by blaboup** [Alex-the-666/AlexsMobs#399]
Rattlesnakes and roadrunners are absent in my world (otherwise vanilla) from deserts. They only show up in badlands. 
Tarantula hawks simply do not spawn. 
However gusters spawn just fine in deserts after rain / thunderstorms.

**Comment by Alex-the-666** [comment]
try deleting your biome spawn jsons in the mod's config folders.
