### ISSUE TITLE
(presumably) Flies are causing the game to crash

### ISSUE THREAD

**Issue by slim-shady6** [Alex-the-666/AlexsMobs#40]
It appears that flies are causing the game to crash according to the crash report below:

[crash-2020-12-13_21.43.33-server.txt](https://github.com/Alex-the-666/AlexsMobs/files/5684672/crash-2020-12-13_21.43.33-server.txt)

specifically the lines:

if (!(creatureIn.getNavigator() instanceof GroundPathNavigator) && !(creatureIn.getNavigator() instanceof FlyingPathNavigator)) {
         throw new IllegalArgumentException("Unsupported mob type for TemptGoal");
      }

removing the mod stops the crashing.

**Comment by Alex-the-666** [comment]
This isn't caused by our mod. 
The error is stemming from "enemeez.simplefarming.entities.ai.MoreTemptation.<init>".  Please report this issue to the mod with modid "simplefarming". They should not assume that every animal has one of 2 vanilla pathfinding systems.

**Comment by viveleroi** [comment]
This occurs with Pam's Harvestcraft too. I've reported it and they just blame this mod. Unfortunately, I've had to remove this mod as HC is more important to my pack.
