### ISSUE TITLE
Eagle Falcon Hood crashes the game

### ISSUE THREAD

**Issue by SalmonSmacker** [Alex-the-666/AlexsMobs#401]
Every time I try to control a falcon with the hood, I get crashed out and this is what I see.

The game crashed whilst unexpected error
Error: java.lang.ClassCastException: com.github.alexthe666.alexsmobs.entity.EntityBaldEagle cannot be cast to net.minecraft.entity.player.PlayerEntity

**Comment by Alex-the-666** [comment]
gonna need a full log

**Comment by SalmonSmacker** [comment]
I made a pastebin but I'm not sure you will even click it so here it is. https://pastebin.com/sK17eHt1

**Comment by Alex-the-666** [comment]
> ReflectionNecklaceClientEvents.onOverlayRender
Caused by relics mod
