### ISSUE TITLE
Config settings not removing spawns

### ISSUE THREAD

**Issue by Zygus42** [Alex-the-666/AlexsMobs#405]
I'm attempting to remove certain animals from my world spawn.  I had assumed that if I set the "negate" values to True in all the categories for that mob it would cause them to not spawn anywhere, but not so.  Example emu_spawns.json:

[emu_spawns.json.txt](https://github.com/Alex-the-666/AlexsMobs/files/6440375/emu_spawns.json.txt)

Still spawning emus.

This is using version 1.9.1, but I haven't seen anything in the changelogs for later versions to indicate that this has been fixed.

Am I incorrect in my assumption that setting Negate to True cancels that spawn ?  Or is this a bug ?

**Comment by Alex-the-666** [comment]
thats not how it works at all. change the emu spawn weight to 0 for this.
