### ISSUE TITLE
Hooded Hawk Crashes The Game

### ISSUE THREAD

**Issue by Teldenes** [Alex-the-666/AlexsMobs#410]
When i try to launch a hooded hawk out of my hand the game freezes and crashes. Im playing 1.16.5

[crash-2021-05-08_22.16.44-client.txt](https://github.com/Alex-the-666/AlexsMobs/files/6446499/crash-2021-05-08_22.16.44-client.txt)

**Comment by Alex-the-666** [comment]
issue is with the Tetra mod.
