### ISSUE TITLE
I cant Load The Alexs Mob

### ISSUE THREAD

**Issue by mcaskilSeed** [Alex-the-666/AlexsMobs#411]
![image](https://user-images.githubusercontent.com/78537050/117568947-0a483300-b078-11eb-9ef7-f4e828216cef.png)
What Happened?

**Comment by Redtiger4719** [comment]
Same thing happened to me. I looked through the crash report and I think the issue had something to do with the Cachalot Whale

**Comment by JamesJamestar** [comment]
I seem to have the same problem, aswell.
"Alex's Mobs (alexsmobs) has failed to load correctly"
"java.lang.IllegalAccessError: no such constructor: com.github.alexthe666.alexsmobs.entity.EntityCachalotWhale.<init>(EntityType,World)void/newInvokeSpecial"
