### ISSUE TITLE
[1.16.4] Cenipede server log spam v1.0.1

### ISSUE THREAD

**Issue by Cixon** [Alex-the-666/AlexsMobs#42]
**Context:** Was just building with worldedit in a snowy mountain biome when I noticed my console being spammed.

**Citadel Version:**  v1.5.3
**Forge Version:** v35.0.17

![Screenshot (545)](https://user-images.githubusercontent.com/69068153/102029297-8bbec200-3d73-11eb-8035-aa4d2553a49d.png)

Log:
[latest.log](https://github.com/Alex-the-666/AlexsMobs/files/5685881/latest.log)

**Comment by Inpaladin** [comment]
seconding this, this is a massive bug.

**Comment by Alex-the-666** [comment]
fixed
