### ISSUE TITLE
Attacking yourself as an eagle crashes the game.

### ISSUE THREAD

**Issue by Booshroom** [Alex-the-666/AlexsMobs#420]

**Comment by Alex-the-666** [comment]
how were you able to attack yourself as an eagle? i cant seem to replicate that behavior

**Comment by Booshroom** [comment]
I just left clicked myself and then this happened
![image](https://user-images.githubusercontent.com/83992394/118203990-146c8780-b412-11eb-94bf-e42ad7a8d9ab.png)

**Comment by Booshroom** [comment]
Here's a video
https://streamable.com/o82pap
