### ISSUE TITLE
Clicked "Create New World", Crashed. java.lang.NullPointerException: mouseClicked event handler

### ISSUE THREAD

**Issue by zndrmn** [Alex-the-666/AlexsMobs#444]
Once I clicked "Create New World", the game crashed and here's the crash report.
Sorry for the huge mod list, also my pc is ass for a lack of better words
https://gist.github.com/zndrmn/8165cc82338dfb138260765b0d64d9b7#file-crash-2021-05-18_20-49-24-client-txt

**Comment by Alex-the-666** [comment]
fixed
