### ISSUE TITLE
Hooded Eagle Crashes when launched.

### ISSUE THREAD

**Issue by TenTonSkeleton** [Alex-the-666/AlexsMobs#449]
Every time I try launching a tamed hooded eagle, I crash, I have mods on, but no Optifine.

**Comment by Alex-the-666** [comment]
crashlog?

**Comment by TenTonSkeleton** [comment]
I believe I found the issue, it works with others, and I was on a large modpack, so maybe it was just mod incompatibility. I'll let you know if the issue comes up again.
