### ISSUE TITLE
Straddlers too strong.

### ISSUE THREAD

**Issue by SolutionMe** [Alex-the-666/AlexsMobs#463]
Straddlers are too strong. Nerf their firing rate and or their accuracy. Basalt Starts in the Nether are too difficult because of them.

**Comment by AidanCorgi4556** [comment]
Just get good nerd this isnt an issue this is a suggestion. Just fucking learn to play the game and you wont have issues. 
![image](https://user-images.githubusercontent.com/83181250/120885805-1d084600-c5eb-11eb-9f7f-cf6b1321ead9.png)

**Comment by SolutionMe** [comment]
Editing their spawn rates to be lower was a good band-aid solution on my part, but that creature is flawed. It is tankier than skeletons while shooting quicker than them, and their projectile can fight back and you can even swing on them unintentionally if you meant to hit the Straddler itself. As I stated it also doesn't help that you have to fight them in Basalt Deltas which pretty much outright stops you from approaching them.

You can obviously just set up a nether portal elsewhere and try again, or craft a bow to clear them out before they respawn again, but this won't really fix the issue at hand with the Straddler itself. No other Nether creature is as overkill as this one, even the others included in this mod.
