### ISSUE TITLE
Tarantula hawk breeding bugs

### ISSUE THREAD

**Issue by CrestMemepaste** [Alex-the-666/AlexsMobs#470]
After taming 2 hawks and giving them fermented spider eye to begin the breeding process, they either kill or do not bury the spider they target, regardless of whether the spider is hostile to the player or not. 
If a hawk does manage to bury a spider after being bred, the majority of the time a larva will not be spawned when the spider dies. 
Larva also despawns despite the chunk it is in never being unloaded.

**Comment by sauphle** [comment]
I do not have an answer but I do want to add that the spider idle sound affects still play after the spider has died.
