### ISSUE TITLE
Crashing on Forge 1.16.5

### ISSUE THREAD

**Issue by jaehyuun** [Alex-the-666/AlexsMobs#479]
i'm a huge noob when it comes to reading crash reports but i was just playing in singleplayer and i started flying in creative in a random direction and my game suddenly crashed. i looked at the crash report and the first mod i could see was AlexsMobs that's why i'm posting here, i'm really sorry if the issue is not related to this mod or something

i'd appreciate any help i'm really lost on what to do, thank you

[crash log](https://pastebin.com/raw/R5vN21TE)

(edit)
i also just got this error on a server:

`[Server] Worker-Main7/ERROR [minecraft/TagCollectionReader]: Couldn't load block tag alexsmobs:lobster_spawns as it is missing following references: #forge:stone (from alexsmobs-1.10.1.jar)`

**Comment by AidanCorgi4556** [comment]
I see you only have around 2 gigs of ram allocated. Upgrade it to 3 gigs and it might fix it easily. If youre using a launcher you can find the java memory settings in the instances settings but if youre using the minecraft launcher by going here and changing -Xmx2G- to -Xmx3G- you can also do it as megabytes by changing the suffix from G to M. This'll also make the game run better.![image](https://user-images.githubusercontent.com/83181250/121890046-3495ac00-cd1a-11eb-835b-89e39cdb6f58.jpeg)

**Comment by Alex-the-666** [comment]
fixed
