### ISSUE TITLE
My animal suggestions

### ISSUE THREAD

**Issue by Rxann** [Alex-the-666/AlexsMobs#482]
Hello,
I had some ideas for some mods and I didn't know where to submit them so I am going to do it here.

1.Ducks and Geese. I think that ducks and geese would be good because they would populate the water areas with some more wildlife.

2. Racoons. I think racoons would be good because they can add some more animals to the woods areas.

If I didn't submit these in the right place I am very sorry.

I really love your mod!

**Comment by AidanCorgi4556** [comment]
You absolute buffoon. You do realize that github is for GLITCHES AND BUGS? THE ONLY BUG HERE IS THE *FLY* IN YOUR EMPTY SKULL BUMPING AROUND PRODUCING THESE HORRIBLE SUGGESTIONS. You asked for ducks and geeses. Not a good suggestion but whatever… THEN FUCKING RACCOONS? Have you even played the mod? Hell have you even turned on your computer? What the absolute hell dude? Im so dissapointed in you even though you’re an absolute stranger. You have completely misused the github and I am fucking melting. RA-FUCKING-COONS??? Theyre AREADY IN THE GODDAMN MOD??!!! ARE YOU BLIND???? 

Kindly,
AidanCorgi

**Comment by AidanCorgi4556** [comment]
No offense

**Comment by Rxann** [comment]
alr then

**Comment by 1235788998753568hfjfu** [comment]
untitled duck mod
