### ISSUE TITLE
Snow Leopard and Tasmanian Devil causing ticking entity (want to disable spawning)

### ISSUE THREAD

**Issue by hippytea** [Alex-the-666/AlexsMobs#499]
A modded server I'm running started crashing when loading into the server because of the snow leopard and tasmanian devil. I use COFH Core to kill them but it seems to be a bandaid fix and was wanting to turn off the spawns. Could I get some help with doing that? Thanks! 

Logs: https://pastebin.com/H0vByhPL

**Comment by Alex-the-666** [comment]
uninstall performant
