### ISSUE TITLE
Worm boss crash, on summoning.

### ISSUE THREAD

**Issue by KKotik** [Alex-the-666/AlexsMobs#501]
I dropped the item in the void, saw a glance of epic work and got crashed sadly. On the crash it's say smth related with sounds. Charmonium feels kinda sus with it. 
[crash-2021-06-22_15.50.14-client.txt](https://github.com/Alex-the-666/AlexsMobs/files/6694332/crash-2021-06-22_15.50.14-client.txt)

**Comment by Alex-the-666** [comment]
Seems like this is a bug on charm's end.
