### ISSUE TITLE
Void Worm Idle Sound Lasts Too Long

### ISSUE THREAD

**Issue by LunarPhobos** [Alex-the-666/AlexsMobs#510]
The sound, void_worm_idle_2, is 30 seconds long the sound ends up lingering for way too long, is this intentional?

**Comment by Alex-the-666** [comment]
re-install the mod

**Comment by LunarPhobos** [comment]
Persists on version 1.11.1.
https://user-images.githubusercontent.com/76231975/124029766-1aff9000-d9bb-11eb-9d31-f3d332f47c85.mp4
