### ISSUE TITLE
Crocodile and Snapping turtle spawn in wrong biomes

### ISSUE THREAD

**Issue by NixityNull** [Alex-the-666/AlexsMobs#519]
I ended up having to disable these mobs because despite me not doing anything to change their config from swamp only, they naturally spawn in all biomes, even cold ones! Crocodiles generally spawn near water and Snapping turtles are more likely to spawn near sand, but otherwise they are completely unrestricted.

**Comment by Wedge1453** [comment]
I second this

**Comment by Alex-the-666** [comment]
fixed
