### ISSUE TITLE
Compatibility with other mob mods

### ISSUE THREAD

**Issue by ronangamero** [Alex-the-666/AlexsMobs#528]
So I'm playing using your mod and some other mods that add animals, like wizard's animals, exotic birds, and aquaculture 2. I noticed that animals are quite rare spawning and Alex's animals are even more rare. Is there any way to make mobs spawn more often?

I'm playing mc 1.16.5

**Comment by AidanCorgi4556** [comment]
Go into the citadel config and change the last number from 1.0 to anything else (2.0 is two times more and so on)
