### ISSUE TITLE
Elephants require multiple blossoms to breed

### ISSUE THREAD

**Issue by SkipSnap** [Alex-the-666/AlexsMobs#549]
Hello there, I just was wondering, I have 2 elephants that won’t breed. I tested in a creative world if this was some kind of glitch, but they did eventually breed after multiple blossoms. Also, they only stay in love mode for a few seconds, unlike vanilla mobs. Is this a glitch or intentional? Thanks!

**Comment by Carro1001** [comment]
Yea their breeding is definitely kinda broken

**Comment by SkipSnap** [comment]
Will that be fixed in the next changelog?
