### ISSUE TITLE
Mobs still spawn even when gamerule "disable mob spawning" is set to true. 

### ISSUE THREAD

**Issue by Tanner201X** [Alex-the-666/AlexsMobs#553]
I've seen raccoons, crocodiles, flies and crows spawn even when mobs shouldn't be spawning.

**Comment by DiamondDemon123** [comment]
Did they spawn? or did they spawn when the world was created.

**Comment by Tanner201X** [comment]
> Did they spawn? or did they spawn when the world was created.

They spawned when the world was created, and they still continue to spawn.

**Comment by chandler05** [comment]
Might be a vanilla bug: https://bugs.mojang.com/browse/MC-118347
