### ISSUE TITLE
Cachalot failed whit Waila and Toro Health mods.

### ISSUE THREAD

**Issue by ricardo-jn** [Alex-the-666/AlexsMobs#556]
The WAILA is used to see each item and mob in the game, it also includes life. The TORO HEALTH is used to see a health bar for each mob; including a small skin of it. All the mobs in your mod pack work correctly with these aforementioned mods (WAILA and TORO HEALTH) except the cachalot.

![2021-07-12_23 09 28](https://user-images.githubusercontent.com/87350218/125384288-b2bf8f80-e366-11eb-8b78-18a40f36ce3e.png)
![2021-07-12_23 09 47](https://user-images.githubusercontent.com/87350218/125384289-b2bf8f80-e366-11eb-9fdc-24a9e31f745d.png)
![2021-07-12_23 11 10](https://user-images.githubusercontent.com/87350218/125384290-b3582600-e366-11eb-8f57-a1b78dcf1dec.png)
![2021-07-12_23 11 27](https://user-images.githubusercontent.com/87350218/125384293-b3582600-e366-11eb-93c2-e0d45ee050a9.png)
![2021-07-12_23 11 45](https://user-images.githubusercontent.com/87350218/125384296-b3f0bc80-e366-11eb-99bf-f6516ca00391.png)

**Comment by Mike-U5** [comment]
I've experienced the same issue.
