### ISSUE TITLE
server crash ticking entity

### ISSUE THREAD

**Issue by stanlexgreenson** [Alex-the-666/AlexsMobs#58]
So, I was whatching a pair of myrmex aproaching a crocodile and when they started fighting server crashed, what a titanic fight. I'm kind of new reporting issues, if I missed any other info or step on doing it, please let me know.

Minecraft 1.16.4
Forge 35.1.10
alexsmobs-1.1.0
iceandfire-2.1.4-1.16.4
[crash-2020-12-14_15.42.14-server.txt](https://github.com/Alex-the-666/AlexsMobs/files/5691525/crash-2020-12-14_15.42.14-server.txt)

**Comment by Daejangnamu** [comment]
yes 

-- Entity being ticked --
Details:
	Entity Type: alexsmobs:crocodile (com.github.alexthe666.alexsmobs.entity.EntityCrocodile)
	Entity ID: 26731968
	Entity Name: Crocodile
	Entity's Exact location: 114.18, 62.12, -7657.38
	Entity's Block location: World: (114,62,-7658), Chunk: (at 2,3,6 in 7,-479; contains blocks 112,0,-7664 to 127,255,-7649), Region: (0,-15; contains chunks 0,-480 to 31,-449, blocks 0,0,-7680 to 511,255,-7169)
	Entity's Momentum: -0.18, -0.03, 0.03
	Entity's Passengers: [EntityMyrmexSoldier['Myrmex Soldier'/26696261, l='ServerLevel[world]', x=111.36, y=62.51, z=-7658.51]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}

**Comment by aziz2077** [comment]
Same problem

https://pastebin.com/dE6ea4Kw

**Comment by Alex-the-666** [comment]
should be fixed in ice and fire 2.1.5
