### ISSUE TITLE
Shaders

### ISSUE THREAD

**Issue by KillNagaThul** [Alex-the-666/AlexsMobs#59]
does not work with shaders, lava looks like water
I'm using seus renewed and Realismmats resource pack

**Comment by Bright625** [comment]
Can confirm.

**Comment by LuamLeite** [comment]
Can also confirm. It makes lava just like water in SEUS.

**Comment by Filomaster** [comment]
Can also confirm. Most of the shaders work fine, but in SEUS (tested on reneved and older version) lava looks like water
![2020-12-18_13 06 43](https://user-images.githubusercontent.com/25264110/102612952-f5ebb400-4131-11eb-8545-5806a5bd4bf6.png)
![2020-12-18_13 06 51](https://user-images.githubusercontent.com/25264110/102612958-f8e6a480-4131-11eb-944d-ef90fd96c4ea.png)

**Comment by Syampuuh** [comment]
Adding onto this, it doesn't seem like lava vision makes lava semi-translucent at all with any form of shaders, it just completely hides it, regardless of lavaVisionOpacity configuration setting.

**Comment by MarioCraftLP** [comment]
Can confirm.

**Comment by GatoLeyo** [comment]
I dont even have shaders, just optifine installed and the lava is completely invisible which makes the effect more harmful than helpful sometimes. I also tried putting different values on the config file about the opacity.

**Comment by Alex-the-666** [comment]
I added a config option to fix this in the next version.

**Comment by DefinedAscent** [comment]
Just tested with SEUS PTGI 2.1 and edited the config and the issue still persists. Lava looks like water.

**Comment by JianlingRemix** [comment]
The problem persists after shaderCompact is set to true, with mod version 1.18.6
