### ISSUE TITLE
Alex's mobs crashes after apotheosis temptation enchantment

### ISSUE THREAD

**Issue by SpinoFTW** [Alex-the-666/AlexsMobs#595]
My server kept crashing because of this until I 
[message.txt](https://github.com/Alex-the-666/AlexsMobs/files/6951457/message.txt)
removed Alex's mobs and it work

**Comment by Alex-the-666** [comment]
> pam.pamhc2crops.events.TemptationTask.onEntitySpawn

bug caused by pam harvestcraft
