### ISSUE TITLE
Crocodile spawn in incorrect biomes

### ISSUE THREAD

**Issue by Rozarke** [Alex-the-666/AlexsMobs#597]
i've seen crocodiles on plains multiple time i tried without other world gen or biome mods and crocs still spawn on plains

**Comment by JIgglyJaded** [comment]
they spawn in deserts too, i spawned in one and 2 crocodiles were right next to me.

**Comment by enginutku36** [comment]
I also have the same problem but with crocodiles there are emus, gazelles and kangaroos. They are always together and I have seen them in plains, deserts and savannas.

**Comment by Rozarke** [comment]
i've just seen crocodiles in snowy toundra.

**Comment by AidanCorgi4556** [comment]
Make sure to delete your config so it reloads
