### ISSUE TITLE
Ticking Entity/Stock Overflow Error

### ISSUE THREAD

**Issue by LilAngelicKitty** [Alex-the-666/AlexsMobs#604]
A huge issue my boyfriend and I faced was that renaming a mob (or at least in our case the Tasmanian Devil) causes a server crash and the "Stock Overflow Error" aka a ticking entity and the server becomes unplayable. We had this issue before and had to restart our world from scratch but just a warning to anyone out there. To fix it we had to kill our beloved pet within the 30 or so seconds the server gives us before crashing </3

**Comment by chandler05** [comment]
Can you attach the crash report?

**Comment by LilAngelicKitty** [comment]
![C7570762-3632-43DD-A93B-FC7B3669AB00](https://user-images.githubusercontent.com/88999458/129592993-9df8dcf9-650b-4527-9751-51daa1ba7d63.png)

**Comment by LilAngelicKitty** [comment]
![CEA69475-3AA4-4E36-8C6D-EC8E6CE171E6](https://user-images.githubusercontent.com/88999458/129593162-0cf24785-bd67-456e-8fcc-e12b704e5c5f.png)

**Comment by LilAngelicKitty** [comment]
(We fixed it by killing him but this is just a heads up to anyone else)

**Comment by chandler05** [comment]
It'd probably be more helpful for solving this issue to attach the actual crash report file if you can do that.

**Comment by Alex-the-666** [comment]
performant issue
