### ISSUE TITLE
Centipedes spam server logs

### ISSUE THREAD

**Issue by Cynderblood** [Alex-the-666/AlexsMobs#61]
Whenever there's a centipede alive somewhere it spams the servers logs and console with:

`[Server thread/INFO] [STDOUT/]: [com.github.alexthe666.alexsmobs.entity.EntityCentipedeHead:func_70071_h_:163]: 58.0 / 60.0`

I assume from `[STDOUT/]` that this is very easy to fix, although I'm no Java expert. Maybe there is a config file where I can turn this off and I just overlooked it?

Edit:
[Here's a log file that goes on for about three quarters of an hour](https://gist.github.com/Cynderblood/ff5dd0e779b1fb28c022877ad712bfb4)
In those 42 minutes, the latest.log file grew to 30.158 lines, with the centipede outputs beginning at line 335. From that point on, the log consists mostly of these outputs, a few of them being generated every second.

**Comment by Alex-the-666** [comment]
update your mod.
