### ISSUE TITLE
Spawn config not working for modded biomes

### ISSUE THREAD

**Issue by NixityNull** [Alex-the-666/AlexsMobs#62]
To be specific, I am trying to add the Crimson mosquito to Biomes o' plenty's Visceral heap

**Comment by Alex-the-666** [comment]
["|minecraft:crimson_forest+|bop:visceral_heap"]

**Comment by negationofnegation** [comment]
Where does it say that it's bop:biome_x and not biomesoplenty:biome_x ? I'm asking because I'm curious if I can spawb mobs in another biome mod (Wild Worlds)
