### ISSUE TITLE
Rabbits not spawning anywhere!

### ISSUE THREAD

**Issue by LordHellscream** [Alex-the-666/AlexsMobs#623]
I think the mod overwhelm all spawning "allowance" and I cannot find a single rabbit in all normal spawning biomes (desert, taiga, tundra, mountains, flower forest etc etc)
Using all kind assistance such as scanners and such to help and nada.

Mod version: 1.12.0

**Comment by AidanCorgi4556** [comment]
Change the spawn number in the citadel config
