### ISSUE TITLE
Alex mobs Banner Patters,Bear Paw, Sun Symbol, Star cross and Union  give texture missing pattern on banners when applied

### ISSUE THREAD

**Issue by bloxclay** [Alex-the-666/AlexsMobs#624]
When trying to use the Alex mob banner patters, you get a missing texture pattern rather than the actual pattern when they are applied in the loom, 
![2021-09-02_10 02 57](https://user-images.githubusercontent.com/25862494/131815959-d3a6213d-abc5-4d2d-bc91-fade9aa5758b.png)
![2021-09-02_10 03 45](https://user-images.githubusercontent.com/25862494/131815978-0ecc4073-0e4e-4a66-9a3b-c51781111c67.png)

**Comment by JuicyCosmos** [comment]
Apparently you've got a mod (maybe more than one) that corrupts modded banner pattern textures. Banner pattern from other mods are also likely to be corrupted. (It's more like a registry prevention rather than a corruption)
Try to identify such mod.
Maybe providing a list of mods so others can help?

**Comment by bloxclay** [comment]
> Apparently you've got a mod (maybe more than one) that corrupts modded banner pattern textures. Banner pattern from other mods are also likely to be corrupted. (It's more like a registry prevention rather than a corruption)
> Try to identify such mod.
> Maybe providing a list of mods so others can help?

ok 
![image](https://user-images.githubusercontent.com/25862494/132948061-fba9feeb-329c-4f21-86cf-28afcfbb589b.png)

**Comment by JuicyCosmos** [comment]
Try updating Mowzie's Mobs. The earlier versions of this mod is known to have corrupted banner textures.
And since you use optifine, I suggest you remove dynamic lights mod. The dynamic light feature is included in optifine unless you disabled it manually.

**Comment by bloxclay** [comment]
> Try updating Mowzie's Mobs. The earlier versions of this mod is known to have corrupted banner textures.
> And since you use optifine, I suggest you remove dynamic lights mod. The dynamic light feature is included in optifine unless you disabled it manually.

Thanks Ill see If I can find the newer version of Mowzies mobs, I had a hunch it was that causing issues
