### ISSUE TITLE
Request: Add in a rare zebra variant for mantis shrimp

### ISSUE THREAD

**Issue by warning-djkajslh** [Alex-the-666/AlexsMobs#625]
Zebra mantis shrimp is a thing
https://en.wikipedia.org/wiki/Lysiosquillina_maculata

**Comment by Carro1001** [comment]
Yeah i can try doin that

**Comment by Carro1001** [comment]
wait do these even punch

**Comment by warning-djkajslh** [comment]
> wait do these even punch

yes they do.
