### ISSUE TITLE
Seagull: stealing blacklist

### ISSUE THREAD

**Issue by TheLegitStick** [Alex-the-666/AlexsMobs#631]
My experience: **Seagull steals entire lunchbox from "Spice of Life: Potato Edition"**
The issue is simply that a seagull will have the ability to steal a lunchbox, which is a container item that can hold many stacks of  #food.
I encourage anyone to comment with additional information, as I'm only going to provide a description. I've turned off stealing items, but I'd prefer a blacklist to be implemented, if possible.

**Comment by mischiefsfocus** [comment]
I am having a similar issues except that even when stealing is turned off they continue to steal.

**Comment by TheInfamousAlk** [comment]
What is the formatting for this? I tried putting `solsweetpotato:lunchbox` in the brackets for the blacklist but it failed to read the config and crashed. And what's the formatting for multiple items?

**Comment by NovaLynxie** [comment]
I honestly wish there was a "default" preset for this as having this happen repeatedly is very annoying. At best it should just not consume the entire container and drop the empty one instead.
