### ISSUE TITLE
Grizzly Bears everywhere!

### ISSUE THREAD

**Issue by TocinoShimmer** [Alex-the-666/AlexsMobs#643]
Hello and good afternoon, morning, or whatever.

I don't know if this only happens to me but since I install the last 2 versions... there's a lot of grizzly bears spawning at almost every biome at the game, at groups of 3, 4 or even 5 bears... 3 babies, and 2 adults.

![2021-09-13_15 27 07](https://user-images.githubusercontent.com/56833714/133158997-a1960e1b-3242-4917-b23f-53af480ebe5f.png)

I hope this is only a glitch...

That's all for the moment, thanks for the attention

**Comment by Jukabofy** [comment]
you should use the config to decrease the spawn

**Comment by TocinoShimmer** [comment]
How should i do that? im using "configured" mod but everything seems exactly as other versions of the mod

this "spawn rolls" and "spawn weight" things are confusing me so hard

**Comment by Jukabofy** [comment]
#**_Spawn Weight_**, added to a pool of other mobs for each biome. **_Higher number = higher chance of spawning._** 0 = disable spawn
		#Range: 0 ~ 1000
		snowLeopardSpawnWeight = 10

#**_Random roll_** chance to enable mob spawning. **_Higher number = lower chance of spawning_**
		#Range: > 0
		seagullSpawnRolls = 4

READ CAREFULLY, you should understand it
