### ISSUE TITLE
SEUS Shaders still show lava as water after 1.2 update.

### ISSUE THREAD

**Issue by DefinedAscent** [Alex-the-666/AlexsMobs#66]
Just tested with SEUS PTGI 2.1 and SEUS Renewed 1.0.1 and edited the config and the issue still persists. Lava looks like water.

**Comment by Alex-the-666** [comment]
hmmmm. curious. I'll have to look into this more.

**Comment by Bright625** [comment]
I checked and it really still doesn't work :(
