### ISSUE TITLE
Increase Tusklin's meat drops as well as add in leather drop.

### ISSUE THREAD

**Issue by warning-djkajslh** [Alex-the-666/AlexsMobs#678]
Leather because Hoglins drop those, maybe as much as cows???? Idk, it is a big guy.
Tusklin should have slightly more meats than Hoglin, rn it seems they drops the same, which us 2-4.

Probably should mention that Tusklins also drop leather in the guide book.

**Comment by Alex-the-666** [comment]
no lether, but ill add more meat.
