### ISSUE TITLE
[1.2.0] Server login issues

### ISSUE THREAD

**Issue by Daejangnamu** [Alex-the-666/AlexsMobs#68]
forge-1.16.4-35.1.12
alexsmobs-1.2.0

I cannot login after updating the alexs mobs mod version

![123213123](https://user-images.githubusercontent.com/52635462/102938951-a5d56e80-44f0-11eb-8e25-03ab57639cc2.png)

[User Authenticator #1/INFO] [net.minecraft.network.login.ServerLoginNetHandler/]: UUID of player Daejangnamu is f9803129-d7d4-4926-8f58-988d2e8c032d
[Server thread/INFO] [net.minecraftforge.common.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@2c36d271
[Server thread/INFO] [net.minecraft.server.management.PlayerList/]: Daejangnamu logged in with entity id 120 at (-1.655497487421734, 62.0, -6.652451219807788)
 [Netty Server IO #2/ERROR] [net.minecraft.network.NettyPacketEncoder/]: java.lang.NullPointerException
[Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Daejangnamu joined the game
[Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: Daejangnamu lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
[Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Daejangnamu left the game

**Comment by Alex-the-666** [comment]
did you install citadel 1.5.3?

**Comment by codec-d** [comment]
I'm getting the same error and I have 1.5.3 installed. Reverting back to version 1.1.1 solves the issue.

**Comment by Daejangnamu** [comment]
> did you install citadel 1.5.3?

yes citadel 1.5.3
