### ISSUE TITLE
[Suggestion] Fabric version

### ISSUE THREAD

**Issue by Micalobia** [Alex-the-666/AlexsMobs#693]

**Comment by Dreki1984** [comment]
no

**Comment by Micalobia** [comment]
Any particular reason why, and are you opposed to someone making a port of it?

**Comment by Dreki1984** [comment]
Because why should there be another mod loader if force works fine as it
is? Don’t fix what isn’t broken.

**Comment by Micalobia** [comment]
The mappings and most everything to do with Fabric is licensed differently, making it more open to the user/developer on what they can do. There's also load times, a better learning community, and libraries/APIs that are often less intrusive than Forge, although that's not as necessary and is more a preference thing.

**Comment by Dreki1984** [comment]
Interesting.

**Comment by Alex-the-666** [comment]
no

**Comment by Micalobia** [comment]
Is there any particular reason you don't want to, and would it be okay if someone else ported and maintained it instead?
