### ISSUE TITLE
Crash on my server

### ISSUE THREAD

**Issue by xPown3d** [Alex-the-666/AlexsMobs#695]
[alexmob crash.txt](https://github.com/Alex-the-666/AlexsMobs/files/7383710/alexmob.crash.txt)

Here is the crash file, keep crashing the server when someone connect, disabled it and working now.
I posted you used mods aswell.
![image](https://user-images.githubusercontent.com/34897211/138156756-0e7ae29f-0390-40c7-8d28-e58a3d3a014a.png)

**Comment by Alex-the-666** [comment]
error is with bigbrain mod
