### ISSUE TITLE
Crashing every time I access the crafting book.

### ISSUE THREAD

**Issue by tiaaIord** [Alex-the-666/AlexsMobs#696]
Every time I open the crafting table, Minecraft crashes –– Usually when I try to access the crafting book. 
The computer isn't an issue as it's a fairly recent model and it runs other mods and programs just fine. I've tried re-downloading both mods, (citadel and Alex's mobs), but it doesn't fix anything. Everything else, as far as I can tell, runs smoothly. I haven't seen any other comments reporting the same issue, so am I missing something? Either way, please fix this! Everything else looks amazing!

**Comment by Alex-the-666** [comment]
Crash log?
