### ISSUE TITLE
SEUS renewed an PTGI

### ISSUE THREAD

**Issue by KillNagaThul** [Alex-the-666/AlexsMobs#70]
Hi not working in any seus shaders, same problem, lava looks like water

**Comment by DefinedAscent** [comment]
He is looking into it. He already replied to the one I made earlier that he closed. Hopefully we get a fix soon, quite gamebreaking.

**Comment by Alex-the-666** [comment]
try redownloading the mod

**Comment by DefinedAscent** [comment]
Still nothing. Is it caused by something to do with lava vision? It works perfectly fine with other shaders but not any of the SEUS ones.

**Comment by Alex-the-666** [comment]
Yes I assume the issue has to deal with the setting of a new fluid handler to render the lava vision effect. i'm not sure why it causes issue since the fluid renderer should only be in use when lava vision is used, but the issue seems to exist outside of that too.

**Comment by DefinedAscent** [comment]
I don't enough about java to help thoroughly here. Is it possible we could get an optional alpha version with lava vision removed until this is fixed?

**Comment by negationofnegation** [comment]
Just want to say it's seconded. A preliminary version without any lava potion support that works with SEUS would be very, very appreciated ♡
