### ISSUE TITLE
[1.17] SemiAquatic AI Crash

### ISSUE THREAD

**Issue by Carro1001** [Alex-the-666/AlexsMobs#707]
[crash-2021-11-02_17.56.55-server.txt](https://github.com/Alex-the-666/AlexsMobs/files/7463981/crash-2021-11-02_17.56.55-server.txt)

Happens really often it seems.

**Comment by Alex-the-666** [comment]
Definitely caused by another mod interfering with alexs mobs. None of our aquatics use RestrictSunGoal. I believe its due to another mod that changes vanilla mob AI, probably a performance or immersion mod. Would be good to find out which one

**Comment by Carro1001** [comment]
I think it's Big Brain, since it changes some mob behaviors like making them seek shelter at night
