### ISSUE TITLE
(1.17.1) game freezes for a while then crashes after getting the "Begun, The Emu War" achievement

### ISSUE THREAD

**Issue by uwujelly** [Alex-the-666/AlexsMobs#710]
the first time, after getting the fourth baby emu from the emu eggs i gathered, my game froze after getting the achievement. After restarting my game, i tried to get some baby emus again, but the game froze again after the 2nd baby emu and getting achievement. How can I solve this? Or should I wait for the mod update to get this issue fixed?

**Comment by gohkenytp** [comment]
Same goes with me too.

**Comment by NeonCao** [comment]
Same goes with me too.
crash [report](url) attache
[crash-2021-12-29_02.54.53-client.txt](https://github.com/Alex-the-666/AlexsMobs/files/7787847/crash-2021-12-29_02.54.53-client.txt)
d
