### ISSUE TITLE
CodeChickenLib causes Lava Vision to fail

### ISSUE THREAD

**Issue by Dr-WeiAL** [Alex-the-666/AlexsMobs#722]
CodeChickenLib 1.16.5-4.0.2.429
alexsmobs 1.12.1
![image](https://user-images.githubusercontent.com/47446553/142267752-7728d805-fa56-4f46-9757-ce6a1c1a0bf3.png)
![image](https://user-images.githubusercontent.com/47446553/142267808-4102b342-9c50-49bc-826c-f7aabd6c3cfd.png)

The effect is normal after deleting CodeChickenLib
![image](https://user-images.githubusercontent.com/47446553/142267968-efce1f6d-4b20-451a-b1f8-8b81bebffaf0.png)

**Comment by Alex-the-666** [comment]
Then the problem is with code chicken lib.

**Comment by Dr-WeiAL** [comment]
> Then the problem is with code chicken lib.

TheCBProject/CodeChickenLib#382
They said it’s not a CCL problem, can you take a look
