### ISSUE TITLE
humming bird crash

### ISSUE THREAD

**Issue by RumbleODeath** [Alex-the-666/AlexsMobs#733]
the humming bird is crashing my game in alex mobs im not sure if its my other mods or something else but it is crashin my game and cant reload my survival world cause it crashes instantly

**Comment by RumbleODeath** [comment]
oh so i just loaded a creative world and spawned humming bird and it didnt crash... weird

**Comment by RumbleODeath** [comment]
The game crashed whilst ticking entity
Error: java.lang.ClassCastException: class com.github.alexthe666.alexsmobs.entity.EntityHummingbird$1 cannot be cast to class net.minecraft.world.entity.ai.navigation.GroundPathNavigation (com.github.alexthe666.alexsmobs.entity.EntityHummingbird$1 is in module alexsmobs@1.13.1 of loader 'TRANSFORMER' @7c52fc81; net.minecraft.world.entity.ai.navigation.GroundPathNavigation is in module minecraft@1.17.1 of loader 'TRANSFORMER' @7c52fc81)
Exit Code: -1 is the crash thingy

**Comment by Alex-the-666** [comment]
You have another mod assigning RestrictSunGoal to mobs without checking their navigator first. This is not a problem with Alex's Mobs. Find out what mod is making mobs flee sunlight. Probably a mod that says it changes vanilla mob behavior.
