### ISSUE TITLE
Raccoon Is causing server crash

### ISSUE THREAD

**Issue by Flame115** [Alex-the-666/AlexsMobs#734]
Getting ticking entity crash from raccoons doesn't seem to be constant only sometimes.
[crash-2021-11-23_02.29.09-server.txt](https://github.com/Alex-the-666/AlexsMobs/files/7592748/crash-2021-11-23_02.29.09-server.txt)

**Comment by Alex-the-666** [comment]
> it.unimi.dsi.fastutil.longs.LongLinkedOpenHashSet.removeFirstLong

bug is caused by fastutil mod. its just that the raccoon is what that mod is looking at when it crashes.
