### ISSUE TITLE
Cape still displays when wearing Tarantula Hawk Elytra

### ISSUE THREAD

**Issue by LunarPhobos** [Alex-the-666/AlexsMobs#744]
Cape still displays when wearing Tarantula Hawk Elytra, is this intentional?
![2021-11-26_18 22 17](https://user-images.githubusercontent.com/76231975/143662331-7a8d3f60-2130-4fc4-b539-d95876953cac.png)

**Comment by Alex-the-666** [comment]
nothing we can do about this unfortunately, is a vanilla error
