### ISSUE TITLE
Using Banner pattern with Star cross on Loom is crashing the game

### ISSUE THREAD

**Issue by eugeneivashin** [Alex-the-666/AlexsMobs#780]
[crash-2021-12-09_17.02.05-client.txt](https://github.com/Alex-the-666/AlexsMobs/files/7686183/crash-2021-12-09_17.02.05-client.txt)

**Comment by nezaloth** [comment]
I Found Using Any Of The Modded Banner Patterns Crash The Game

**Comment by muetzeeio** [comment]
same. all banners crash the game
