### ISSUE TITLE
Leaf Cutter Ants Pathing To Leaf Blocks Far Away From Nest

### ISSUE THREAD

**Issue by nezaloth** [Alex-the-666/AlexsMobs#782]
In 1.18 It Is Noted That Pathing To These Far Away Blocks Leaves The Nest Abandoned As The Missing Ants Tend To Get Stuck And Not Return. This Issue Could Be Fixed Simply By Not Letting Ants Path To Or Harvest Leaf Blocks Outside Of A Set Radius From The Nest Entrance (E.g. ~30 - ~50 Blocks). Another Minor Issue With Ants Is Them Detecting And Pathing To Leaves That Are Inaccessible Or Behind Walls.

**Comment by Paradox915** [comment]
I have also encountered this problem with ants getting stuck due to their path finding. This leads to the nests being deserted and is detrimental to the immersion of the mod.
