### ISSUE TITLE
Emu cause crash when dodging arrows

### ISSUE THREAD

**Issue by Edison12300** [Alex-the-666/AlexsMobs#790]
As title. When I reopen the game, it still crashes.
Here's the crash log
[crash-2021-12-16_21.06.03-client.txt](https://github.com/Alex-the-666/AlexsMobs/files/7730446/crash-2021-12-16_21.06.03-client.txt)
:

**Comment by Edison12300** [comment]
I think that the crash has something to do with the advancement. Everytime I try to open alex's mobs advancement tab, the game crashes.

**Comment by Alex-the-666** [comment]
dupe #686
