### ISSUE TITLE
Are mosquitos unaffected by biome configs?

### ISSUE THREAD

**Issue by SatDog92** [Alex-the-666/AlexsMobs#80]
I'm using mod version 1.2.1 and Forge 35.1.10
Apparently, trying to edit the biome configurations for the mosquito spawn doesn't work. This is the syntax below, for my desired setup (i use modded biomes as well):
`["|minecraft:crimson_forest+|biomesoplenty:undergrowth"]`
I'm very sure i'm not doing mistakes (it's "biomesoplenty:", not "bop:") because the setup to make bone serpents appear in only Soul Sand Valley and Visceral Heap (which is a modded biome too) works as intended instead:
`["|minecraft:soul_sand_valley+|biomesoplenty:visceral_heap"]`

Is there something i'm missing? I tested vanilla biomes as well but it's the same problem, they won't spawn in that specified biome, and if i even change "minecraft:crimson_forest" to something else (example: minecraft:nether_wastes), just simply disappear. The problem persists regardless of other mods, i tested this in an installation with only this mod installed, and there is the same issue.

On an unrelated issue: the cave centipede description [seems to clip over the page](https://user-images.githubusercontent.com/56725716/103086756-aef43780-45e5-11eb-93af-d50fae890042.png).

**Comment by NixityNull** [comment]
I am having the same issue with the crimson mosquito spawn config not working with modded biomes.

**Comment by Brun333rp** [comment]
also having this issue. this seems to affect other mobs as well, mainly Nether and End ones.
