### ISSUE TITLE
Spawn rate after 1.18 blend

### ISSUE THREAD

**Issue by blaboup** [Alex-the-666/AlexsMobs#803]
Hi I optimized my 1.17 world into 1.18, but alex’s mobs are spawning very scarcily, if even at all once outside the blend (so in the 1.18 world generation). 

So far I’ve seen that flutters, rocky rollers and capuchin monkey, cachalots (all mobs that should be quite frequent, at least they were in 1.17) are mainly absent, and i have seen only 2 gorillas in a whole jungle biome

In a world with the same seed, I went to the same places, and found normal spawning rates. 
Something to explain it?

Again, these are in until now unloaded chunks so I didn’t think there would be a problem.

**Comment by Alex-the-666** [comment]
Yes this is intended. Prior to 1.15.0 our mob spawns were unintentionally being doubled due to a bug.

**Comment by blaboup** [comment]
I dont think you understand. It looks like a blended 1.17->1.18 world messes with the spawn rates, and makes the mobs super rare to find. 

But in the same world, same seed with purely 1.18 gen, the mobs are spawning as they should.

For example in my blended world I could see no capuchin monkeys at all (with the glowing entity command) but in the same seed purely 1.18 world, and same biome, I could easily detect 15-18 capuchin monkeys.
