### ISSUE TITLE
[BUG] there's a fly in this mod, lol

### ISSUE THREAD

**Issue by DRAKKKS** [Alex-the-666/AlexsMobs#81]
reporting a bug 😂

**Comment by NovaN4** [comment]
crimson mosquitoes seem to exist, please fix this thanks

**Comment by DRAKKKS** [comment]
lol   From: NikoSent: Saturday, December 26, 2020 4:29 AMTo: Alex-the-666/AlexsMobsCc: DRAKKKS; AuthorSubject: Re: [Alex-the-666/AlexsMobs] [BUG] there's a fly in this mod, lol (#81) crimson mosquitoes seem to exist, please fix this thanks—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by DRAKKKS** [comment]
Hope this gave yall a good laugh
