### ISSUE TITLE
Flying mobs get stuck on water

### ISSUE THREAD

**Issue by Carro1001** [Alex-the-666/AlexsMobs#818]
If they fly and land on water, they are permanently stuck bobbing up and down there, this applies to most if not every thing entity, crows, tar hawks, seagulls, toucans, and so on

**Comment by ozBillo** [comment]
I can confirm this problem still exists in alexsmobs-1.17.0

**Comment by Flugel3** [comment]
I also have this issue and don't know the root of it at all, originally I thought it was only crows trying to find items underwater
