### ISSUE TITLE
Cave Centipedes are recognized as neutral mobs by game, yet act entirely hostile. 

### ISSUE THREAD

**Issue by newtrogicNexus** [Alex-the-666/AlexsMobs#824]
Even the guidebook claims them to be hostile creatures, yet due to them being recognized as a neutral mob, items that prevent hostile mob spawns don't prevent them from spawning.

**Comment by AlexModGuy** [comment]
![Screenshot (648)](https://user-images.githubusercontent.com/8662109/149052236-d75edb5d-e1cf-478d-a42b-a5c096bed15f.png)
Seems like thats another mod's issue.

**Comment by esotericist** [comment]
> Even the guidebook claims them to be hostile creatures, yet due to them being recognized as a neutral mob, items that prevent hostile mob spawns don't prevent them from spawning.

if this is about torchmaster, it doesn't attempt to automatically determine what mobs to block outside of the ones it already knows; you have to manually adjust the config for the mobs in question.
