### ISSUE TITLE
1.18.1 still crashs after a few minutes

### ISSUE THREAD

**Issue by agentwolf88** [Alex-the-666/AlexsMobs#827]
[crash-2022-01-01_12.30.57-server.txt](https://github.com/Alex-the-666/AlexsMobs/files/7797621/crash-2022-01-01_12.30.57-server.txt)

**Comment by agentwolf88** [comment]
https://crashy.net/KywsfnxkAUhygFSZE9ty

**Comment by LagHero** [comment]
My server is also crashing after a few minutes, but I think the root cause might be different:

>  [11Jan2022 21:26:46.886] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
> net.minecraft.ReportedException: Exception ticking world
> at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872) ~[server-1.18.1-20211210.034407-srg.jar%2348!:?]
> at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%2348!:?]
> at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%2348!:?]
> at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%2348!:?]
> at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%2348!:?]
> at java.lang.Thread.run(Thread.java:833) [?:?]
> **Caused by: java.lang.NoSuchFieldError: DIRT**
> at com.github.alexthe666.alexsmobs.entity.**EntityFly.canFlySpawn(EntityFly.java:115)** ~[alexsmobs-1.15.1.jar%2337!:1.15.1]
> at net.minecraft.world.entity.SpawnPlacements.m_21759_(SpawnPlacements.java:63) ~[server-1.18.1-20211210.034407-srg.jar%2348!:?]
> at net.minecraft.world.level.NaturalSpawner.m_46995_(NaturalSpawner.java:226) ~[server-1.18.1-20211210.034407-srg.jar%2348!:?]
> at net.minecraft.world.level.NaturalSpawner.m_47038_(NaturalSpawner.java:174) ~[server-1.18.1-20211210.034407-srg.jar%2348!:?]
> at net.minecraft.world.level.NaturalSpawner.m_47045_(NaturalSpawner.java:124) ~[server-1.18.1-20211210.034407-srg.jar%2348!:?]
> at net.minecraft.world.level.NaturalSpawner.m_47029_(NaturalSpawner.java:114) ~[server-1.18.1-20211210.034407-srg.jar%2348!:?]
> at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:355) ~[server-1.18.1-20211210.034407-srg.jar%2348!:?]
> at net.minecraft.server.level.ServerChunkCache.m_142483_(ServerChunkCache.java:311) ~[server-1.18.1-20211210.034407-srg.jar%2348!:?]
> at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:278) ~[server-1.18.1-20211210.034407-srg.jar%2348!:?]
> at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[server-1.18.1-20211210.034407-srg.jar%2348!:?]
> ... 5 more
>

**Comment by AlexModGuy** [comment]
install 1.16.0 version of the mod
