### ISSUE TITLE
[1.18.1] Advancement Crash when clicking Alexs Mobs tab

### ISSUE THREAD

**Issue by itsdinkd** [Alex-the-666/AlexsMobs#832]
https://crashy.net/ZHqNEg9vcK4Vi6xW2fqJ

**Comment by twa16** [comment]
The folks on my server and myself are facing the same crash when pulling up some alexsmobs items in just enough items.

**Comment by twa16** [comment]
Alright, this seems to be where the NPE is coming from: https://github.com/Alex-the-666/AlexsMobs/blob/4ab22411d20038bd04f7df2147f340cc1cadacc4/src/main/resources/data/alexsmobs/advancements/alexsmobs/emu_dodge.json#L5

**Comment by lhaeussler** [comment]
Having the same issue here, when i type somethin with the letter "e" in jei

**Comment by AlexModGuy** [comment]
fixed
