### ISSUE TITLE
Spawning fly's crashes the game?

### ISSUE THREAD

**Issue by elderendlord** [Alex-the-666/AlexsMobs#833]
I'm trying to make a mod series survival on a mod pack. and for some reason fly's are crashing the game.

I'm also using 28 Xtra mods that dont have flys in them. If you need the mod pack. I dont know if Ill be able to send? its also 1.18.1.

[https://www.mediafire.com/file/islfd05gtus4lst/Mod+Pack.zip/file](url)

**Comment by AlexModGuy** [comment]
fixed
