### ISSUE TITLE
Advancement tab crashing 1.18.1 

### ISSUE THREAD

**Issue by LuigiTP** [Alex-the-666/AlexsMobs#837]
Whenever i click the alexs advancement tab it crashes my game
i am in a multiplayer server however so far (to my knowledge) im the only one experiencing this

the crash report mentioned a block not rendering i think its the australia banner for some reason

[crash-2022-01-07_17.18.09-client.txt](https://github.com/Alex-the-666/AlexsMobs/files/7830316/crash-2022-01-07_17.18.09-client.txt)

**Comment by lhaeussler** [comment]
Having a similar one with another mob here
[crash-2022-01-09_17.58.31-client.txt](https://github.com/Alex-the-666/AlexsMobs/files/7835526/crash-2022-01-09_17.58.31-client.txt)
