### ISSUE TITLE
Rocky Roller Chestplate not working at all

### ISSUE THREAD

**Issue by AstroPenguan** [Alex-the-666/AlexsMobs#838]
I play on 1.18 through better minecraft modpack and when I first crafted the rocky roller chestplate it was working perfectly, but since a while ago it has stopped working, I've tried almost everything, exiting to main menu, quitting game, Opening LAN world and even restarting computer.

**Comment by Carro1001** [comment]
Take it off, leave the world, then put it back on, the problem seems to be if you die while wearing it, it just doesn't work until you relog, but it also just doesn't work randomly to a few people so i'm not sure
