### ISSUE TITLE
Crash 1.18.1 Version

### ISSUE THREAD

**Issue by Daihok41** [Alex-the-666/AlexsMobs#846]
Getting this Crash with newest Forge Version 39.0.18 and Alex mobs Version 1.15.1

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 1/10/22, 7:11 PM
Description: Exception ticking world

java.lang.NoSuchFieldError: DIRT
	at com.github.alexthe666.alexsmobs.entity.EntityFly.canFlySpawn(EntityFly.java:115) ~[alexsmobs-1.15.1.jar%2354!:1.15.1] {re:classloading}
	at net.minecraft.world.entity.SpawnPlacements.m_21759_(SpawnPlacements.java:63) ~[client-1.18.1-20211210.034407-srg.jar%23144!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.world.level.NaturalSpawner.m_46995_(NaturalSpawner.java:226) ~[client-1.18.1-20211210.034407-srg.jar%23144!:?] {re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47038_(NaturalSpawner.java:174) ~[client-1.18.1-20211210.034407-srg.jar%23144!:?] {re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47045_(NaturalSpawner.java:124) ~[client-1.18.1-20211210.034407-srg.jar%23144!:?] {re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47029_(NaturalSpawner.java:114) ~[client-1.18.1-20211210.034407-srg.jar%23144!:?] {re:classloading}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:355) ~[client-1.18.1-20211210.034407-srg.jar%23144!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_142483_(ServerChunkCache.java:311) ~[client-1.18.1-20211210.034407-srg.jar%23144!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:278) ~[client-1.18.1-20211210.034407-srg.jar%23144!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[client-1.18.1-20211210.034407-srg.jar%23144!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%23144!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:120) ~[client-1.18.1-20211210.034407-srg.jar%23144!:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%23144!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%23144!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.github.alexthe666.alexsmobs.entity.EntityFly.canFlySpawn(EntityFly.java:115) ~[alexsmobs-1.15.1.jar%2354!:1.15.1] {re:classloading}
	at net.minecraft.world.entity.SpawnPlacements.m_21759_(SpawnPlacements.java:63) ~[client-1.18.1-20211210.034407-srg.jar%23144!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.world.level.NaturalSpawner.m_46995_(NaturalSpawner.java:226) ~[client-1.18.1-20211210.034407-srg.jar%23144!:?] {re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47038_(NaturalSpawner.java:174) ~[client-1.18.1-20211210.034407-srg.jar%23144!:?] {re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47045_(NaturalSpawner.java:124) ~[client-1.18.1-20211210.034407-srg.jar%23144!:?] {re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47029_(NaturalSpawner.java:114) ~[client-1.18.1-20211210.034407-srg.jar%23144!:?] {re:classloading}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:355) ~[client-1.18.1-20211210.034407-srg.jar%23144!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_142483_(ServerChunkCache.java:311) ~[client-1.18.1-20211210.034407-srg.jar%23144!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:278) ~[client-1.18.1-20211210.034407-srg.jar%23144!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:A}
-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['Daihok'/144, l='ServerLevel[New World]', x=-41.64, y=90.07, z=207.39]]
	Chunk stats: 15509
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,63,48), Section: (at 0,15,0 in -2,3,3; chunk contains blocks -32,-64,48 to -17,319,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 660 game time, 660 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 174210 (now: false), thunder time: 160059 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[client-1.18.1-20211210.034407-srg.jar%23144!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%23144!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:120) ~[client-1.18.1-20211210.034407-srg.jar%23144!:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%23144!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%23144!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2892585984 bytes (2758 MiB) / 6220152832 bytes (5932 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1660 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x21c4
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9729
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 29610.31
	Virtual memory used (MB): 21443.16
	Swap memory total (MB): 13312.00
	Swap memory used (MB): 264.36
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Daihok'/144, l='ServerLevel[New World]', x=-41.64, y=90.07, z=207.39]]
	Data Packs: vanilla, mod:morecarpets (incompatible), mod:inventorysorter (incompatible), mod:doubledoors, mod:supermartijn642configlib, mod:flatbedrock (incompatible), mod:vanillaexcavators, mod:beenfo (incompatible), mod:platforms, mod:jei (incompatible), mod:justmobheads, mod:mcwwindows, mod:kleeslabs, mod:moreconcrete, mod:xaeroworldmap, mod:comforts, mod:citadel, mod:alexsmobs (incompatible), mod:additionalbars (incompatible), mod:smarterfarmers (incompatible), mod:player_mobs (incompatible), mod:libx, mod:rangedpumps, mod:betteranimalsplus, mod:bonsaitrees3, mod:filteredchests, mod:beefix, mod:newwalls, mod:mcwdoors, mod:balm (incompatible), mod:packingtape (incompatible), mod:ninjaphenix_container_lib, mod:cloth_config (incompatible), mod:forge, mod:stackrefill, mod:shetiphiancore, mod:refinedstorage, mod:axesareweapons (incompatible), mod:replantingcrops, mod:mcwbridges, mod:block_variants, mod:swingthroughgrass, mod:livingthings (incompatible), mod:endertanks, mod:ambientsounds (incompatible), mod:playerplates (incompatible), mod:titanium (incompatible), mod:the_wild_update (incompatible), mod:immersiveengineering, mod:morevanillalib, mod:drawerfps (incompatible), mod:creativecore, mod:mcwtrpdoors, mod:mcwfences, mod:ava (incompatible), mod:horsestatsmod (incompatible), mod:supermartijn642corelib, mod:simplylight (incompatible), mod:domum_ornamentum (incompatible), mod:itsjustlights (incompatible), mod:wthit, mod:spark (incompatible), mod:car, mod:betterfpsdist (incompatible), mod:pipez, mod:patchouli, mod:xaerominimap, mod:croptopia, mod:collective, mod:multibeds, mod:dramaticdoors, mod:storagedrawers (incompatible), mod:enderchests, mod:vanillahammers, mod:expandedstorage, mod:extrastorage (incompatible), mod:cfm (incompatible), mod:architectury (incompatible), mod:ferritecore (incompatible), mod:engineersdecor (incompatible), mod:functionalstorage, mod:trashcans, mod:chunkloaders (incompatible), mod:aquaculture (incompatible), mod:inventoryessentials, mod:refinedstorageaddons, mod:speedyladders (incompatible), mod:fastleafdecay, mod:thutcore, mod:betterboats, mod:thuttech, mod:mcwlights
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	OptiFine Version: OptiFine_1.18.1_HD_U_H4
	OptiFine Build: 20211212-175054
	Render Distance Chunks: 30
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 497.29
	OpenGlRenderer: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		MoreCarpets-1.18.1-1.5.5.jar                      |More Carpets                  |morecarpets                   |1.5.5               |DONE      |Manifest: NOSIGNATURE
		inventorysorter-1.18-19.0.0.jar                   |Simple Inventory Sorter       |inventorysorter               |19.0.0              |DONE      |Manifest: NOSIGNATURE
		doubledoors_1.18.1-3.2.jar                        |Double Doors                  |doubledoors                   |3.2                 |DONE      |Manifest: NOSIGNATURE
		supermartijn642configlib-1.0.9-mc1.18.jar         |SuperMartijn642's Config Lib  |supermartijn642configlib      |1.0.9               |DONE      |Manifest: NOSIGNATURE
		flatbedrock-1.4.0-build.6+mc1.18.1.jar            |Flat Bedrock                  |flatbedrock                   |1.4.0-build.6+mc1.18|DONE      |Manifest: NOSIGNATURE
		VanillaExcavators-1.18.1-4.0.0.jar                |Vanilla Excavators            |vanillaexcavators             |1.18.1-4.0.0        |DONE      |Manifest: NOSIGNATURE
		beenfo-1.18.1-forge39.0.9-1.2.jar                 |Beenfo                        |beenfo                        |1.18.1-forge39.0.9-1|DONE      |Manifest: NOSIGNATURE
		platforms-1.18-1.9.0.jar                          |Platforms                     |platforms                     |1.9.0               |DONE      |Manifest: NOSIGNATURE
		jei-1.18.1-9.2.1.69.jar                           |Just Enough Items             |jei                           |9.2.1.69            |DONE      |Manifest: NOSIGNATURE
		justmobheads_1.18.1-5.3.jar                       |Just Mob Heads                |justmobheads                  |5.3                 |DONE      |Manifest: NOSIGNATURE
		mcw-windows-2.0.2-mc1.18.1.jar                    |Macaw's Windows               |mcwwindows                    |2.0.2               |DONE      |Manifest: NOSIGNATURE
		kleeslabs-forge-1.18-11.0.0.jar                   |KleeSlabs                     |kleeslabs                     |11.0.0              |DONE      |Manifest: NOSIGNATURE
		moreconcrete-1.2.1-1.18.1.jar                     |More Concrete                 |moreconcrete                  |1.2.1               |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.19.1_Forge_1.18.jar              |Xaero's World Map             |xaeroworldmap                 |1.19.1              |DONE      |Manifest: NOSIGNATURE
		comforts-forge-1.18-5.0.0.1.jar                   |Comforts                      |comforts                      |1.18-5.0.0.1        |DONE      |Manifest: NOSIGNATURE
		citadel-1.10.8-1.18.jar                           |Citadel                       |citadel                       |1.10.8              |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.15.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.15.1              |DONE      |Manifest: NOSIGNATURE
		1.18.1-additionalbars-2.3.0.jar                   |Additional Bars               |additionalbars                |2.3.0               |DONE      |Manifest: NOSIGNATURE
		smarterfarmers-1.18-1.2.1.jar                     |Smarter Farmers               |smarterfarmers                |1.18-1.2.1          |DONE      |Manifest: NOSIGNATURE
		PlayerMobs-1.18.1-2.0.1.12.jar                    |Player Mobs                   |player_mobs                   |2.0.1.12            |DONE      |Manifest: 15:a4:a3:0e:d2:f8:64:0c:a4:97:30:5f:48:ba:5f:69:f9:23:42:14:a8:5a:60:3a:b1:b1:29:1a:0a:37:3c:79
		LibX-1.18.1-3.1.7.jar                             |LibX                          |libx                          |1.18.1-3.1.7        |DONE      |Manifest: NOSIGNATURE
		rangedpumps-0.9.0.jar                             |Ranged Pumps                  |rangedpumps                   |0.9.0               |DONE      |Manifest: NOSIGNATURE
		betteranimalsplus-1.18.1-11.0.3-forge.jar         |Better Animals Plus           |betteranimalsplus             |1.18.1-11.0.3       |DONE      |Manifest: NOSIGNATURE
		bonsaitrees3-3.0.0.jar                            |Bonsai Trees 3                |bonsaitrees3                  |3.0.0               |DONE      |Manifest: NOSIGNATURE
		filteredchests-1.18.1-1.0.2.jar                   |Filtered Chests Mod           |filteredchests                |1.0.2               |DONE      |Manifest: NOSIGNATURE
		BeeFix-1.18-1.0.0.1.jar                           |Bee Fix                       |beefix                        |1.0.0.1             |DONE      |Manifest: NOSIGNATURE
		NewSlabsStairsWalls-1.18.1-2.0.1.jar              |New Slabs, Stairs & Walls     |newwalls                      |2.0.1               |DONE      |Manifest: NOSIGNATURE
		mcw-doors-1.0.5-mc1.18.1.jar                      |Macaw's Doors                 |mcwdoors                      |1.0.5               |DONE      |Manifest: NOSIGNATURE
		balm-2.4.0+0.jar                                  |Balm                          |balm                          |2.4.0+0             |DONE      |Manifest: NOSIGNATURE
		PackingTape-1.18-0.12.2.jar                       |Packing Tape                  |packingtape                   |0.12.2              |DONE      |Manifest: NOSIGNATURE
		ninjaphenix-container-library-1.2.10+1.18.jar     |NinjaPhenix's Container Librar|ninjaphenix_container_lib     |1.2.10              |DONE      |Manifest: NOSIGNATURE
		cloth-config-6.1.48-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.1.48              |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.18-universal.jar                |Forge                         |forge                         |39.0.18             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		stackrefill_1.18.1-2.1.jar                        |Stack Refill                  |stackrefill                   |2.1                 |DONE      |Manifest: NOSIGNATURE
		shetiphiancore-1.18-3.10.0.jar                    |ShetiPhian-Core               |shetiphiancore                |3.10.0              |DONE      |Manifest: NOSIGNATURE
		refinedstorage-1.10.0-beta.4.jar                  |Refined Storage               |refinedstorage                |1.10.0-beta.4       |DONE      |Manifest: NOSIGNATURE
		AxesAreWeapons-1.5.1-forge-1.18.jar               |Axes Are Weapons              |axesareweapons                |1.5.1               |DONE      |Manifest: NOSIGNATURE
		replantingcrops_1.18.1-2.6.jar                    |Replanting Crops              |replantingcrops               |2.6                 |DONE      |Manifest: NOSIGNATURE
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		mcw-bridges-2.0.1-mc1.18.1.jar                    |Macaw's Bridges               |mcwbridges                    |2.0.1               |DONE      |Manifest: NOSIGNATURE
		block_variants-1.18.1-3.1.jar                     |Vanilla Block Variants        |block_variants                |3.1                 |DONE      |Manifest: NOSIGNATURE
		swingthroughgrass-1.18.1-1.8.0.jar                |SwingThroughGrass             |swingthroughgrass             |1.18.1-1.8.0        |DONE      |Manifest: NOSIGNATURE
		livingthings-1.18.1-1.4.1.jar                     |Living Things                 |livingthings                  |1.18.1 - 1.4.1      |DONE      |Manifest: NOSIGNATURE
		endertanks-1.18-1.11.0.jar                        |EnderTanks                    |endertanks                    |1.11.0              |DONE      |Manifest: NOSIGNATURE
		AmbientSounds_v5.0.3_mc1.18.1.jar                 |Ambient Sounds                |ambientsounds                 |3.0.3               |DONE      |Manifest: NOSIGNATURE
		PlayerPlates-1.1.3-build.6+mc1.18.1.jar           |Player Plates                 |playerplates                  |1.1.3-build.6+mc1.18|DONE      |Manifest: NOSIGNATURE
		titanium-1.18-3.4.0-27.jar                        |Titanium                      |titanium                      |3.4.0               |DONE      |Manifest: NOSIGNATURE
		The_Wild_Update_Mod_V1.1_Minecraft_1.18.1.jar     |The Wild Update 1.19 Mod      |the_wild_update               |1.1                 |DONE      |Manifest: NOSIGNATURE
		ImmersiveEngineering-1.18.1-7.1.0-145.jar         |Immersive Engineering         |immersiveengineering          |1.18.1-7.1.0-145    |DONE      |Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		MoreVanillaLib-1.18.1-3.0.3.jar                   |MoreVanillaLib                |morevanillalib                |1.18.1-3.0.3        |DONE      |Manifest: NOSIGNATURE
		drawerfps-1.18.1-1.7.jar                          |Example Mod                   |drawerfps                     |1.18.1-1.7          |DONE      |Manifest: NOSIGNATURE
		CreativeCore_v2.4.1_mc1.18.1.jar                  |CreativeCore                  |creativecore                  |2.4.0               |DONE      |Manifest: NOSIGNATURE
		mcw-trapdoors-1.0.4-mc1.18.1.jar                  |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.4               |DONE      |Manifest: NOSIGNATURE
		mcw-fences-1.0.2-mc1.18.1.jar                     |Macaw's Fences and Walls      |mcwfences                     |1.0.2               |DONE      |Manifest: NOSIGNATURE
		ava-2.0.3.jar                                     |A.V.A - Alliance of Valiant Ar|ava                           |2.0.3               |DONE      |Manifest: NOSIGNATURE
		horsestatsmod-MC1.18.x-1.4.3.jar                  |Horse Stats Mod               |horsestatsmod                 |1.4.3               |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.15a-mc1.18.jar         |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.15a             |DONE      |Manifest: NOSIGNATURE
		simplylight-1.18.1-1.4.0-build.26.jar             |Simply Light                  |simplylight                   |1.18.1-1.4.0-build.2|DONE      |Manifest: NOSIGNATURE
		domum_ornamentum-1.18-1.0.32-ALPHA-universal.jar  |Domum Ornamentum              |domum_ornamentum              |1.18-1.0.32-ALPHA   |DONE      |Manifest: NOSIGNATURE
		itsjustlights[1.18]-v1.0.0.jar                    |It's just lights              |itsjustlights                 |1.0.0               |DONE      |Manifest: NOSIGNATURE
		wthit-forge-4.4.1.jar                             |wthit                         |wthit                         |4.4.1               |DONE      |Manifest: NOSIGNATURE
		spark-forge.jar                                   |spark                         |spark                         |1.7.2               |DONE      |Manifest: NOSIGNATURE
		car-1.18.1-1.0.1.jar                              |Ultimate Car Mod              |car                           |1.18.1-1.0.1        |DONE      |Manifest: NOSIGNATURE
		betterfpsdist-1.18-1.3.jar                        |betterfpsdist mod             |betterfpsdist                 |1.18-1.3            |DONE      |Manifest: NOSIGNATURE
		pipez-1.18.1-1.0.1.jar                            |Pipez                         |pipez                         |1.18.1-1.0.1        |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.18.1-64.jar                           |Patchouli                     |patchouli                     |1.18.1-64           |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_21.23.1_Forge_1.18.jar             |Xaero's Minimap               |xaerominimap                  |21.23.1             |DONE      |Manifest: NOSIGNATURE
		Croptopia-1.18-FORGE-1.8.0.jar                    |Croptopia                     |croptopia                     |1.8.0               |DONE      |Manifest: NOSIGNATURE
		collective-1.18.1-3.8.jar                         |Collective                    |collective                    |3.8                 |DONE      |Manifest: NOSIGNATURE
		multibeds-1.18-1.9.0.jar                          |Multi-Beds                    |multibeds                     |1.9.0               |DONE      |Manifest: NOSIGNATURE
		DramaticDoors-1.18.1-1.4.2.jar                    |Dramatic Doors                |dramaticdoors                 |1.18.1-1.4.2        |DONE      |Manifest: NOSIGNATURE
		StorageDrawers-1.18.1-10.1.0.jar                  |Storage Drawers               |storagedrawers                |10.1.0              |DONE      |Manifest: NOSIGNATURE
		enderchests-1.18-1.9.0.jar                        |EnderChests                   |enderchests                   |1.9.0               |DONE      |Manifest: NOSIGNATURE
		VanillaHammers-1.18.1-4.0.0.jar                   |Vanilla Hammers               |vanillahammers                |1.18.1-4.0.0        |DONE      |Manifest: NOSIGNATURE
		expandedstorage-7.3.6+1.18.jar                    |Expanded Storage              |expandedstorage               |7.3.6               |DONE      |Manifest: NOSIGNATURE
		ExtraStorage-1.18.1-2.0.1.jar                     |Extra Storage                 |extrastorage                  |2.0.1               |DONE      |Manifest: NOSIGNATURE
		furniture-7.0.0-pre27-1.18.1.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre27         |DONE      |Manifest: NOSIGNATURE
		architectury-3.4.9.jar                            |Architectury                  |architectury                  |3.4.9               |DONE      |Manifest: NOSIGNATURE
		ferritecore-4.0.0-forge.jar                       |Ferrite Core                  |ferritecore                   |4.0.0               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		engineersdecor-1.18.1-1.1.19-b1.jar               |Engineer's Decor              |engineersdecor                |1.1.19-b1           |DONE      |Manifest: NOSIGNATURE
		functionalstorage-1.18.1-0.0.7.jar                |Functional Storage            |functionalstorage             |1.18.1-0.0.7        |DONE      |Manifest: NOSIGNATURE
		trashcans-1.0.12-mc1.18.jar                       |Trash Cans                    |trashcans                     |1.0.12              |DONE      |Manifest: NOSIGNATURE
		chunkloaders-1.1.8-mc1.18.jar                     |Chunk Loaders                 |chunkloaders                  |1.1.8               |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.18.1-2.3.2.jar                      |Aquaculture 2                 |aquaculture                   |1.18.1-2.3.2        |DONE      |Manifest: NOSIGNATURE
		inventoryessentials-forge-1.18-4.0.1.jar          |Inventory Essentials          |inventoryessentials           |4.0.1               |DONE      |Manifest: NOSIGNATURE
		refinedstorageaddons-0.8.1.jar                    |Refined Storage Addons        |refinedstorageaddons          |0.8.1               |DONE      |Manifest: NOSIGNATURE
		speedyladders-1.18-1.jar                          |Speedy Ladders                |speedyladders                 |1.18-1              |DONE      |Manifest: NOSIGNATURE
		FastLeafDecay-27.2.jar                            |FastLeafDecay                 |fastleafdecay                 |27.2                |DONE      |Manifest: NOSIGNATURE
		thutcore-1.18.1-8.6.3.jar                         |Thut Core                     |thutcore                      |8.6.3               |DONE      |Manifest: NOSIGNATURE
		betterboats-1.1.4.jar                             |Better Boats                  |betterboats                   |1.1.4               |DONE      |Manifest: NOSIGNATURE
		thuttech-1.18.1-9.1.5.jar                         |Thut Elevators                |thuttech                      |9.1.5               |DONE      |Manifest: NOSIGNATURE
		mcw-lights-1.0.2-mc1.18.1.jar                     |Macaw's Lights and Lamps      |mcwlights                     |1.0.2               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: ff571717-366d-48e3-90db-340e0852d024
	FML: 39.0
	Forge: net.minecraftforge:39.0.18

**Comment by MarkusBordihn** [comment]
Just for FYI, seems this is related to the following change https://github.com/MinecraftForge/MinecraftForge/pull/7891 which removed the forge dirt block.

**Comment by caligator** [comment]
I'm getting the same error under the same environment, so yea its replicated pretty solidly
[latest.log](https://github.com/Alex-the-666/AlexsMobs/files/7843347/latest.log)
.

**Comment by ClaudiusMinimus** [comment]
Me too
https://crashy.net/f0BWMiZCY2JRcNcVK6yF
or
https://crashy.net/f0BWMiZCY2JRcNcVK6yF?raw

**Comment by ClaudiusMinimus** [comment]
Seems to be an issue with Forge 39.0.18. I reverted to 39.0.17 and it seems to work fine.

**Comment by AzureMonument** [comment]
I've experienced the same thing- but unfortunately I can't revert the forge version of the server I'm using due to it, in its infinite wisdom, only allowing the install of the latest forge version for each version of mc -_-

*sigh*
Hopefully this gets fixed soon.

**Comment by ClaudiusMinimus** [comment]
>  unfortunately I can't revert the forge version of the server I'm using due to the host, in its infinite wisdom, only allowing the install of the latest forge version for each version of mc -_-

I am glad you mentioned this issue as I made this very point with my sponsor, Bisect Hosting.

**Comment by Lesley-Black-Velvet** [comment]
I have the same issue.

**Comment by AlexModGuy** [comment]
fixed

**Comment by ClaudiusMinimus** [comment]
> I've experienced the same thing- but unfortunately I can't revert the forge version of the server I'm using due to the host, in its infinite wisdom, only allowing the install of the latest forge version for each version of mc -_-

Take a look at this [video](https://www.youtube.com/watch?v=7OzcRO4sPd4). Maybe your hosting company has a similar feature.
