### ISSUE TITLE
The bug crashed my game

### ISSUE THREAD

**Issue by Klouver-github** [Alex-the-666/AlexsMobs#849]
a Bug crashed my game (pun intended) https://paste.gg/p/anonymous/5bd7998d11204fc2a7d3ac18bea4aef4

**Comment by littlepianist** [comment]
I get the exact same bug(fly)

**Comment by Wedge1453** [comment]
same (1.18), only started happening today in the overworld, after I updated the following mods:

- Biomes O'Plenty
- Ambient Sound
- GeckoLib
- Flywheel
- Create
- Create Addition
- Carry On

I suspect Create or on of its addons/dependncies, or GeckoLib.
[crash-2022-01-11_12.03.15-server.txt](https://github.com/Alex-the-666/AlexsMobs/files/7845948/crash-2022-01-11_12.03.15-server.txt)

**Comment by nikolodeon** [comment]
yeap also getting the same crash.. and its not like its one of those mods that you can turn off mid game, since you have acquired a bunch of items from it already.
[crash-2022-01-11_15.22.40-server.txt](https://github.com/Alex-the-666/AlexsMobs/files/7847372/crash-2022-01-11_15.22.40-server.txt)

**Comment by Wedge1453** [comment]
found out it's because of forge 39.0.18 removing something, I reverted to 39.0.17 and the problem was solved.

**Comment by nikolodeon** [comment]
thanks Wedge1453 that worked!

**Comment by JasonKillsUs** [comment]
same here, thanks for the hint, reverted to x.17

**Comment by AlexModGuy** [comment]
fixed, will be in a release very soon
