### ISSUE TITLE
java.lang.stackoverflow error

### ISSUE THREAD

**Issue by DvIy** [Alex-the-666/AlexsMobs#850]
i got alex'smob mod and played for a bit yesterday with my friends but when we got online today we spent likw 10-20 seconds til the server crashed and we tried again and it happened again i checked the server and client logs and the mod had errors

here are the logs:

https://mclo.gs/2OiMko4
https://mclo.gs/ZL6JYRd

**Comment by Wedge1453** [comment]
downgrade forge version to 39.017

**Comment by AlexModGuy** [comment]
fixed
