### ISSUE TITLE
1.18.1 update creates crash caused by ticking error or sumthin idk on the latest forge version

### ISSUE THREAD

**Issue by andreibear** [Alex-the-666/AlexsMobs#852]
taking alex's mobs out of the mods folder makes everything fine again. I love this mod fix as fast as possible pls i beg here is the full crash report.

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 1/11/22, 4:21 PM
Description: Exception in server tick loop

java.util.concurrent.CompletionException: net.minecraft.ReportedException: Exception generating new chunk
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:58) ~[client-1.18.1-20211210.034407-srg.jar%23108!:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.18.1-20211210.034407-srg.jar%23108!:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.18.1-20211210.034407-srg.jar%23108!:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.18.1-20211210.034407-srg.jar%23108!:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
Caused by: net.minecraft.ReportedException: Exception generating new chunk
	at net.minecraft.server.level.ChunkMap.lambda$chunkGenerate$20(ChunkMap.java:704) ~[client-1.18.1-20211210.034407-srg.jar%23108!:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:polymorph.mixins.json:AccessorChunkMap,pl:mixin:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar%2337!:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$chunkGenerate$22(ChunkMap.java:684) ~[client-1.18.1-20211210.034407-srg.jar%23108!:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:polymorph.mixins.json:AccessorChunkMap,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	... 11 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.tags.Tag.m_8110_(Object)" because the return value of "net.minecraft.tags.TagCollection.m_13404_(net.minecraft.resources.ResourceLocation)" is null
	at com.github.alexthe666.alexsmobs.entity.EntityCrocodile.canCrocodileSpawn(EntityCrocodile.java:120) ~[alexsmobs-1.15.1.jar%2355!:1.15.1] {re:classloading}
	at net.minecraft.world.entity.SpawnPlacements.m_21759_(SpawnPlacements.java:63) ~[client-1.18.1-20211210.034407-srg.jar%23108!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.NaturalSpawner.m_151616_(NaturalSpawner.java:358) ~[client-1.18.1-20211210.034407-srg.jar%23108!:?] {re:classloading}
	at net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator.m_6929_(NoiseBasedChunkGenerator.java:428) ~[client-1.18.1-20211210.034407-srg.jar%23108!:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:seedfix.mixins.json:NoiseBasedChunkGeneratorMixin,pl:mixin:APP:seedfix.mixins.json:NoiseBasedChunkGeneratorAccessor,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkStatus.m_187762_(ChunkStatus.java:149) ~[client-1.18.1-20211210.034407-srg.jar%23108!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_183270_(ChunkStatus.java:313) ~[client-1.18.1-20211210.034407-srg.jar%23108!:?] {re:classloading}
	at net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262) ~[client-1.18.1-20211210.034407-srg.jar%23108!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.lambda$chunkGenerate$20(ChunkMap.java:686) ~[client-1.18.1-20211210.034407-srg.jar%23108!:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:polymorph.mixins.json:AccessorChunkMap,pl:mixin:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar%2337!:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$chunkGenerate$22(ChunkMap.java:684) ~[client-1.18.1-20211210.034407-srg.jar%23108!:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:polymorph.mixins.json:AccessorChunkMap,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1590592272 bytes (1516 MiB) / 4026531840 bytes (3840 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f08
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7212
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 24498.02
	Virtual memory used (MB): 19488.91
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 191.51
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['andreibear'/136, l='ServerLevel[New World]', x=12.50, y=66.00, z=73.50]]
	Data Packs: vanilla, mod:seedfix, mod:clienttweaks, mod:easymagic, mod:jei (incompatible), mod:goblintraders (incompatible), mod:mcwwindows, mod:kleeslabs, mod:waystones, mod:mcwpaintings, mod:controlling (incompatible), mod:citadel, mod:alexsmobs (incompatible), mod:itemborders, mod:dungeoncrawl, mod:curioofundying, mod:cdl, mod:mcwdoors, mod:bedspreads, mod:balm (incompatible), mod:carryon (incompatible), mod:jeresources, mod:skinlayers3d (incompatible), mod:tinyskeletons, mod:customizableelytra (incompatible), mod:enchdesc, mod:itemphysiclite, mod:ambientsounds (incompatible), mod:mousetweaks, mod:toolbelt (incompatible), mod:wildfire_gender (incompatible), mod:jade, mod:forge, mod:creativecore, mod:mcwtrpdoors, mod:mcwfences, mod:notenoughanimations (incompatible), mod:iceberg, mod:flywheel, mod:create, mod:curios, mod:collective, mod:cyclepaintings, mod:polymorph, mod:justenoughprofessions, mod:autoreglib (incompatible), mod:quark (incompatible), mod:storagedrawers (incompatible), mod:sit, mod:villagertools (incompatible), mod:hardcorerevival, mod:cfm (incompatible), mod:appleskin (incompatible), mod:puzzleslib, mod:voidtotem, mod:tradingpost
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	OptiFine Version: OptiFine_1.18.1_HD_U_H4
	OptiFine Build: 20211212-175054
	Render Distance Chunks: 14
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 472.12
	OpenGlRenderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		Amplified+Nether+1.0.1+_+Forge (1).jar            |Amplified Nether + Seed Fix   |seedfix                       |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		clienttweaks-forge-1.18-7.0.1.jar                 |Client Tweaks                 |clienttweaks                  |7.0.1               |DONE      |Manifest: NOSIGNATURE
		EasyMagic-v3.2.1-1.18.1-Forge.jar                 |Easy Magic                    |easymagic                     |3.2.1               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		jei-1.18.1-9.2.1.69.jar                           |Just Enough Items             |jei                           |9.2.1.69            |DONE      |Manifest: NOSIGNATURE
		goblintraders-1.7.0-1.18.1 (1).jar                |Goblin Traders                |goblintraders                 |1.7.0               |DONE      |Manifest: NOSIGNATURE
		mcw-windows-2.0.2-mc1.18.1 (1).jar                |Macaw's Windows               |mcwwindows                    |2.0.2               |DONE      |Manifest: NOSIGNATURE
		kleeslabs-forge-1.18-11.0.0 (1).jar               |KleeSlabs                     |kleeslabs                     |11.0.0              |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.18.1-9.0.1 (1).jar              |Waystones                     |waystones                     |9.0.1               |DONE      |Manifest: NOSIGNATURE
		mcw-paintings-1.0.2-mc1.18.1 (1).jar              |Macaw's Paintings             |mcwpaintings                  |1.0.2               |DONE      |Manifest: NOSIGNATURE
		Controlling-forge-1.18.1-9.0.11.jar               |Controlling                   |controlling                   |9.0.11              |DONE      |Manifest: NOSIGNATURE
		citadel-1.10.8-1.18.jar                           |Citadel                       |citadel                       |1.10.8              |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.15.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.15.1              |DONE      |Manifest: NOSIGNATURE
		ItemBorders-1.18.1-1.1.5.jar                      |Item Borders                  |itemborders                   |1.1.5               |DONE      |Manifest: NOSIGNATURE
		DungeonCrawl-1.18.1-2.3.6.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.3.6               |DONE      |Manifest: NOSIGNATURE
		curioofundying-forge-1.18-5.3.0.0 (1).jar         |Curio of Undying              |curioofundying                |1.18-5.3.0.0        |DONE      |Manifest: NOSIGNATURE
		Customized-Dungeon-Loot-1.17.x-(v.2.1.0).jar      |Customized Dungeon Loot       |cdl                           |2.1.0               |DONE      |Manifest: NOSIGNATURE
		mcw-doors-1.0.5-mc1.18.1 (1).jar                  |Macaw's Doors                 |mcwdoors                      |1.0.5               |DONE      |Manifest: NOSIGNATURE
		bedspreads-forge-1.18-5.1.0.4.jar                 |Bedspreads                    |bedspreads                    |1.18-5.1.0.4        |DONE      |Manifest: NOSIGNATURE
		balm-2.4.0+0.jar                                  |Balm                          |balm                          |2.4.0+0             |DONE      |Manifest: NOSIGNATURE
		carryon-1.18.1-1.17.0.5.jar                       |Carry On                      |carryon                       |1.17.0.5            |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.18.1-0.13.1.138.jar         |Just Enough Resources         |jeresources                   |0.13.1.138          |DONE      |Manifest: NOSIGNATURE
		3dSkinLayers-forge-mc1.18-1.3.1 (1).jar           |3dSkinLayers                  |skinlayers3d                  |1.3.1               |DONE      |Manifest: NOSIGNATURE
		TinySkeletons-v3.1.0-1.18.1-Forge.jar             |Tiny Skeletons                |tinyskeletons                 |3.1.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		customizableelytra-1.18-1.6.3.jar                 |Customizable Elytra           |customizableelytra            |1.18-1.6.3          |DONE      |Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.18.1-9.0.8.jar    |EnchantmentDescriptions       |enchdesc                      |9.0.8               |DONE      |Manifest: NOSIGNATURE
		ItemPhysicLite_v1.4.8_mc1.18.jar                  |ItemPhysic Lite               |itemphysiclite                |1.4.0               |DONE      |Manifest: NOSIGNATURE
		AmbientSounds_v5.0.3_mc1.18.1.jar                 |Ambient Sounds                |ambientsounds                 |3.0.3               |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.18-2.21.jar                 |Mouse Tweaks                  |mousetweaks                   |2.21                |DONE      |Manifest: NOSIGNATURE
		ToolBelt-1.18-1.18.0 (1).jar                      |Tool Belt                     |toolbelt                      |1.18.0              |DONE      |Manifest: NOSIGNATURE
		[Forge]+Wildfire+Female+Gender+Mod-2.8.1.jar      |Wildfire's Female Gender Mod  |wildfire_gender               |2.8.1               |DONE      |Manifest: NOSIGNATURE
		Jade-1.18-4.1.1.jar                               |Jade                          |jade                          |4.1.1               |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.18-universal.jar                |Forge                         |forge                         |39.0.18             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		CreativeCore_v2.4.1_mc1.18.1.jar                  |CreativeCore                  |creativecore                  |2.4.0               |DONE      |Manifest: NOSIGNATURE
		mcw-trapdoors-1.0.4-mc1.18.1 (1).jar              |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.4               |DONE      |Manifest: NOSIGNATURE
		mcw-fences-1.0.2-mc1.18.1 (1).jar                 |Macaw's Fences and Walls      |mcwfences                     |1.0.2               |DONE      |Manifest: NOSIGNATURE
		notenoughanimations-forge-1.4.0-mc1.18 (1).jar    |NotEnoughAnimations Mod       |notenoughanimations           |1.4.0               |DONE      |Manifest: NOSIGNATURE
		Iceberg-1.18.1-1.0.33.jar                         |Iceberg                       |iceberg                       |1.0.33              |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18-0.5.1.jar                     |Flywheel                      |flywheel                      |1.18-0.5.1          |DONE      |Manifest: NOSIGNATURE
		create-mc1.18.1_v0.4c.jar                         |Create                        |create                        |0.4c                |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.1-5.0.5.1.jar                   |Curios API                    |curios                        |1.18.1-5.0.5.1      |DONE      |Manifest: NOSIGNATURE
		collective-1.18.1-3.8 (1).jar                     |Collective                    |collective                    |3.8                 |DONE      |Manifest: NOSIGNATURE
		cyclepaintings_1.18.1-2.2 (1).jar                 |Cycle Paintings               |cyclepaintings                |2.2                 |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-1.18.1-0.35.jar                   |Polymorph                     |polymorph                     |1.18.1-0.35         |DONE      |Manifest: NOSIGNATURE
		JustEnoughProfessions-1.18-1.2.2 (1).jar          |Just Enough Professions (JEP) |justenoughprofessions         |1.2.2               |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.7-52.jar                             |AutoRegLib                    |autoreglib                    |1.7-52              |DONE      |Manifest: NOSIGNATURE
		Quark-3.0-334.jar                                 |Quark                         |quark                         |3.0-334             |DONE      |Manifest: NOSIGNATURE
		StorageDrawers-1.18.1-10.1.0.jar                  |Storage Drawers               |storagedrawers                |10.1.0              |DONE      |Manifest: NOSIGNATURE
		sit-1.18-1.3.1 (1).jar                            |Sit                           |sit                           |1.3.1               |DONE      |Manifest: NOSIGNATURE
		villagertools-1.18-1.0.2 (1).jar                  |villagertools                 |villagertools                 |1.18-1.0.2          |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		hardcorerevival-forge-1.18-8.0.0 (1).jar          |Hardcore Revival              |hardcorerevival               |8.0.0               |DONE      |Manifest: NOSIGNATURE
		furniture-7.0.0-pre27-1.18.1 (1).jar              |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre27         |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.18-2.2.0.jar                  |AppleSkin                     |appleskin                     |2.2.0               |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v3.1.3-1.18.1-Forge.jar                |Puzzles Lib                   |puzzleslib                    |3.1.3               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		voidtotem-forge-1.18.1-1.1.0 (1).jar              |Void Totem                    |voidtotem                     |1.18.1-1.1.0        |DONE      |Manifest: NOSIGNATURE
		TradingPost-v3.1.2-1.18.1-Forge.jar               |Trading Post                  |tradingpost                   |3.1.2               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
	Flywheel Backend: GL33 Instanced Arrays
	Crash Report UUID: 0847d429-4407-41ac-84a7-4bb4e3fd9915
	FML: 39.0
	Forge: net.minecraftforge:39.0.18

**Comment by Wedge1453** [comment]
try downgrading forge version to 39.017

**Comment by AlexModGuy** [comment]
fixed
