### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by MagmaSlime123** [Alex-the-666/AlexsMobs#855]
No need for a mod list as this mod is mentioned all over the report. However, one is provided in the report if you need it. Thank Forge for that.

[crash-2022-01-11_20.09.04-server.txt](https://github.com/Alex-the-666/AlexsMobs/files/7851353/crash-2022-01-11_20.09.04-server.txt)

**Comment by AlexModGuy** [comment]
update AM

**Comment by MagmaBro123** [comment]
Everything is updated already.
