### ISSUE TITLE
Lava from Lava Vision isn't visible with Optifine on, even if shaders are not being used

### ISSUE THREAD

**Issue by Inonedn** [Alex-the-666/AlexsMobs#867]
![2022-01-17_22 25 51](https://user-images.githubusercontent.com/36087299/149865740-c8abd27c-11c4-400c-b691-d55fa33e184d.png)

**Comment by Inonedn** [comment]
The mod works just fine, except this part

**Comment by TheCrispyBarrett** [comment]
I'm having this same issue presently in the current update.

**Comment by AlexModGuy** [comment]
dupe
