### ISSUE TITLE
Bear Pattern crashing 

### ISSUE THREAD

**Issue by LuigiTP** [Alex-the-666/AlexsMobs#877]
I tested for other patterns minecraft vanilla patterns nothing happened
This happened while in multiplayer it was only me that was affected tho 
i then tried it in singleplayer and as soon as i put the pattern in the loom the game crash
multiplayer report:
[crash-2022-01-20_23.11.51-client.txt](https://github.com/Alex-the-666/AlexsMobs/files/7909072/crash-2022-01-20_23.11.51-client.txt)

singleplayer report:
[crash-2022-01-20_23.17.19-client.txt](https://github.com/Alex-the-666/AlexsMobs/files/7909073/crash-2022-01-20_23.17.19-client.txt)
d

**Comment by AlexModGuy** [comment]
dupe
