### ISSUE TITLE
Mobs don't spawn in Terralith biomes

### ISSUE THREAD

**Issue by Robified0** [Alex-the-666/AlexsMobs#878]
Mobs still don't spawn in Terralith biomes, only in the vanilla biomes. This only occurs on the datapack version of Terralith - modded works fine.

This was listed as fixed in fix #787 , but it still doesn't seem to be the case. Is there additional configuration that needs to happen on my side, or is it just still bugged?

**Comment by unweeked** [comment]
For me it doesn't work on any version of Terralith. Only cockroaches spawn in caves, which is really not the reason for me to have alexs mobs xD
(I'm playing on my server though)

**Comment by PlummetStudios** [comment]
You need to do additional configuration as since Terralith is only a datapack, it does not use forge tags.
