### ISSUE TITLE
Server Crash issue

### ISSUE THREAD

**Issue by superroksak** [Alex-the-666/AlexsMobs#879]
Receiving following error.
Forge 39.0.55
Minecraft 1.18.1

Full mod list 

Alexs Mobs 1.16.0
Citadel 1.10.8
Cucumber 1.18.1-5.0.2
Decorative Blocks 1.18.1-2.0.2
Farmers Delighht 1.18.1-1.0.3
Golden Hopper 1.2.5-1.18.1
jei 1.18.1-9.2.1.69
Mystical Agriculture 1.18.1-5.0.1
Optifine 1.18.1
SmarterFarmers 1.18-1.2.1

Error message seems to be suggesting an issue of interation between hopper and capsid block, which I have in the world.

`<html><body>

[22Jan2022 01:31:10.340] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
--
 

<span class="level level-ERROR multiline">	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[server-1.18.1-20211210.034407-srg.jar%2347!/:?]
</span>
</body>
</html>`

**Comment by superroksak** [comment]
Full Log

https://pastebin.com/XU95eScV

**Comment by superroksak** [comment]
Full Server crash log

https://pastebin.com/rcTLcYEB

**Comment by AlexModGuy** [comment]
update alexs mobs
