### ISSUE TITLE
Server crash 1.16

### ISSUE THREAD

**Issue by aziz2077** [Alex-the-666/AlexsMobs#88]
Hi 

My server keeps crashing and it has something to do with AlexsMobs and Ice and Fire

https://pastebin.com/dE6ea4Kw

The modpack is TNP Limitless 3

Happy holidays

**Comment by Daejangnamu** [comment]
same #58

**Comment by Toilet-Man** [comment]
Happened to me too

**Comment by Alex-the-666** [comment]
dupe
