### ISSUE TITLE
Capsid Server Crash

### ISSUE THREAD

**Issue by JadeOfTheSky** [Alex-the-666/AlexsMobs#888]
Right clicking on a Capsid regardless of holding an item or not will crash a server.

**Comment by emihead** [comment]
Got this too. 99% sure it's because forge changed the logic for saving block NBT data recently.

[crash-2022-01-29_15.32.38-client.txt](https://github.com/Alex-the-666/AlexsMobs/files/7964672/crash-2022-01-29_15.32.38-client.txt)

**Comment by LivingLandmine** [comment]
Just encountered the same crash in my game.

https://pastebin.com/unb4aGmF

**Comment by Aulluna** [comment]
I got same issue

**Comment by 1mtwtfss1** [comment]
I got same issue in Singleplayer too

**Comment by LivingLandmine** [comment]
Thank you Alex for fixing the crash issues!
