### ISSUE TITLE
Rendering issue with the mimicube

### ISSUE THREAD

**Issue by PixelatedApples** [Alex-the-666/AlexsMobs#894]
https://pastebin.com/N3d3mkSt

If it's of any relevance, I'm playing on a server.

**Comment by rex706** [comment]
I am also having this issue with Kangaroos that are wearing armor.

It's an problem with using Forge version 39.0.57 or above as the Forge devs "Simplif[ied] usage of IItemRenderProperties::getArmorModel", according to the changelog, which is the method in question that is causing the crash.
