### ISSUE TITLE
Crocodiles can’t be attacked while being grabbed

### ISSUE THREAD

**Issue by Inonedn** [Alex-the-666/AlexsMobs#9]

**Comment by Inonedn** [comment]
In Addition, other mobs can attack while being grabbed

**Comment by GatoLeyo** [comment]
Maybe it is intended but not sure, the crimson mosquito can't be attacked as well most of the time

**Comment by CINQ-MARS** [comment]
Hope this is gonna be answered... Is it intended or not, and if so, is it not a little overpowered? It's a shame 'cause it's such a cool mob but it is so unsatisfying to strike back without any results ; feels like being trapped in an animated scene during a gameplay and knowing instantly "well okay, I'm dead can this thing end please"... And after that, you go get your stuff back and get the same thing again and again.

**Comment by Alex-the-666** [comment]
fixed
