### ISSUE TITLE
[1.18.1] Mimicube crashed my game

### ISSUE THREAD

**Issue by Sharitz** [Alex-the-666/AlexsMobs#900]
I can't log into my save since when mimicube attacked me :< there is a chance to recover somehow my save or, fix the problem?  :>

[crash-2022-02-02_00.05.24-client.txt](https://github.com/Alex-the-666/AlexsMobs/files/7982493/crash-2022-02-02_00.05.24-client.txt)

**Comment by Sharitz** [comment]
I noticed that the game crash occurs only because of the minicube when the player is wearing armor

**Comment by TheRetrolizer** [comment]
Had the same issue here. Crash file:
[crash-2022-02-02_21.30.31-client.txt](https://github.com/Alex-the-666/AlexsMobs/files/7991462/crash-2022-02-02_21.30.31-client.txt)

**Comment by E-T-C101** [comment]
Same issue here! 
The crash only happens when I walk into the chunk where the Mimicube is at.
Is there a way of changing the world's difficulty without actually going into the world? Since I'm at the chunk where the Mimicube is at, I can't really open the world without it crashing instantly. I'm guessing changing the difficulty will make the Mimicube disappear and I'll be able to grab my stuff and leave.

**Comment by noncom** [comment]
Most likely related to the change in Forge: https://github.com/MinecraftForge/MinecraftForge/commit/fd522d38b00f6b7e8021fa75634a9aec74c5c301#diff-2dc5c128112e105ce820bb71ed201942b398c677270c6ae719f2da975b6daa5eL282

**Comment by DingyTomb** [comment]
have you been able to solve entering your world again? I'm having the same crash when start up thing
edit: never mind I got it, i just disabled the mod, played my save and then enabled the mod again and its good to go

**Comment by Sharitz** [comment]
> have you been able to solve entering your world again? I'm having the same crash when start up thing edit: never mind I got it, i just disabled the mod, played my save and then enabled the mod again and its good to go

Yeah that helped a lot, thanks! I just hope that problem with mimicube will be fixed, for now i will just kill them from distance, again thanks <3
