### ISSUE TITLE
Mimicubes crash the game when trying to put on a helmet

### ISSUE THREAD

**Issue by Warhand** [Alex-the-666/AlexsMobs#912]
While playing around in a custom modpack I discovered that mimicubes would crash the game when attacked, after messing around a bit, and loading up a new profile that only had Alex's mobs and its dependency it would still happen, and after a bit more testing I found it only happened when the mimicubes tried to render the players helmet, it doesn't happen with either shields or the item in the players main hand.

Heres the crash report from my latest test, hopefully this will be a rather simple thing to fix, as it makes it so I have to completely disable mimicubes if I want to play with Alex's mobs installed.
(As an aside, the option to disable individual mobs from spawning at all, rather than just having to leave the list of biomes they can spawn in empty, would be appreciated.)

[crash-2022-02-07_13.05.38-client.txt](https://github.com/Alex-the-666/AlexsMobs/files/8017711/crash-2022-02-07_13.05.38-client.txt)

**Comment by z0rkie** [comment]
This happens to me as well.

**Comment by z0rkie** [comment]
> This happens to me as well.

https://pastebin.com/M5mgfWzx
