### ISSUE TITLE
Dimensional Carver doesn't seem to allow more than one use

### ISSUE THREAD

**Issue by yifo123** [Alex-the-666/AlexsMobs#915]
For each player to use the pickaxe it only opens a portal once, and cannot be used to open another portal, even after the initial portal disappears. Despite the 20 durability, regardless of putting on mending or unbreaking, for some reason you just can't open another portal if you've already opened one before.
We are playing on a multiplayer server, however even when I've tried on singleplayer, I cannot open more than one portal.
No durability was taken when trying to open a portal the second time. Giving the dimensional carver to another player allows them to open a portal, however it doesn't work when they try for a second time too.
Not sure if this is the fault of having other mods conflicting or something to do with the Alex's mobs mod itself, but we are playing on a custom modpack. I'm not sure of any known conflicts which may cause it but my guess it's that the dimensional carver itself might be bugged perhaps?

(1.16.5)

**Comment by jspzyhl** [comment]
I have the same problem...

**Comment by jspzyhl** [comment]
I found the solution. Just pressing the right mouse button even after the animation disappear, after a few seconds the protal will open. I think this may caused by server lag, so maybe we should make the anination disappear after the portal really created?

**Comment by yifo123** [comment]
> I found the solution. Just pressing the right mouse button even after the animation disappear, after a few seconds the protal will open. I think this may caused by server lag, so maybe we should make the anination disappear after the portal really created?

Oh wow you're right! I just tried it, and it does still work if you hold down right click for longer.
I guess it would make sense for them to make it so that the pickaxe only stops doing its mining animation until the portal spawns to avoid any more confusion.

Other than that I guess it's this "bug" turns out to just be server-side lag. I guess I'll close the thread then. Thanks for finding this out :)
