### ISSUE TITLE
Brown Mushrooms can't bleed Husklins

### ISSUE THREAD

**Issue by 1mtwtfss1** [Alex-the-666/AlexsMobs#918]
Mod version:
1.16.0

Forge version:
39.0.64

Singleplayer or Multiplayer:
Singleplayer

Installed mods:
alexsmobs-1.16.0
citadel-1.10.8-1.18

Description of the problem:
If you feed Tusklins with Brown Mushrooms, they won't enter love mode. Only Red Mushrooms can make them enter love mode. Brown Mushrooms also can't takes off of the remaining time to grow up. You must feed them with Red Mushrooms again.

Pictures:
![360截图20220210095847801](https://user-images.githubusercontent.com/88222275/153322628-84780b27-eea5-494f-9b42-3d5f385ebcf0.png)

**Comment by AlexModGuy** [comment]
intended. brown ones make them passive

**Comment by 1mtwtfss1** [comment]
> intended. brown ones make them passive

Thank you, and I have found out that this is due to a mistake in the Simplified Chinese translation.
