### ISSUE TITLE
Armored kangaroo crash game

### ISSUE THREAD

**Issue by Romenakss** [Alex-the-666/AlexsMobs#922]
Kangaroo who wear iron chestplate crash game. And please can u repair it fast, beacause of that i can do anything its inposible to kill him or get armor back. I cant even use command /kill . Its only in newest verion. i changed a version and killed him all. All work now. But its still bug'

**Comment by ghost** [comment]
fixed in alexsmobs-1.17.0 please close the issue

**Comment by AlexModGuy** [comment]
^

**Comment by Romenakss** [comment]
No its bug from 1.17.0. And it wasnt in older versions. Wait WHAT how it is fixed when i wasnt had this bug in older, but i have it in newest
