### ISSUE TITLE
Throwing an enchanted trident while wearing an enchanted netherite helmet on a mimicube made my minecraft crash

### ISSUE THREAD

**Issue by Cassowarinium** [Alex-the-666/AlexsMobs#933]
I was just busy exploring in the End and approached a Mimicube and I wanted to throw the trident at the Mimicube and when the trident hit the Mimicube, the game had crashed, and I can't play on my own world anymore.

**Comment by Carro1001** [comment]
This should not happen anymore, please update your Alex's Mobs and forge, as both had internal changes to armor models

**Comment by Cassowarinium** [comment]
Thanks, the problem is gone, because I realized that my Forge needed to be updated.
