### ISSUE TITLE
French book

### ISSUE THREAD

**Issue by polikarpov5** [Alex-the-666/AlexsMobs#935]
hi, I propose a translation by google translate in French
Thank you for your great mod
[fr_fr.json.zip](https://github.com/Alex-the-666/AlexsMobs/files/8055117/fr_fr.json.zip)

**Comment by AlexModGuy** [comment]
"block.ava.repairable_black_stained_glass": "Vitrail noir réparable",
  "block.ava.repairable_black_stained_glass_pane": "Verre vitrail noir réparable",
  "block.ava.repairable_blue_stained_glass": "Vitrail bleu réparable",
  "block.ava.repairable_blue_stained_glass_pane": "Vitrail bleu réparable",
  "block.ava.repairable_brown_stained_glass": "Vitrail marron réparable",
  
  this is not a translation for this mod.
