### ISSUE TITLE
Mimicube crashes game when trying to transform

### ISSUE THREAD

**Issue by BasDerilov** [Alex-the-666/AlexsMobs#936]
When the mimicube tries to transform into a player it causes the game to crash, thankfully it doesn't crash the server.
The log says it has something to do with armor rendering I was wearing diamond armor but it had modded enchants so this could hvae something to do with it.
[latest.log](https://github.com/Alex-the-666/AlexsMobs/files/8055999/latest.log)

**Comment by AlexModGuy** [comment]
This is not a crash log. Are you using the latest versions of Alex's Mobs and Forge?

**Comment by BasDerilov** [comment]
I am one version behind, the game log is all I had no crash log was generated but I think it was some armor rendering function causing the crash. I noticed you pushed out a fix for the mimicube in the latest version. Did it by any chance have anything to do with armor rendering? If so I will just close the issue since this is my exact problem.

**Comment by Romenakss** [comment]
I have this bug in newest version too :/

**Comment by BasDerilov** [comment]
> I have this bug in newest version too :/

Are you sure you are on the latest version? 1.17.0 is the latest and it has fixed the issue for me.
