### ISSUE TITLE
Unable to feed Gorillas bananas

### ISSUE THREAD

**Issue by SirKrunk** [Alex-the-666/AlexsMobs#943]
[latest.log](https://github.com/Alex-the-666/AlexsMobs/files/8068359/latest.log)
Steps:
1. Right click on Gorilla with Banana, nothing in offhand.
2. Try step 1 again
3. Rage

Alex's Mobs version: alexsmobs-1.17.0
Citadel version: 1.10.10
Minecraft Version: Release 1.18.1
Forge Version: 39.0.76

**Comment by LivingLandmine** [comment]
Some mobs in this mod do not take food directly from you, you probably have to drop it for them and let them pick it up.

**Comment by SirKrunk** [comment]
ohhh, thank you! once i threw the bananas at them they started eating it
