### ISSUE TITLE
mimicube locked me out of my server after shooting it wtih a harming arrow

### ISSUE THREAD

**Issue by DekkyOwO** [Alex-the-666/AlexsMobs#954]
https://pastebin.com/Yc49nPsk

**Comment by alvarohulse** [comment]
It also happens when the mimicube takes damage from something like thorns. I'm guessing it has to do with how the cube receives damage. I'm saying thorns because I got locked out when a mimicube rubbed against me.

**Comment by alvarohulse** [comment]
It seems like this issue should be resolved in the latest update as of today.
