### ISSUE TITLE
Alex's mobs creative tab crashed my game.

### ISSUE THREAD

**Issue by Warhand** [Alex-the-666/AlexsMobs#969]
I'm not exactly sure what it tried to render, but based on this crash report, one of the entities in the loop for what it displays in the creative tab didn't really work out and crashed my game.

https://pastebin.com/esGJ966T

**Comment by AlexModGuy** [comment]
> at com.mrcrayfish.framework.common.data.SyncedEntityData.hasSyncedDataKey

bug is with crayfish framework
