### ISSUE TITLE
Need an option for Cachalot Whale's wooden block destroying

### ISSUE THREAD

**Issue by RedBeast1959** [Alex-the-666/AlexsMobs#970]
I liked Cachalot Whale's ability to destroy wooden block when it charge, because it remined me the Moby Dick... until it smashed and destroyed my whoel fisherman house and wooden galion ship just to eat squids. I really wish there's an option for turning on/off Cachalot Whale's wooden block griefing just like leaf cutter ants and mungus biome changing ability. 

Also, Can you make guardian fight back against giant squid? One single giant squid turns sea monument into slaughterhouse.

**Comment by Kirklegacy** [comment]
I second that. I'm playing All The Mods 7 and the Cachalot Whale destroyed my port and my boat. At least against creepers I can prevent them from exploding.
