### ISSUE TITLE
Alex Mobs Banner Crashes

### ISSUE THREAD

**Issue by Beholder504** [Alex-the-666/AlexsMobs#983]
While attempting to put the ''Sun'' banner on a banner, my game crashed. Can someone help me ?

https://crashy.net/eTS7gp00sCUorwhlPIRO

**Comment by UlfurCorp** [comment]
Got the same problem with other banners from the mod as well. 
Here is the crash report : 
https://pastebin.com/uvhZAfbb
I have all banners from the mod so let me know if you need more crash report from all of them.
