### ISSUE TITLE
Putting armor on kangaroo crashes my game

### ISSUE THREAD

**Issue by litlebitwise** [Alex-the-666/AlexsMobs#986]
whenever I put armor on a kangaroo it just closes my game and crashes. I am using the 1.18 version.

It gave me this error: The game crashed whilst rendering entity in world
Error: java.lang.NoSuchMethodError: 'net.minecraft.client.model.Model net.minecraftforge.client.ForgeHooksClient.getArmorModel(net.minecraft.world.entity.LivingEntity, net.minecraft.world.item.ItemStack, net.minecraft.world.entity.EquipmentSlot, net.minecraft.client.model.HumanoidModel)'
Exit Code: -1

**Comment by AlexModGuy** [comment]
update forge version
