### ISSUE TITLE
Leviathan causes server crash in overworld

### ISSUE THREAD

**Issue by antoine-courant** [Alex-the-666/AlexsMobs#990]
Hello !
I was, out of curiosity, trying to bring the Leviathan in the overworld with my dimensionnal carver, but when he just went through the portal, the server became very very laggy, almost frozen until it just crashed
When I rebooted it, the server made me rollback just before I made the Leviathan go through the portal
And it does it each time I try

**Comment by M4DMAXX** [comment]
Wow... a Mod cause Server Crash... dont matter its know or unkown... just close the Issue ... its a bit ridiculous
