### ISSUE TITLE
[1.18.1] Crash when typing into "Configured Mod, Search Bar".

### ISSUE THREAD

**Issue by Gbergz** [Alex-the-666/AlexsMobs#995]
Title^

Getting a crash when typing some letters into the Configured Mod Search Bar.
Started happening with the most recent Alex's Mobs update from this post ([v1.17.2](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs/files/3693598)).

**Versions**:
Minecraft: 1.18.1
Forge: 39.1.2
Alex's Mobs: 1.17.2
Citadel: 1.10.10-1.18
Catalogue: 1.6.0-1.18.1

**Crash-Report**: https://gist.github.com/Gbergz/d2642410d1e5e2ceb6a8e711de371fa0

**Comment by AlexModGuy** [comment]
will be fixed in next release
