### ISSUE TITLE
Crash on selecting Mods in Main Menu

### ISSUE THREAD

**Issue by EldrinFal** [Alex-the-666/AlexsMobs#996]
[crash-2022-03-16_04.25.42-client.txt](https://github.com/Alex-the-666/AlexsMobs/files/8258918/crash-2022-03-16_04.25.42-client.txt)

I have the mod Catalogue installed in case that is relevant.  AlexMobs 1.17.1 did not crash.

Basically, when I click on the Mod menu item on the main screen, I get a CTD.

**Comment by drakray** [comment]
got the same crash after installing 1.17.2, seeing the green dot of "mod to update", clicking [Mods], CTD

**Comment by Wilevar** [comment]
Same here. I have Configured and Catalogue installed as well, so I'll have to test to see if it's a mod conflict.

Edit:
Tested without Configured, no change. CTD.
Tested without Catalogue, no crash. So it's definitely a mod conflict with Catalogue.

**Comment by Shibva** [comment]
please reopen the issue @Alex-the-666 , this issue is still present as of v 1.17.4

Crash: https://gist.github.com/SteamDoge9000/2dfc28146a690b92ccdfd8785129eecc

**Comment by EldrinFal** [comment]
Yes, I am still having the same issue as well.  Using MC 1.18.1.

**Comment by drakray** [comment]
I think @Alex-the-666 closed the issue because it's fixed inDev, only not yet available on CF
