### ISSUE TITLE
Incorrect mod version?

### ISSUE THREAD

**Issue by TuffCat** [Alex-the-666/AlexsMobs#998]
Hey, so I downloaded the 1.16.0 version of the mod because I was excited for jerboas in minecraft. However, upon using the correct 1.16 version of the mod, I was met with only the features from release 1.12.0. Is anyone else having this issue? Have you had and have fixed this issue? if so, how did you fix it? Also I am running forge version 1.16.5.

**Comment by PlummetStudios** [comment]
The 1.16.5 version of the mod doesn't contain any mobs from the updates after 1.12.0, 1.16.5 is an abandoned version of the mod and will no longer receive support.

**Comment by TuffCat** [comment]
Thank you! Will versions like 1.16.4 or 1.16.6 work? If they do, I'll do my best to get that version with the other mods that I use <3

**Comment by PlummetStudios** [comment]
the only versions that have stuff like the Jerboa are at least the versions made for 1.18.1 forge.
